project:
  type: website
  output-dir: _site

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu:
        - text: "Exercise 1A - Geospatial Data Wrangling"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html"
        - text: "Exercise 1B - Choropleth Mapping"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
        - text: "Exercise 2A - 1st Order spatial point pattern analysis methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html"
        - text: "Exercise 2B - 2nd Order spatial point pattern analysis methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html"
        - text: "Exercise 3A - Spatio-Temporal Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Exercise 4A - Spatial Weights and Applications"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Exercise 5A - Global Measures of Spatial Autocorrelation"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
        - text: "Exercise 5B - Local Measures of Spatial Autocorrelation"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
        - text: "Exercise 6A - Geographic Segmentation"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Exercise 7A - Calibrating Hedonic Pricing Model"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
      - text: "In-Class Exercises"
        menu:
        - text: "In-Class : Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "In-Class : Exercise 2"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "In-Class : Exercise 3a"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03a.html"
        - text: "In-Class : Exercise 3b"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "In-Class : Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In-Class : Exercise 5"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
        - text: "In-Class : Exercise 6"
          href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
      - text: "Take-Home Exercises"
        menu:
        - text: "Exercise 1 - Geospatial Analytics for Public Good"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"

    right:
      - href: index.qmd
        text: "Home"
      - href: http://ssinha8752.github.io/Shubham/
        text: "ABOUT ME"
      - icon: linkedin
        href: https://www.linkedin.com/in/am-shubh-am/
        aria-label: Linkedin
      - icon: github
        href: https://github.com/ssinha8752
        aria-label: Github

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

