---
title: "In-class Exercise 03b"
author: "Shubham Sinha"
---

---
title: "Take home Exercise 1 : Geospatial Analytics for Public Good"
author: "Shubham Sinha"
date: "September 13, 2025"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

## 1 Load the R package

```{r}
pacman::p_load(sf, tmap, tidyverse,httr)
```

## 2 Import the ACRA data 

```{r}
folder_path <- "data/aspatial/ACRA"
file_list <- list.files(path = folder_path,
                        pattern = "^ACRA*.*\\.csv$",
                        full.names = TRUE)
```

```{r}
acra_data <- file_list %>%
  map_dfr(read_csv)
```
Save the data into rds folder 

```{r}
write_rds(acra_data,
          "data/rds/acra_data.rds")
```

## 3 Tidying the ACRA data

```{r}
biz_56111 <- acra_data %>%
  select(1:24) %>%
  filter(primary_ssic_code == 56111) %>%
  rename(date = registration_incorporation_date) %>%
  mutate(date = as.Date(date),
         YEAR = year(date),
         MONTH_NUM = month(date),
         MONTH_ABBR = month(date,
                            label = TRUE,
                            abbr = TRUE)) %>%
  mutate(
    postal_code = str_pad(postal_code,
    width = 6, side = "left", pad = "0")) %>%
            filter(YEAR == 2025)
```


## 4 Geocoding 

```{r}
postcodes <- unique(biz_56111$postal_code)

url <- "https://onemap.gov.sg/api/common/elastic/search"


found <-data.frame()
not_found <- data.frame(postcode = character())

for(pc in postcodes) {
  query <- list(
    searchVal = pc,
    returnGeom = "Y",
    getAddrDetails = "Y",
    pageNum = "1"
  )
  
  res <- GET(url,query = query)
  json <- content(res)
  
  if(json$found !=0) {
    df <- as.data.frame(json$results,stringAsFactors = FALSE)
    df$input_postcode <- pc
    found <- bind_rows(found,df)
  } else {
    not_found <- bind_rows(not_found,data,frame(postcode = pc))
  }
}
```

## 5 Appending the location information


```{r}
biz_56111 = biz_56111 %>%
  left_join(found,
            by = c('postal_code' = 'POSTAL'))
```


## 6 Converting into SF data frame

```{r}
biz_56111_sf <- st_as_sf(biz_56111, 
                         coords = c("X", "Y"),
                         crs = 3414)
```
