<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Shubham Sinha">
<meta name="dcterms.date" content="2024-10-18">
<title>In-class Exercise 7 – ISSS626-GAA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-df479d6c4d77d0e0dfbcb5361179d7fd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="../../styles.css">
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">
<li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html">
 <span class="dropdown-text">Exercise 1A - Geospatial Data Wrangling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html">
 <span class="dropdown-text">Exercise 1B - Choropleth Mapping</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html">
 <span class="dropdown-text">Exercise 2A - 1st Order spatial point pattern analysis methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html">
 <span class="dropdown-text">Exercise 2B - 2nd Order spatial point pattern analysis methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Exercise 3A - Spatio-Temporal Point Patterns Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Exercise 4A - Spatial Weights and Applications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html">
 <span class="dropdown-text">Exercise 5A - Global Measures of Spatial Autocorrelation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html">
 <span class="dropdown-text">Exercise 5B - Local Measures of Spatial Autocorrelation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html">
 <span class="dropdown-text">Exercise 6A - Geographic Segmentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html">
 <span class="dropdown-text">Exercise 7A - Calibrating Hedonic Pricing Model</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-Class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">
<li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex01/In-class_Ex01.html">
 <span class="dropdown-text">In-Class : Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html">
 <span class="dropdown-text">In-Class : Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03a.html">
 <span class="dropdown-text">In-Class : Exercise 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03.html">
 <span class="dropdown-text">In-Class : Exercise 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-Class : Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html">
 <span class="dropdown-text">In-Class : Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex06/In-class_Ex06.html">
 <span class="dropdown-text">In-Class : Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex07/In-class_Ex07.html">
 <span class="dropdown-text">In-Class : Exercise 7</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">
<li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Exercise 1 - Geospatial Analytics for Public Good</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html">
 <span class="dropdown-text">Exercise 2 - Bus Passenger Demand in Singapore</span></a>
  </li>  
    </ul>
</li>
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="http://ssinha8752.github.io/Shubham/"> 
<span class="menu-text">ABOUT ME</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/am-shubh-am/"> <i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ssinha8752"> <i class="bi bi-github" role="img" aria-label="Github">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">1</span> Overview</a></li>
  <li><a href="#learning-outcome" id="toc-learning-outcome" class="nav-link" data-scroll-target="#learning-outcome"><span class="header-section-number">2</span> Learning Outcome</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"><span class="header-section-number">3</span> The Data</a></li>
  <li><a href="#installing-and-launching-the-r-packages" id="toc-installing-and-launching-the-r-packages" class="nav-link" data-scroll-target="#installing-and-launching-the-r-packages"><span class="header-section-number">4</span> Installing and Launching the R Packages</a></li>
  <li>
<a href="#geospatial-data-wrangling" id="toc-geospatial-data-wrangling" class="nav-link" data-scroll-target="#geospatial-data-wrangling"><span class="header-section-number">5</span> Geospatial Data Wrangling</a>
  <ul class="collapse">
<li><a href="#importing-geospatial-data" id="toc-importing-geospatial-data" class="nav-link" data-scroll-target="#importing-geospatial-data"><span class="header-section-number">5.1</span> Importing geospatial data</a></li>
  <li><a href="#updating-crs-information" id="toc-updating-crs-information" class="nav-link" data-scroll-target="#updating-crs-information"><span class="header-section-number">5.2</span> Updating CRS information</a></li>
  </ul>
</li>
  <li>
<a href="#aspatial-data-wrangling" id="toc-aspatial-data-wrangling" class="nav-link" data-scroll-target="#aspatial-data-wrangling"><span class="header-section-number">6</span> Aspatial Data Wrangling</a>
  <ul class="collapse">
<li><a href="#importing-the-aspatial-data" id="toc-importing-the-aspatial-data" class="nav-link" data-scroll-target="#importing-the-aspatial-data"><span class="header-section-number">6.1</span> Importing the aspatial data</a></li>
  <li><a href="#converting-aspatial-data-frame-into-a-sf-object" id="toc-converting-aspatial-data-frame-into-a-sf-object" class="nav-link" data-scroll-target="#converting-aspatial-data-frame-into-a-sf-object"><span class="header-section-number">6.2</span> Converting aspatial data frame into a sf object</a></li>
  </ul>
</li>
  <li>
<a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda"><span class="header-section-number">7</span> Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
<li><a href="#eda-using-statistical-graphics" id="toc-eda-using-statistical-graphics" class="nav-link" data-scroll-target="#eda-using-statistical-graphics"><span class="header-section-number">7.1</span> EDA using statistical graphics</a></li>
  <li><a href="#multiple-histogram-plots-distribution-of-variables" id="toc-multiple-histogram-plots-distribution-of-variables" class="nav-link" data-scroll-target="#multiple-histogram-plots-distribution-of-variables"><span class="header-section-number">7.2</span> Multiple Histogram Plots distribution of variables</a></li>
  </ul>
</li>
  <li>
<a href="#hedonic-pricing-modelling-in-r" id="toc-hedonic-pricing-modelling-in-r" class="nav-link" data-scroll-target="#hedonic-pricing-modelling-in-r"><span class="header-section-number">8</span> Hedonic Pricing Modelling in R</a>
  <ul class="collapse">
<li><a href="#simple-linear-regression-method" id="toc-simple-linear-regression-method" class="nav-link" data-scroll-target="#simple-linear-regression-method"><span class="header-section-number">8.1</span> Simple Linear Regression Method</a></li>
  <li><a href="#multiple-linear-regression-method" id="toc-multiple-linear-regression-method" class="nav-link" data-scroll-target="#multiple-linear-regression-method"><span class="header-section-number">8.2</span> Multiple Linear Regression Method</a></li>
  <li><a href="#building-a-hedonic-pricing-model-using-multiple-linear-regression-method" id="toc-building-a-hedonic-pricing-model-using-multiple-linear-regression-method" class="nav-link" data-scroll-target="#building-a-hedonic-pricing-model-using-multiple-linear-regression-method"><span class="header-section-number">8.3</span> Building a hedonic pricing model using multiple linear regression method</a></li>
  <li><a href="#revising-the-model" id="toc-revising-the-model" class="nav-link" data-scroll-target="#revising-the-model"><span class="header-section-number">8.4</span> Revising the model</a></li>
  <li><a href="#preparing-publication-quality-table-gtsummary-method" id="toc-preparing-publication-quality-table-gtsummary-method" class="nav-link" data-scroll-target="#preparing-publication-quality-table-gtsummary-method"><span class="header-section-number">8.5</span> Preparing Publication Quality Table: gtsummary method</a></li>
  <li><a href="#regression-diagnostics" id="toc-regression-diagnostics" class="nav-link" data-scroll-target="#regression-diagnostics"><span class="header-section-number">8.6</span> Regression Diagnostics</a></li>
  </ul>
</li>
  <li>
<a href="#building-hedonic-pricing-models-using-gwmodel" id="toc-building-hedonic-pricing-models-using-gwmodel" class="nav-link" data-scroll-target="#building-hedonic-pricing-models-using-gwmodel"><span class="header-section-number">9</span> Building Hedonic Pricing Models using GWmodel</a>
  <ul class="collapse">
<li><a href="#building-fixed-bandwidth-gwr-model" id="toc-building-fixed-bandwidth-gwr-model" class="nav-link" data-scroll-target="#building-fixed-bandwidth-gwr-model"><span class="header-section-number">9.1</span> Building Fixed Bandwidth GWR Model</a></li>
  </ul>
</li>
  <li>
<a href="#building-adaptive-bandwidth-gwr-model" id="toc-building-adaptive-bandwidth-gwr-model" class="nav-link" data-scroll-target="#building-adaptive-bandwidth-gwr-model"><span class="header-section-number">10</span> Building Adaptive Bandwidth GWR Model</a>
  <ul class="collapse">
<li><a href="#computing-the-adaptive-bandwidth-with-aic" id="toc-computing-the-adaptive-bandwidth-with-aic" class="nav-link" data-scroll-target="#computing-the-adaptive-bandwidth-with-aic"><span class="header-section-number">10.1</span> Computing the adaptive bandwidth witH AIC</a></li>
  <li><a href="#constructing-the-adaptive-bandwidth-gwr-model" id="toc-constructing-the-adaptive-bandwidth-gwr-model" class="nav-link" data-scroll-target="#constructing-the-adaptive-bandwidth-gwr-model"><span class="header-section-number">10.2</span> Constructing the adaptive bandwidth gwr model</a></li>
  </ul>
</li>
  <li><a href="#converting-sdf-into-sf-data.frame" id="toc-converting-sdf-into-sf-data.frame" class="nav-link" data-scroll-target="#converting-sdf-into-sf-data.frame"><span class="header-section-number">11</span> Converting SDF into sf data.frame</a></li>
  <li><a href="#visualising-and-plotting-of-r2-in-tampinies" id="toc-visualising-and-plotting-of-r2-in-tampinies" class="nav-link" data-scroll-target="#visualising-and-plotting-of-r2-in-tampinies"><span class="header-section-number">12</span> Visualising and PLotting of R2 in Tampinies</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">In-class Exercise 7</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shubham Sinha </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 18, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 18, 2025</p>
    </div>
  </div>
    
  </div>
  


</header><section id="overview" class="level2" data-number="1"><h2 data-number="1" class="anchored" data-anchor-id="overview">
<span class="header-section-number">1</span> Overview</h2>
<p>In this exercise, we will learn to build <a href="https://www.investopedia.com/terms/h/hedonicpricing.asp">hedonic pricing</a> models for private high-rise property using Geographically Weighted Regression (GWR) methods to account for non-stationary variables.</p>
<p><strong>Geographically weighted regression (GWR)</strong> is a spatial statistical technique that takes non-stationary variables into consideration (e.g., climate; demographic factors; physical environment characteristics) and models the local relationships between these independent variables and an outcome of interest (also known as dependent variable).</p>
<blockquote class="blockquote">
<p>In this exercise, The dependent variable is the resale prices of condominium in 2015. The independent variables are divided into either structural and locational.</p>
</blockquote>
<p>We will be using the <a href="https://www.jstatsoft.org/article/view/v063i17"><strong>GWmodel</strong></a> package. It provides a collection of localised spatial statistical methods, namely: GW summary statistics, GW principal components analysis, GW discriminant analysis and various forms of GW regression; some of which are provided in basic and robust (outlier resistant) forms. Commonly, outputs or parameters of the GWmodel are mapped to provide a useful exploratory tool, which can often precede (and direct) a more traditional or sophisticated statistical analysis.</p>
</section><section id="learning-outcome" class="level2" data-number="2"><h2 data-number="2" class="anchored" data-anchor-id="learning-outcome">
<span class="header-section-number">2</span> Learning Outcome</h2>
<ul>
<li>Understand the basics of geographically weighted regression (GWR).</li>
<li>Build and evaluate hedonic pricing models using GWR.</li>
<li>Convert geospatial and aspatial data into appropriate formats for analysis.</li>
<li>Perform exploratory data analysis (EDA) using statistical graphics.</li>
<li>Visualize the model outputs and spatial patterns using various R packages.</li>
<li>Assess spatial autocorrelation and other statistical properties of model residuals.</li>
<li>Compare and interpret fixed and adaptive bandwidth GWR models.</li>
</ul></section><section id="the-data" class="level2" data-number="3"><h2 data-number="3" class="anchored" data-anchor-id="the-data">
<span class="header-section-number">3</span> The Data</h2>
<p>The following 2 datasets will be used in this study:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th><strong>Data Set</strong></th>
<th><strong>Description</strong></th>
<th><strong>Format</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>MP14_SUBZONE_WEB_PL</td>
<td>URA Master Plan 2014’s planning subzone boundaries represented as polygon features.</td>
<td>ESRI Shapefile</td>
</tr>
<tr class="even">
<td>condo_resale_2015.csv</td>
<td>Data on condominium resale prices in 2015, including structural and locational attributes.</td>
<td>CSV</td>
</tr>
</tbody>
</table></section><section id="installing-and-launching-the-r-packages" class="level2" data-number="4"><h2 data-number="4" class="anchored" data-anchor-id="installing-and-launching-the-r-packages">
<span class="header-section-number">4</span> Installing and Launching the R Packages</h2>
<p>The following R packages will be used in this exercise:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th><strong>Package</strong></th>
<th><strong>Purpose</strong></th>
<th><strong>Use Case in Exercise</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>sf</strong></td>
<td>Manages, processes, and manipulates vector-based geospatial data.</td>
<td>Handling and converting geospatial data such as the URA Master Plan boundaries.</td>
</tr>
<tr class="even">
<td><strong>GWmodel</strong></td>
<td>Calibrates geographically weighted models for local spatial analysis.</td>
<td>Building hedonic pricing models using fixed and adaptive bandwidth GWR methods.</td>
</tr>
<tr class="odd">
<td><strong>olsrr</strong></td>
<td>Performs diagnostics and builds better multiple linear regression models.</td>
<td>Testing for multicollinearity, normality, and linearity of the regression model.</td>
</tr>
<tr class="even">
<td><strong>corrplot</strong></td>
<td>Provides visual tools to explore data correlation matrices.</td>
<td>Visualizing relationships between independent variables in the dataset.</td>
</tr>
<tr class="odd">
<td><strong>tmap</strong></td>
<td>Creates static and interactive thematic maps using cartographic quality elements.</td>
<td>Visualizing the geospatial distribution of condominium resale prices and other model outputs.</td>
</tr>
<tr class="even">
<td><strong>tidyverse</strong></td>
<td>A collection of packages for data science tasks such as data manipulation, visualization, and modeling.</td>
<td>Importing CSV files, wrangling data, and performing data transformations and visualizations.</td>
</tr>
<tr class="odd">
<td><strong>ggpubr</strong></td>
<td>Enhances ‘ggplot2’ for easier ‘publication-ready’ plots.</td>
<td>Creating small multiple histograms and scatterplots for exploratory data analysis.</td>
</tr>
</tbody>
</table>
<p>To install and load these packages, use the following code:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">olsrr</span>, <span class="va">corrplot</span>, <span class="va">ggpubr</span>, </span>
<span>               <span class="va">sf</span>, <span class="va">sfdep</span>, <span class="va">GWmodel</span>, <span class="va">tmap</span>, </span>
<span>               <span class="va">tidyverse</span>, <span class="va">gtsummary</span>,</span>
<span>               <span class="va">performance</span>, <span class="va">RColorBrewer</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="geospatial-data-wrangling" class="level2" data-number="5"><h2 data-number="5" class="anchored" data-anchor-id="geospatial-data-wrangling">
<span class="header-section-number">5</span> Geospatial Data Wrangling</h2>
<section id="importing-geospatial-data" class="level3" data-number="5.1"><h3 data-number="5.1" class="anchored" data-anchor-id="importing-geospatial-data">
<span class="header-section-number">5.1</span> Importing geospatial data</h3>
<p>The geospatial data used in this hands-on exercise is called MP14_SUBZONE_WEB_PL. It is in ESRI shapefile format. The shapefile consists of URA Master Plan 2014’s planning subzone boundaries. Polygon features are used to represent these geographic boundaries. The GIS data is in svy21 projected coordinates systems.</p>
<p>The code chunk below is used to import MP_SUBZONE_WEB_PL shapefile by using st_read() of sf packages.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mpsz</span> <span class="op">=</span> <span class="fu">st_read</span><span class="op">(</span>dsn <span class="op">=</span> <span class="st">"data/geospatial"</span>, </span>
<span>               layer <span class="op">=</span> <span class="st">"MP14_SUBZONE_WEB_PL"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MP14_SUBZONE_WEB_PL' from data source 
  `D:\ssinha8752\ISSS608-VAA\In-class_Ex\In-class_Ex07\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 323 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21</code></pre>
</div>
</div>
<p>The report above shows that the R object used to contain the imported MP14_SUBZONE_WEB_PL shapefile is called mpsz and it is a simple feature object. The geometry type is multipolygon. it is also important to note that mpsz simple feature object does not have EPSG information.</p>
</section><section id="updating-crs-information" class="level3" data-number="5.2"><h3 data-number="5.2" class="anchored" data-anchor-id="updating-crs-information">
<span class="header-section-number">5.2</span> Updating CRS information</h3>
<p>The code chunk below updates the newly imported mpsz with the correct ESPG code (i.e.&nbsp;3414)</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mpsz_svy21</span> <span class="op">&lt;-</span> <span class="fu">st_transform</span><span class="op">(</span><span class="va">mpsz</span>, <span class="fl">3414</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After transforming the projection metadata, you can varify the projection of the newly transformed mpsz_svy21 by using st_crs() of sf package.</p>
<p>The code chunk below will be used to verify the newly transformed mpsz_svy21.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">st_crs</span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:3414 
  wkt:
PROJCRS["SVY21 / Singapore TM",
    BASEGEOGCRS["SVY21",
        DATUM["SVY21",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4757]],
    CONVERSION["Singapore Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (N)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre, engineering survey, topographic mapping."],
        AREA["Singapore - onshore and offshore."],
        BBOX[1.13,103.59,1.47,104.07]],
    ID["EPSG",3414]]</code></pre>
</div>
</div>
<p>Notice that the EPSG: is indicated as 3414 now.</p>
<p>Next, we will reveal the extent of mpsz_svy21 by using st_bbox() of sf package.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">st_bbox</span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     xmin      ymin      xmax      ymax 
 2667.538 15748.721 56396.440 50256.334 </code></pre>
</div>
</div>
</section></section><section id="aspatial-data-wrangling" class="level2" data-number="6"><h2 data-number="6" class="anchored" data-anchor-id="aspatial-data-wrangling">
<span class="header-section-number">6</span> Aspatial Data Wrangling</h2>
<section id="importing-the-aspatial-data" class="level3" data-number="6.1"><h3 data-number="6.1" class="anchored" data-anchor-id="importing-the-aspatial-data">
<span class="header-section-number">6.1</span> Importing the aspatial data</h3>
<p>The condo_resale_2015 is in csv file format. The codes chunk below uses read_csv() function of readr package to import condo_resale_2015 into R as a tibble data frame called condo_resale.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale</span> <span class="op">=</span> <span class="fu">read_csv</span><span class="op">(</span></span>
<span>  <span class="st">"data/aspatial/Condo_resale_2015.csv"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After importing the data file into R, it is important for us to examine if the data file has been imported correctly.</p>
<p>The codes chunks below uses glimpse() to display the data structure of will do the job.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">glimpse</span><span class="op">(</span><span class="va">condo_resale</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,436
Columns: 23
$ LATITUDE             &lt;dbl&gt; 1.287145, 1.328698, 1.313727, 1.308563, 1.321437,…
$ LONGITUDE            &lt;dbl&gt; 103.7802, 103.8123, 103.7971, 103.8247, 103.9505,…
$ POSTCODE             &lt;dbl&gt; 118635, 288420, 267833, 258380, 467169, 466472, 3…
$ SELLING_PRICE        &lt;dbl&gt; 3000000, 3880000, 3325000, 4250000, 1400000, 1320…
$ AREA_SQM             &lt;dbl&gt; 309, 290, 248, 127, 145, 139, 218, 141, 165, 168,…
$ AGE                  &lt;dbl&gt; 30, 32, 33, 7, 28, 22, 24, 24, 27, 31, 17, 22, 6,…
$ PROX_CBD             &lt;dbl&gt; 7.941259, 6.609797, 6.898000, 4.038861, 11.783402…
$ PROX_CHILDCARE       &lt;dbl&gt; 0.16597932, 0.28027246, 0.42922669, 0.39473543, 0…
$ PROX_ELDERLYCARE     &lt;dbl&gt; 2.5198118, 1.9333338, 0.5021395, 1.9910316, 1.121…
$ PROX_URA_GROWTH_AREA &lt;dbl&gt; 6.618741, 7.505109, 6.463887, 4.906512, 6.410632,…
$ PROX_HAWKER_MARKET   &lt;dbl&gt; 1.76542207, 0.54507614, 0.37789301, 1.68259969, 0…
$ PROX_KINDERGARTEN    &lt;dbl&gt; 0.05835552, 0.61592412, 0.14120309, 0.38200076, 0…
$ PROX_MRT             &lt;dbl&gt; 0.5607188, 0.6584461, 0.3053433, 0.6910183, 0.528…
$ PROX_PARK            &lt;dbl&gt; 1.1710446, 0.1992269, 0.2779886, 0.9832843, 0.116…
$ PROX_PRIMARY_SCH     &lt;dbl&gt; 1.6340256, 0.9747834, 1.4715016, 1.4546324, 0.709…
$ PROX_TOP_PRIMARY_SCH &lt;dbl&gt; 3.3273195, 0.9747834, 1.4715016, 2.3006394, 0.709…
$ PROX_SHOPPING_MALL   &lt;dbl&gt; 2.2102717, 2.9374279, 1.2256850, 0.3525671, 1.307…
$ PROX_SUPERMARKET     &lt;dbl&gt; 0.9103958, 0.5900617, 0.4135583, 0.4162219, 0.581…
$ PROX_BUS_STOP        &lt;dbl&gt; 0.10336166, 0.28673408, 0.28504777, 0.29872340, 0…
$ NO_Of_UNITS          &lt;dbl&gt; 18, 20, 27, 30, 30, 31, 32, 32, 32, 32, 34, 34, 3…
$ FAMILY_FRIENDLY      &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0…
$ FREEHOLD             &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1…
$ LEASEHOLD_99YR       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">condo_resale</span><span class="op">$</span><span class="va">LONGITUDE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 103.7802 103.8123 103.7971 103.8247 103.9505 103.9386</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">condo_resale</span><span class="op">$</span><span class="va">LATITUDE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.287145 1.328698 1.313727 1.308563 1.321437 1.314198</code></pre>
</div>
</div>
<p>The print above reveals that the values of LONGITITUDE and LATITUDE fields are in decimal degree. Most probably wgs84 geographic coordinate system is used.</p>
<p>Next, summary() of base R is used to display the summary statistics of cond_resale tibble data frame.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">condo_resale</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    LATITUDE       LONGITUDE        POSTCODE      SELLING_PRICE     
 Min.   :1.240   Min.   :103.7   Min.   : 18965   Min.   :  540000  
 1st Qu.:1.309   1st Qu.:103.8   1st Qu.:259849   1st Qu.: 1100000  
 Median :1.328   Median :103.8   Median :469298   Median : 1383222  
 Mean   :1.334   Mean   :103.8   Mean   :440439   Mean   : 1751211  
 3rd Qu.:1.357   3rd Qu.:103.9   3rd Qu.:589486   3rd Qu.: 1950000  
 Max.   :1.454   Max.   :104.0   Max.   :828833   Max.   :18000000  
    AREA_SQM          AGE           PROX_CBD       PROX_CHILDCARE    
 Min.   : 34.0   Min.   : 0.00   Min.   : 0.3869   Min.   :0.004927  
 1st Qu.:103.0   1st Qu.: 5.00   1st Qu.: 5.5574   1st Qu.:0.174481  
 Median :121.0   Median :11.00   Median : 9.3567   Median :0.258135  
 Mean   :136.5   Mean   :12.14   Mean   : 9.3254   Mean   :0.326313  
 3rd Qu.:156.0   3rd Qu.:18.00   3rd Qu.:12.6661   3rd Qu.:0.368293  
 Max.   :619.0   Max.   :37.00   Max.   :19.1804   Max.   :3.465726  
 PROX_ELDERLYCARE  PROX_URA_GROWTH_AREA PROX_HAWKER_MARKET PROX_KINDERGARTEN 
 Min.   :0.05451   Min.   :0.2145       Min.   :0.05182    Min.   :0.004927  
 1st Qu.:0.61254   1st Qu.:3.1643       1st Qu.:0.55245    1st Qu.:0.276345  
 Median :0.94179   Median :4.6186       Median :0.90842    Median :0.413385  
 Mean   :1.05352   Mean   :4.5981       Mean   :1.27987    Mean   :0.458903  
 3rd Qu.:1.35122   3rd Qu.:5.7550       3rd Qu.:1.68578    3rd Qu.:0.578474  
 Max.   :3.94916   Max.   :9.1554       Max.   :5.37435    Max.   :2.229045  
    PROX_MRT         PROX_PARK       PROX_PRIMARY_SCH  PROX_TOP_PRIMARY_SCH
 Min.   :0.05278   Min.   :0.02906   Min.   :0.07711   Min.   :0.07711     
 1st Qu.:0.34646   1st Qu.:0.26211   1st Qu.:0.44024   1st Qu.:1.34451     
 Median :0.57430   Median :0.39926   Median :0.63505   Median :1.88213     
 Mean   :0.67316   Mean   :0.49802   Mean   :0.75471   Mean   :2.27347     
 3rd Qu.:0.84844   3rd Qu.:0.65592   3rd Qu.:0.95104   3rd Qu.:2.90954     
 Max.   :3.48037   Max.   :2.16105   Max.   :3.92899   Max.   :6.74819     
 PROX_SHOPPING_MALL PROX_SUPERMARKET PROX_BUS_STOP       NO_Of_UNITS    
 Min.   :0.0000     Min.   :0.0000   Min.   :0.001595   Min.   :  18.0  
 1st Qu.:0.5258     1st Qu.:0.3695   1st Qu.:0.098356   1st Qu.: 188.8  
 Median :0.9357     Median :0.5687   Median :0.151711   Median : 360.0  
 Mean   :1.0455     Mean   :0.6141   Mean   :0.193974   Mean   : 409.2  
 3rd Qu.:1.3994     3rd Qu.:0.7862   3rd Qu.:0.220466   3rd Qu.: 590.0  
 Max.   :3.4774     Max.   :2.2441   Max.   :2.476639   Max.   :1703.0  
 FAMILY_FRIENDLY     FREEHOLD      LEASEHOLD_99YR  
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :0.0000   Median :0.0000   Median :0.0000  
 Mean   :0.4868   Mean   :0.4227   Mean   :0.4882  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  </code></pre>
</div>
</div>
</section><section id="converting-aspatial-data-frame-into-a-sf-object" class="level3" data-number="6.2"><h3 data-number="6.2" class="anchored" data-anchor-id="converting-aspatial-data-frame-into-a-sf-object">
<span class="header-section-number">6.2</span> Converting aspatial data frame into a sf object</h3>
<p>Currently, the condo_resale tibble data frame is aspatial. We will convert it to a sf object. The code chunk below converts condo_resale data frame into a simple feature data frame by using st_as_sf() of sf packages.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale.sf</span> <span class="op">&lt;-</span> <span class="fu">st_as_sf</span><span class="op">(</span><span class="va">condo_resale</span>,</span>
<span>                            coords <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"LONGITUDE"</span>, <span class="st">"LATITUDE"</span><span class="op">)</span>,</span>
<span>                            crs<span class="op">=</span><span class="fl">4326</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">st_transform</span><span class="op">(</span>crs<span class="op">=</span><span class="fl">3414</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, head() is used to list the content of condo_resale.sf object.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">condo_resale.sf</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 21 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 22085.12 ymin: 29951.54 xmax: 41042.56 ymax: 34546.2
Projected CRS: SVY21 / Singapore TM
# A tibble: 6 × 22
  POSTCODE SELLING_PRICE AREA_SQM   AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE
     &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;          &lt;dbl&gt;            &lt;dbl&gt;
1   118635       3000000      309    30     7.94          0.166            2.52 
2   288420       3880000      290    32     6.61          0.280            1.93 
3   267833       3325000      248    33     6.90          0.429            0.502
4   258380       4250000      127     7     4.04          0.395            1.99 
5   467169       1400000      145    28    11.8           0.119            1.12 
6   466472       1320000      139    22    10.3           0.125            0.789
# ℹ 15 more variables: PROX_URA_GROWTH_AREA &lt;dbl&gt;, PROX_HAWKER_MARKET &lt;dbl&gt;,
#   PROX_KINDERGARTEN &lt;dbl&gt;, PROX_MRT &lt;dbl&gt;, PROX_PARK &lt;dbl&gt;,
#   PROX_PRIMARY_SCH &lt;dbl&gt;, PROX_TOP_PRIMARY_SCH &lt;dbl&gt;,
#   PROX_SHOPPING_MALL &lt;dbl&gt;, PROX_SUPERMARKET &lt;dbl&gt;, PROX_BUS_STOP &lt;dbl&gt;,
#   NO_Of_UNITS &lt;dbl&gt;, FAMILY_FRIENDLY &lt;dbl&gt;, FREEHOLD &lt;dbl&gt;,
#   LEASEHOLD_99YR &lt;dbl&gt;, geometry &lt;POINT [m]&gt;</code></pre>
</div>
</div>
<p>Notice that the output is in point feature data frame.</p>
</section></section><section id="exploratory-data-analysis-eda" class="level2" data-number="7"><h2 data-number="7" class="anchored" data-anchor-id="exploratory-data-analysis-eda">
<span class="header-section-number">7</span> Exploratory Data Analysis (EDA)</h2>
<p>In the section, we will learn how to use statistical graphics functions of ggplot2 package to perform EDA.</p>
<section id="eda-using-statistical-graphics" class="level3" data-number="7.1"><h3 data-number="7.1" class="anchored" data-anchor-id="eda-using-statistical-graphics">
<span class="header-section-number">7.1</span> EDA using statistical graphics</h3>
<p>We can plot the distribution of SELLING_PRICE by using appropriate Exploratory Data Analysis (EDA) as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>       <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">`SELLING_PRICE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure above reveals a right skewed distribution. This means that more condominium units were transacted at relative lower prices.</p>
<p>Statistically, the skewed dsitribution can be normalised by using log transformation. The code chunk below is used to derive a new variable called LOG_SELLING_PRICE by using a log transformation on the variable SELLING_PRICE. It is performed using mutate() of dplyr package.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale.sf</span> <span class="op">&lt;-</span> <span class="va">condo_resale.sf</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>`LOG_SELLING_PRICE` <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">SELLING_PRICE</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we can plot the LOG_SELLING_PRICE using the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>       <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">`LOG_SELLING_PRICE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notice that the distribution is relatively less skewed after the transformation.</p>
</section><section id="multiple-histogram-plots-distribution-of-variables" class="level3" data-number="7.2"><h3 data-number="7.2" class="anchored" data-anchor-id="multiple-histogram-plots-distribution-of-variables">
<span class="header-section-number">7.2</span> Multiple Histogram Plots distribution of variables</h3>
<p>In this section, we will learn how to draw a small multiple histograms (also known as trellis plot) by using ggarrange() of ggpubr package.</p>
<p>The code chunk below is used to create 12 histograms. Then, ggarrange() is used to organised these histogram into a 3 columns by 4 rows small multiple plot.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">AREA_SQM</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                   <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`AREA_SQM`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">AGE</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>              <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`AGE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PROX_CBD</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                   <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_CBD`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PROX_CHILDCARE</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                         <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_CHILDCARE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PROX_ELDERLYCARE</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                           <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_ELDERLYCARE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                               <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_URA_GROWTH_AREA`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PROX_HAWKER_MARKET</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                             <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_HAWKER_MARKET`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PROX_KINDERGARTEN</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                            <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_KINDERGARTEN`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PROX_MRT</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                   <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_MRT`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PROX_PARK</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                    <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_PARK`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PROX_PRIMARY_SCH</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                           <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_PRIMARY_SCH`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PROX_TOP_PRIMARY_SCH</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>                               <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">`PROX_TOP_PRIMARY_SCH`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins<span class="op">=</span><span class="fl">20</span>, </span>
<span>                 color<span class="op">=</span><span class="st">"black"</span>, </span>
<span>                 fill<span class="op">=</span><span class="st">"light blue"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggarrange</span><span class="op">(</span><span class="va">AREA_SQM</span>, <span class="va">AGE</span>, <span class="va">PROX_CBD</span>, <span class="va">PROX_CHILDCARE</span>, </span>
<span>          <span class="va">PROX_ELDERLYCARE</span>, <span class="va">PROX_URA_GROWTH_AREA</span>,</span>
<span>          <span class="va">PROX_HAWKER_MARKET</span>, <span class="va">PROX_KINDERGARTEN</span>, <span class="va">PROX_MRT</span>,</span>
<span>          <span class="va">PROX_PARK</span>, <span class="va">PROX_PRIMARY_SCH</span>, <span class="va">PROX_TOP_PRIMARY_SCH</span>,  </span>
<span>          ncol <span class="op">=</span> <span class="fl">3</span>, nrow <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="hedonic-pricing-modelling-in-r" class="level2" data-number="8"><h2 data-number="8" class="anchored" data-anchor-id="hedonic-pricing-modelling-in-r">
<span class="header-section-number">8</span> Hedonic Pricing Modelling in R</h2>
<p>In this section, we will learn how to building hedonic pricing models for condominium resale units using lm() of R base.</p>
<section id="simple-linear-regression-method" class="level3" data-number="8.1"><h3 data-number="8.1" class="anchored" data-anchor-id="simple-linear-regression-method">
<span class="header-section-number">8.1</span> Simple Linear Regression Method</h3>
<p>First, we will build a simple linear regression model by using SELLING_PRICE as the dependent variable and AREA_SQM as the independent variable.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo.slr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula<span class="op">=</span><span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span>, </span>
<span>                data <span class="op">=</span> <span class="va">condo_resale.sf</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>lm() returns an object of class “lm” or for multiple responses of class c(“mlm”, “lm”).</p>
<p>The functions summary() and anova() can be used to obtain and print a summary and analysis of variance table of the results. The generic accessor functions coefficients, effects, fitted.values and residuals extract various useful features of the value returned by lm.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">condo.slr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)

Residuals:
     Min       1Q   Median       3Q      Max 
-3695815  -391764   -87517   258900 13503875 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -258121.1    63517.2  -4.064 5.09e-05 ***
AREA_SQM      14719.0      428.1  34.381  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 942700 on 1434 degrees of freedom
Multiple R-squared:  0.4518,    Adjusted R-squared:  0.4515 
F-statistic:  1182 on 1 and 1434 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The output report reveals that the SELLING_PRICE can be explained by using the formula:</p>
<pre><code>  y = -258121.1 + 14719x1</code></pre>
<p>The R-squared of 0.4518 reveals that the simple regression model built is able to explain about 45% of the resale prices.</p>
<p>Since p-value is much smaller than 0.0001, we will reject the null hypothesis that mean is a good estimator of SELLING_PRICE. This will allow us to infer that simple linear regression model above is a good estimator of SELLING_PRICE.</p>
<p>The Coefficients: section of the report reveals that the p-values of both the estimates of the Intercept and ARA_SQM are smaller than 0.001. In view of this, the null hypothesis of the B0 and B1 are equal to 0 will be rejected. As a results, we will be able to infer that the B0 and B1 are good parameter estimates.</p>
<p>To visualise the best fit curve on a scatterplot, we can incorporate lm() as a method function in ggplot’s geometry as shown in the code chunk below</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">condo_resale.sf</span>,  </span>
<span>       <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">`AREA_SQM`</span>, y<span class="op">=</span><span class="va">`SELLING_PRICE`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="va">lm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure above reveals that there are a few statistical outliers with relatively high selling prices.</p>
</section><section id="multiple-linear-regression-method" class="level3" data-number="8.2"><h3 data-number="8.2" class="anchored" data-anchor-id="multiple-linear-regression-method">
<span class="header-section-number">8.2</span> Multiple Linear Regression Method</h3>
<section id="visualising-the-relationships-of-the-independent-variables" class="level4" data-number="8.2.1"><h4 data-number="8.2.1" class="anchored" data-anchor-id="visualising-the-relationships-of-the-independent-variables">
<span class="header-section-number">8.2.1</span> Visualising the relationships of the independent variables</h4>
<p>Before building a multiple regression model, it is important to ensure that the indepdent variables used are not highly correlated to each other. If these highly correlated independent variables are used in building a regression model by mistake, the quality of the model will be compromised. This phenomenon is known as multicollinearity in statistics.</p>
<p>Correlation matrix is commonly used to visualise the relationships between the independent variables. Beside the pairs() of R, there are many packages support the display of a correlation matrix. In this section, the corrplot package will be used.</p>
<p>The code chunk below is used to plot a scatterplot matrix of the relationship between the independent variables in condo_resale data.frame.</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">corrplot</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">condo_resale</span><span class="op">[</span>, <span class="fl">5</span><span class="op">:</span><span class="fl">23</span><span class="op">]</span><span class="op">)</span>, </span>
<span>         diag <span class="op">=</span> <span class="cn">FALSE</span>, </span>
<span>         order <span class="op">=</span> <span class="st">"AOE"</span>,</span>
<span>         tl.pos <span class="op">=</span> <span class="st">"td"</span>, </span>
<span>         tl.cex <span class="op">=</span> <span class="fl">0.5</span>, </span>
<span>         method <span class="op">=</span> <span class="st">"number"</span>, </span>
<span>         type <span class="op">=</span> <span class="st">"upper"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Matrix reorder is very important for mining the hiden structure and patter in the matrix. There are four methods in corrplot (parameter order), named “AOE”, “FPC”, “hclust”, “alphabet”. In the code chunk above, AOE order is used. It orders the variables by using the angular order of the eigenvectors method suggested by Michael Friendly.</p>
<p>From the scatterplot matrix, it is clear that Freehold is highly correlated to LEASE_99YEAR. In view of this, it is wiser to only include either one of them in the subsequent model building. As a result, LEASE_99YEAR is excluded in the subsequent model building.</p>
</section></section><section id="building-a-hedonic-pricing-model-using-multiple-linear-regression-method" class="level3" data-number="8.3"><h3 data-number="8.3" class="anchored" data-anchor-id="building-a-hedonic-pricing-model-using-multiple-linear-regression-method">
<span class="header-section-number">8.3</span> Building a hedonic pricing model using multiple linear regression method</h3>
<p>The code chunk below using lm() to calibrate the multiple linear regression model.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo.mlr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span>  <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_ELDERLYCARE</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span> <span class="va">PROX_HAWKER_MARKET</span>   <span class="op">+</span></span>
<span>    <span class="va">PROX_KINDERGARTEN</span>   <span class="op">+</span> <span class="va">PROX_MRT</span>  <span class="op">+</span> <span class="va">PROX_PARK</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> <span class="va">PROX_TOP_PRIMARY_SCH</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_SHOPPING_MALL</span>  <span class="op">+</span> <span class="va">PROX_SUPERMARKET</span> <span class="op">+</span> </span>
<span>    <span class="va">PROX_BUS_STOP</span>   <span class="op">+</span> <span class="va">NO_Of_UNITS</span> <span class="op">+</span> </span>
<span>    <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> <span class="va">FREEHOLD</span>, </span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">condo.mlr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + 
    PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET + 
    PROX_KINDERGARTEN + PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + 
    PROX_TOP_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_SUPERMARKET + 
    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
    data = condo_resale.sf)

Residuals:
     Min       1Q   Median       3Q      Max 
-3475964  -293923   -23069   241043 12260381 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           481728.40  121441.01   3.967 7.65e-05 ***
AREA_SQM               12708.32     369.59  34.385  &lt; 2e-16 ***
AGE                   -24440.82    2763.16  -8.845  &lt; 2e-16 ***
PROX_CBD              -78669.78    6768.97 -11.622  &lt; 2e-16 ***
PROX_CHILDCARE       -351617.91  109467.25  -3.212  0.00135 ** 
PROX_ELDERLYCARE      171029.42   42110.51   4.061 5.14e-05 ***
PROX_URA_GROWTH_AREA   38474.53   12523.57   3.072  0.00217 ** 
PROX_HAWKER_MARKET     23746.10   29299.76   0.810  0.41782    
PROX_KINDERGARTEN     147468.99   82668.87   1.784  0.07466 .  
PROX_MRT             -314599.68   57947.44  -5.429 6.66e-08 ***
PROX_PARK             563280.50   66551.68   8.464  &lt; 2e-16 ***
PROX_PRIMARY_SCH      180186.08   65237.95   2.762  0.00582 ** 
PROX_TOP_PRIMARY_SCH    2280.04   20410.43   0.112  0.91107    
PROX_SHOPPING_MALL   -206604.06   42840.60  -4.823 1.57e-06 ***
PROX_SUPERMARKET      -44991.80   77082.64  -0.584  0.55953    
PROX_BUS_STOP         683121.35  138353.28   4.938 8.85e-07 ***
NO_Of_UNITS             -231.18      89.03  -2.597  0.00951 ** 
FAMILY_FRIENDLY       140340.77   47020.55   2.985  0.00289 ** 
FREEHOLD              359913.01   49220.22   7.312 4.38e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 755800 on 1417 degrees of freedom
Multiple R-squared:  0.6518,    Adjusted R-squared:  0.6474 
F-statistic: 147.4 on 18 and 1417 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section><section id="revising-the-model" class="level3" data-number="8.4"><h3 data-number="8.4" class="anchored" data-anchor-id="revising-the-model">
<span class="header-section-number">8.4</span> Revising the model</h3>
<p>With reference to the report above, it is clear that not all the independent variables are statistically significant. We will revised the model by removing those variables which are not statistically significant.</p>
<p>Now, we are ready to calibrate the revised model by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo.mlr1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span> <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_MRT</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_ELDERLYCARE</span>    <span class="op">+</span> <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_PARK</span>   <span class="op">+</span> <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> </span>
<span>    <span class="va">PROX_SHOPPING_MALL</span>  <span class="op">+</span> <span class="va">PROX_BUS_STOP</span> <span class="op">+</span> </span>
<span>    <span class="va">NO_Of_UNITS</span> <span class="op">+</span> <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> <span class="va">FREEHOLD</span>,</span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + 
    PROX_MRT + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + PROX_PARK + 
    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_BUS_STOP + NO_Of_UNITS + 
    FAMILY_FRIENDLY + FREEHOLD, data = condo_resale.sf)

Residuals:
     Min       1Q   Median       3Q      Max 
-3470778  -298119   -23481   248917 12234210 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           527633.22  108183.22   4.877 1.20e-06 ***
AREA_SQM               12777.52     367.48  34.771  &lt; 2e-16 ***
AGE                   -24687.74    2754.84  -8.962  &lt; 2e-16 ***
PROX_CBD              -77131.32    5763.12 -13.384  &lt; 2e-16 ***
PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** 
PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***
PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***
PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***
PROX_PARK             570504.81   65507.03   8.709  &lt; 2e-16 ***
PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** 
PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***
PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***
NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** 
FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** 
FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 756000 on 1421 degrees of freedom
Multiple R-squared:  0.6507,    Adjusted R-squared:  0.6472 
F-statistic: 189.1 on 14 and 1421 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The output above reveals that all explanatory variables are statistically significant at 95% confident level.</p>
</section><section id="preparing-publication-quality-table-gtsummary-method" class="level3" data-number="8.5"><h3 data-number="8.5" class="anchored" data-anchor-id="preparing-publication-quality-table-gtsummary-method">
<span class="header-section-number">8.5</span> Preparing Publication Quality Table: gtsummary method</h3>
<p>The gtsummary package provides an elegant and flexible way to create publication-ready summary tables in R.</p>
<p>In the code chunk below, tbl_regression() is used to create a well formatted regression report.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tbl_regression</span><span class="op">(</span><span class="va">condo.mlr1</span>, intercept <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="mbgbxpntpw" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#mbgbxpntpw table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#mbgbxpntpw thead, #mbgbxpntpw tbody, #mbgbxpntpw tfoot, #mbgbxpntpw tr, #mbgbxpntpw td, #mbgbxpntpw th {
  border-style: none;
}

#mbgbxpntpw p {
  margin: 0;
  padding: 0;
}

#mbgbxpntpw .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#mbgbxpntpw .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#mbgbxpntpw .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#mbgbxpntpw .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#mbgbxpntpw .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mbgbxpntpw .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mbgbxpntpw .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mbgbxpntpw .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#mbgbxpntpw .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#mbgbxpntpw .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#mbgbxpntpw .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#mbgbxpntpw .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#mbgbxpntpw .gt_spanner_row {
  border-bottom-style: hidden;
}

#mbgbxpntpw .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#mbgbxpntpw .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#mbgbxpntpw .gt_from_md > :first-child {
  margin-top: 0;
}

#mbgbxpntpw .gt_from_md > :last-child {
  margin-bottom: 0;
}

#mbgbxpntpw .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#mbgbxpntpw .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#mbgbxpntpw .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#mbgbxpntpw .gt_row_group_first td {
  border-top-width: 2px;
}

#mbgbxpntpw .gt_row_group_first th {
  border-top-width: 2px;
}

#mbgbxpntpw .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mbgbxpntpw .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#mbgbxpntpw .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#mbgbxpntpw .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mbgbxpntpw .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mbgbxpntpw .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#mbgbxpntpw .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#mbgbxpntpw .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#mbgbxpntpw .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mbgbxpntpw .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mbgbxpntpw .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#mbgbxpntpw .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mbgbxpntpw .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#mbgbxpntpw .gt_left {
  text-align: left;
}

#mbgbxpntpw .gt_center {
  text-align: center;
}

#mbgbxpntpw .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#mbgbxpntpw .gt_font_normal {
  font-weight: normal;
}

#mbgbxpntpw .gt_font_bold {
  font-weight: bold;
}

#mbgbxpntpw .gt_font_italic {
  font-style: italic;
}

#mbgbxpntpw .gt_super {
  font-size: 65%;
}

#mbgbxpntpw .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#mbgbxpntpw .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#mbgbxpntpw .gt_indent_1 {
  text-indent: 5px;
}

#mbgbxpntpw .gt_indent_2 {
  text-indent: 10px;
}

#mbgbxpntpw .gt_indent_3 {
  text-indent: 15px;
}

#mbgbxpntpw .gt_indent_4 {
  text-indent: 20px;
}

#mbgbxpntpw .gt_indent_5 {
  text-indent: 25px;
}

#mbgbxpntpw .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#mbgbxpntpw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Beta</strong></th>
<th id="conf.low" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr></thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">(Intercept)</td>
<td class="gt_row gt_center" headers="estimate">527,633</td>
<td class="gt_row gt_center" headers="conf.low">315,417, 739,849</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">AREA_SQM</td>
<td class="gt_row gt_center" headers="estimate">12,778</td>
<td class="gt_row gt_center" headers="conf.low">12,057, 13,498</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">AGE</td>
<td class="gt_row gt_center" headers="estimate">-24,688</td>
<td class="gt_row gt_center" headers="conf.low">-30,092, -19,284</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_CBD</td>
<td class="gt_row gt_center" headers="estimate">-77,131</td>
<td class="gt_row gt_center" headers="conf.low">-88,436, -65,826</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_CHILDCARE</td>
<td class="gt_row gt_center" headers="estimate">-318,473</td>
<td class="gt_row gt_center" headers="conf.low">-530,250, -106,696</td>
<td class="gt_row gt_center" headers="p.value">0.003</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_MRT</td>
<td class="gt_row gt_center" headers="estimate">-294,745</td>
<td class="gt_row gt_center" headers="conf.low">-406,394, -183,096</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_ELDERLYCARE</td>
<td class="gt_row gt_center" headers="estimate">185,576</td>
<td class="gt_row gt_center" headers="conf.low">107,303, 263,849</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_URA_GROWTH_AREA</td>
<td class="gt_row gt_center" headers="estimate">39,163</td>
<td class="gt_row gt_center" headers="conf.low">16,105, 62,222</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_PARK</td>
<td class="gt_row gt_center" headers="estimate">570,505</td>
<td class="gt_row gt_center" headers="conf.low">442,004, 699,006</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_PRIMARY_SCH</td>
<td class="gt_row gt_center" headers="estimate">159,856</td>
<td class="gt_row gt_center" headers="conf.low">41,698, 278,014</td>
<td class="gt_row gt_center" headers="p.value">0.008</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_SHOPPING_MALL</td>
<td class="gt_row gt_center" headers="estimate">-220,947</td>
<td class="gt_row gt_center" headers="conf.low">-292,668, -149,226</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_BUS_STOP</td>
<td class="gt_row gt_center" headers="estimate">682,482</td>
<td class="gt_row gt_center" headers="conf.low">418,616, 946,348</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">NO_Of_UNITS</td>
<td class="gt_row gt_center" headers="estimate">-245</td>
<td class="gt_row gt_center" headers="conf.low">-418, -73</td>
<td class="gt_row gt_center" headers="p.value">0.005</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">FAMILY_FRIENDLY</td>
<td class="gt_row gt_center" headers="estimate">146,308</td>
<td class="gt_row gt_center" headers="conf.low">54,321, 238,295</td>
<td class="gt_row gt_center" headers="p.value">0.002</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">FREEHOLD</td>
<td class="gt_row gt_center" headers="estimate">350,600</td>
<td class="gt_row gt_center" headers="conf.low">255,448, 445,752</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
</tbody>
<tfoot class="gt_sourcenotes"><tr class="odd">
<td colspan="4" class="gt_sourcenote">Abbreviation: CI = Confidence Interval</td>
</tr></tfoot>
</table>
</div>
</div>
</div>
<p>With gtsummary package, model statistics can be included in the report by either appending them to the report table by using add_glance_table() or adding as a table source note by using add_glance_source_note() as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tbl_regression</span><span class="op">(</span><span class="va">condo.mlr1</span>, </span>
<span>               intercept <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">add_glance_source_note</span><span class="op">(</span></span>
<span>    label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">sigma</span> <span class="op">~</span> <span class="st">"\U03C3"</span><span class="op">)</span>,</span>
<span>    include <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">r.squared</span>, <span class="va">adj.r.squared</span>, </span>
<span>                <span class="va">AIC</span>, <span class="va">statistic</span>,</span>
<span>                <span class="va">p.value</span>, <span class="va">sigma</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="ztsblmsydy" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ztsblmsydy table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ztsblmsydy thead, #ztsblmsydy tbody, #ztsblmsydy tfoot, #ztsblmsydy tr, #ztsblmsydy td, #ztsblmsydy th {
  border-style: none;
}

#ztsblmsydy p {
  margin: 0;
  padding: 0;
}

#ztsblmsydy .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ztsblmsydy .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ztsblmsydy .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ztsblmsydy .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ztsblmsydy .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ztsblmsydy .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ztsblmsydy .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ztsblmsydy .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ztsblmsydy .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ztsblmsydy .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ztsblmsydy .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ztsblmsydy .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ztsblmsydy .gt_spanner_row {
  border-bottom-style: hidden;
}

#ztsblmsydy .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ztsblmsydy .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ztsblmsydy .gt_from_md > :first-child {
  margin-top: 0;
}

#ztsblmsydy .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ztsblmsydy .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ztsblmsydy .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ztsblmsydy .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ztsblmsydy .gt_row_group_first td {
  border-top-width: 2px;
}

#ztsblmsydy .gt_row_group_first th {
  border-top-width: 2px;
}

#ztsblmsydy .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ztsblmsydy .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ztsblmsydy .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ztsblmsydy .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ztsblmsydy .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ztsblmsydy .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ztsblmsydy .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ztsblmsydy .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ztsblmsydy .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ztsblmsydy .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ztsblmsydy .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ztsblmsydy .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ztsblmsydy .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ztsblmsydy .gt_left {
  text-align: left;
}

#ztsblmsydy .gt_center {
  text-align: center;
}

#ztsblmsydy .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ztsblmsydy .gt_font_normal {
  font-weight: normal;
}

#ztsblmsydy .gt_font_bold {
  font-weight: bold;
}

#ztsblmsydy .gt_font_italic {
  font-style: italic;
}

#ztsblmsydy .gt_super {
  font-size: 65%;
}

#ztsblmsydy .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ztsblmsydy .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ztsblmsydy .gt_indent_1 {
  text-indent: 5px;
}

#ztsblmsydy .gt_indent_2 {
  text-indent: 10px;
}

#ztsblmsydy .gt_indent_3 {
  text-indent: 15px;
}

#ztsblmsydy .gt_indent_4 {
  text-indent: 20px;
}

#ztsblmsydy .gt_indent_5 {
  text-indent: 25px;
}

#ztsblmsydy .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#ztsblmsydy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead><tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Beta</strong></th>
<th id="conf.low" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr></thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">(Intercept)</td>
<td class="gt_row gt_center" headers="estimate">527,633</td>
<td class="gt_row gt_center" headers="conf.low">315,417, 739,849</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">AREA_SQM</td>
<td class="gt_row gt_center" headers="estimate">12,778</td>
<td class="gt_row gt_center" headers="conf.low">12,057, 13,498</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">AGE</td>
<td class="gt_row gt_center" headers="estimate">-24,688</td>
<td class="gt_row gt_center" headers="conf.low">-30,092, -19,284</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_CBD</td>
<td class="gt_row gt_center" headers="estimate">-77,131</td>
<td class="gt_row gt_center" headers="conf.low">-88,436, -65,826</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_CHILDCARE</td>
<td class="gt_row gt_center" headers="estimate">-318,473</td>
<td class="gt_row gt_center" headers="conf.low">-530,250, -106,696</td>
<td class="gt_row gt_center" headers="p.value">0.003</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_MRT</td>
<td class="gt_row gt_center" headers="estimate">-294,745</td>
<td class="gt_row gt_center" headers="conf.low">-406,394, -183,096</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_ELDERLYCARE</td>
<td class="gt_row gt_center" headers="estimate">185,576</td>
<td class="gt_row gt_center" headers="conf.low">107,303, 263,849</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_URA_GROWTH_AREA</td>
<td class="gt_row gt_center" headers="estimate">39,163</td>
<td class="gt_row gt_center" headers="conf.low">16,105, 62,222</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_PARK</td>
<td class="gt_row gt_center" headers="estimate">570,505</td>
<td class="gt_row gt_center" headers="conf.low">442,004, 699,006</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_PRIMARY_SCH</td>
<td class="gt_row gt_center" headers="estimate">159,856</td>
<td class="gt_row gt_center" headers="conf.low">41,698, 278,014</td>
<td class="gt_row gt_center" headers="p.value">0.008</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_SHOPPING_MALL</td>
<td class="gt_row gt_center" headers="estimate">-220,947</td>
<td class="gt_row gt_center" headers="conf.low">-292,668, -149,226</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_BUS_STOP</td>
<td class="gt_row gt_center" headers="estimate">682,482</td>
<td class="gt_row gt_center" headers="conf.low">418,616, 946,348</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">NO_Of_UNITS</td>
<td class="gt_row gt_center" headers="estimate">-245</td>
<td class="gt_row gt_center" headers="conf.low">-418, -73</td>
<td class="gt_row gt_center" headers="p.value">0.005</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">FAMILY_FRIENDLY</td>
<td class="gt_row gt_center" headers="estimate">146,308</td>
<td class="gt_row gt_center" headers="conf.low">54,321, 238,295</td>
<td class="gt_row gt_center" headers="p.value">0.002</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">FREEHOLD</td>
<td class="gt_row gt_center" headers="estimate">350,600</td>
<td class="gt_row gt_center" headers="conf.low">255,448, 445,752</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
</tbody>
<tfoot class="gt_sourcenotes">
<tr class="odd">
<td colspan="4" class="gt_sourcenote">Abbreviation: CI = Confidence Interval</td>
</tr>
<tr class="even">
<td colspan="4" class="gt_sourcenote">R² = 0.651; Adjusted R² = 0.647; AIC = 42,967; Statistic = 189; p-value = &lt;0.001; σ = 755,957</td>
</tr>
</tfoot>
</table>
</div>
</div>
</div>
</section><section id="regression-diagnostics" class="level3" data-number="8.6"><h3 data-number="8.6" class="anchored" data-anchor-id="regression-diagnostics">
<span class="header-section-number">8.6</span> Regression Diagnostics</h3>
<p>Regression diagnostics are a set of procedures used to check if a regression model’s assumptions are met and how well the model fits the data. These diagnostics involve checking for issues like non-linear relationships, non-normal errors, non-constant variance, and influential observations to ensure the model’s conclusions are valid and reliable. Common methods include graphical analysis, like residual plots and QQ-plots, and quantitative tests</p>
<p>In this section, we would like to introduce you a fantastic R package specially programmed for performing OLS regression diagnostics. It is called olsrr. It provides a collection of very useful methods for building better multiple linear regression models:</p>
<ul>
<li>comprehensive regression output</li>
<li>residual diagnostics</li>
<li>measures of influence</li>
<li>heteroskedasticity tests</li>
<li>collinearity diagnostics</li>
<li>model fit assessment</li>
<li>variable contribution assessment</li>
<li>variable selection procedures</li>
</ul>
<section id="multicollinearity-test" class="level4" data-number="8.6.1"><h4 data-number="8.6.1" class="anchored" data-anchor-id="multicollinearity-test">
<span class="header-section-number">8.6.1</span> Multicollinearity test</h4>
<p>Multicollinearity occurs when independent variables are not truly independent, meaning a change in one is associated with a change in another. This makes it hard for the model to isolate each variable’s influence on the outcome.</p>
<p>Performing a multicollinearity test is crucial in multiple linear regression because it ensures the reliability and interpretability of the model’s results. High multicollinearity, where independent variables are highly correlated, inflates the variance of the estimated coefficients, making them unstable, unreliable, and difficult to interpret. This instability can lead to misleading statistical conclusions, such as a variable appearing statistically insignificant when it is not.</p>
<p>In the code chunk below, the check_collinearity() of performance package is used to test if there are sign of multicollinearity.</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_collinearity</span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for Multicollinearity

Low Correlation

                 Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI
             AREA_SQM 1.15 [1.09, 1.23]     1.07      0.87     [0.81, 0.92]
                  AGE 1.41 [1.33, 1.52]     1.19      0.71     [0.66, 0.75]
             PROX_CBD 1.57 [1.47, 1.69]     1.25      0.64     [0.59, 0.68]
       PROX_CHILDCARE 3.26 [3.00, 3.56]     1.81      0.31     [0.28, 0.33]
             PROX_MRT 1.91 [1.78, 2.07]     1.38      0.52     [0.48, 0.56]
     PROX_ELDERLYCARE 1.52 [1.42, 1.63]     1.23      0.66     [0.61, 0.70]
 PROX_URA_GROWTH_AREA 1.33 [1.26, 1.43]     1.15      0.75     [0.70, 0.80]
            PROX_PARK 1.21 [1.15, 1.29]     1.10      0.83     [0.77, 0.87]
     PROX_PRIMARY_SCH 2.21 [2.05, 2.40]     1.49      0.45     [0.42, 0.49]
   PROX_SHOPPING_MALL 1.48 [1.39, 1.60]     1.22      0.67     [0.63, 0.72]
        PROX_BUS_STOP 2.85 [2.62, 3.10]     1.69      0.35     [0.32, 0.38]
          NO_Of_UNITS 1.45 [1.36, 1.56]     1.20      0.69     [0.64, 0.73]
      FAMILY_FRIENDLY 1.38 [1.30, 1.48]     1.17      0.72     [0.67, 0.77]
             FREEHOLD 1.44 [1.36, 1.55]     1.20      0.69     [0.65, 0.74]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mlr.vif</span> <span class="op">&lt;-</span> <span class="fu">check_collinearity</span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mlr.vif</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Since the VIF of the independent variables are less than 10. We can safely conclude that there are no sign of multicollinearity among the independent variables.</p>
</section><section id="test-for-non-linearity" class="level4" data-number="8.6.2"><h4 data-number="8.6.2" class="anchored" data-anchor-id="test-for-non-linearity">
<span class="header-section-number">8.6.2</span> Test for Non-Linearity</h4>
<p>In multiple linear regression, it is important for us to test the assumption that linearity and additivity of the relationship between dependent and independent variables.</p>
<p>In the code chunk below, the ols_plot_resid_fit() of olsrr package is used to perform linearity assumption test.</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_model</span><span class="op">(</span><span class="va">condo.mlr1</span>,</span>
<span>            check <span class="op">=</span> <span class="st">"linearity"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure above reveals that most of the data poitns are scattered around the 0 line, hence we can safely conclude that the relationships between the dependent variable and independent variables are linear. #### Test for Normality Assumption The normality assumption test for multiple linear regression checks if the model’s residuals (the differences between observed and predicted values) are normally distributed. This is crucial for accurate hypothesis testing and confidence intervals. To test this, you can use visual methods like histograms and Q-Q plots of the residuals, or conduct statistical tests like Shapiro-Wilk test and Kolmogorov-Smirnov test.</p>
<p>In the code chunk below, check_normality() of performance package is used to perform normality assumption test on condo.mlr1 model.</p>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_normality</span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p &lt; .001).</code></pre>
</div>
</div>
<p>The print above reveals that the p-value of the normality assumption test is less than alpha value of 0.05. Hence we reject the normality assumption at 95% confident level.</p>
<p>Instead of showing the test statistic, plot() of see package can be used to plot a the output of check_normality() for visual inspection as shown below.</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">check_normality</span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">)</span>, </span>
<span>     type <span class="op">=</span> <span class="st">"qq"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Q-Q plot above below shows that majority of the data points are felt along the zero line.</p>
<p>Another way to check for normality assumption visual is by using check_model() of performance package as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">check_model</span><span class="op">(</span><span class="va">condo.mlr1</span>,</span>
<span>            check<span class="op">=</span> <span class="st">"normality"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure reveals that the residual of the multiple linear regression model (i.e.&nbsp;condo.mlr1) is resemble normal distribution.</p>
</section><section id="testing-for-spatial-autocorrelation" class="level4" data-number="8.6.3"><h4 data-number="8.6.3" class="anchored" data-anchor-id="testing-for-spatial-autocorrelation">
<span class="header-section-number">8.6.3</span> Testing for Spatial Autocorrelation</h4>
<p>The hedonic model we try to build are using geographically referenced data. Hence, it is crucial to check for spatial autocorrelation because its presence can produce unreliable and misleading results. Traditional regression models, such as ordinary least squares (OLS), assume that observations are independent of one another. However, spatial data often violates this assumption.</p>
<p>Spatial autocorrelation is the correlation of a variable with itself across different spatial locations. Positive spatial autocorrelation means nearby features tend to be more similar, while negative autocorrelation means they tend to be more dissimilar. This phenomenon is based on the first law of geography: “Everything is related to everything else, but nearby things are more related than distant things”.</p>
<p>Ignoring spatial autocorrelation in a regression model can lead to serious statistical issues:</p>
<ul>
<li>Biased and inefficient coefficient estimates: If autocorrelation is present, standard errors of the model coefficients can be wrong, leading to unreliable hypothesis tests (p-values). The model might appear more significant than it is.</li>
<li>Misleading significance tests: Standard regression models cannot distinguish between true explanatory power and the influence of spatial patterns, resulting in inaccurate p-values.</li>
<li>Model misspecification: Significant spatial autocorrelation in the regression residuals often signals that important explanatory variables are missing from the model. The spatial patterning of the residuals (over- and under-predictions) can provide clues about what these missing variables might be.</li>
<li>Inflated Type I error rates: Researchers might incorrectly reject a true null. To test for spatial autocorrelation, We can run a Moran’s I test on the model’s residuals. Significant spatial autocorrelation in the residuals means the model is not capturing the full spatial story.</li>
</ul>
<p>In order to perform spatial autocorrelation test, we need to export the residual of the hedonic pricing model and save it as a data frame first.</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mlr.output</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">condo.mlr1</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we will join the newly created data frame with condo_resale.sf object.</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale.sf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">condo_resale.sf</span>, </span>
<span>                        <span class="va">condo.mlr1</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span><span class="fu">rename</span><span class="op">(</span>`MLR_RES` <span class="op">=</span> <span class="va">`condo.mlr1.residuals`</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To proof that our observation is indeed true, Global Moran’s I test will be performed</p>
<p>First, we will compute the distance-based weight matrix by using st_dist_band() function of sfdep.</p>
<div class="cell">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale.sf</span> <span class="op">&lt;-</span> <span class="va">condo_resale.sf</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    nb <span class="op">=</span> <span class="fu">st_dist_band</span><span class="op">(</span></span>
<span>      <span class="fu">st_geometry</span><span class="op">(</span><span class="va">geometry</span><span class="op">)</span>, </span>
<span>                 upper <span class="op">=</span> <span class="fl">1500</span><span class="op">)</span>,</span>
<span>    wt <span class="op">=</span> <span class="fu">st_weights</span><span class="op">(</span></span>
<span>      <span class="va">nb</span>, style <span class="op">=</span> <span class="st">"W"</span><span class="op">)</span>,</span>
<span>    .before <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, global_moran_perm() of sfdep package will be used to perform Moran’s I test for residual spatial autocorrelation</p>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="fu">global_moran_perm</span><span class="op">(</span></span>
<span>  <span class="va">condo_resale.sf</span><span class="op">$</span><span class="va">MLR_RES</span>, </span>
<span>  nb <span class="op">=</span> <span class="va">condo_resale.sf</span><span class="op">$</span><span class="va">nb</span>, </span>
<span>  wt <span class="op">=</span> <span class="va">condo_resale.sf</span><span class="op">$</span><span class="va">wt</span>,</span>
<span>  alternative <span class="op">=</span> <span class="st">"two.sided"</span>, </span>
<span>  nsim <span class="op">=</span> <span class="fl">499</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  x 
weights: listw  
number of simulations + 1: 500 

statistic = 0.14389, observed rank = 500, p-value &lt; 2.2e-16
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>The Global Moran’s I test for residual spatial autocorrelation shows that it’s p-value is less than 0.00000000000000022 which is less than the alpha value of 0.05. Hence, we will reject the null hypothesis that the residuals are randomly distributed.</p>
<p>Since the Observed Global Moran I = 0.14389 which is greater than 0, we can infer than the residuals resemble cluster distribution.</p>
</section></section></section><section id="building-hedonic-pricing-models-using-gwmodel" class="level2" data-number="9"><h2 data-number="9" class="anchored" data-anchor-id="building-hedonic-pricing-models-using-gwmodel">
<span class="header-section-number">9</span> Building Hedonic Pricing Models using GWmodel</h2>
<p>In this section, you are going to learn how to modelling hedonic pricing using both the fixed and adaptive bandwidth schemes</p>
<section id="building-fixed-bandwidth-gwr-model" class="level3" data-number="9.1"><h3 data-number="9.1" class="anchored" data-anchor-id="building-fixed-bandwidth-gwr-model">
<span class="header-section-number">9.1</span> Building Fixed Bandwidth GWR Model</h3>
<section id="computing-fixed-bandwith" class="level4" data-number="9.1.1"><h4 data-number="9.1.1" class="anchored" data-anchor-id="computing-fixed-bandwith">
<span class="header-section-number">9.1.1</span> Computing fixed bandwith</h4>
<p>In the code chunk below bw.gwr() of GWModel package is used to determine the optimal fixed bandwidth to use in the model. Notice that the argument adaptive is set to FALSE indicates that we are interested to compute the fixed bandwidth.</p>
<p>There are two possible approaches can be uused to determine the stopping rule, they are: CV cross-validation approach and AIC corrected (AICc) approach. We define the stopping rule using approach argeement.</p>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bw.fixed</span> <span class="op">&lt;-</span> <span class="fu">bw.gwr</span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span>  <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_ELDERLYCARE</span>    <span class="op">+</span></span>
<span>    <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span> <span class="va">PROX_MRT</span> <span class="op">+</span> <span class="va">PROX_PARK</span> <span class="op">+</span> </span>
<span>    <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> <span class="va">PROX_SHOPPING_MALL</span>   <span class="op">+</span> </span>
<span>    <span class="va">PROX_BUS_STOP</span>   <span class="op">+</span> <span class="va">NO_Of_UNITS</span> <span class="op">+</span> <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> </span>
<span>    <span class="va">FREEHOLD</span>, </span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>  approach<span class="op">=</span><span class="st">"AIC"</span>, </span>
<span>  kernel<span class="op">=</span><span class="st">"gaussian"</span>, </span>
<span>  adaptive<span class="op">=</span><span class="cn">FALSE</span>, </span>
<span>  longlat<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fixed bandwidth: 17660.96 AICc value: 42937.77 
Fixed bandwidth: 10917.26 AICc value: 42886.26 
Fixed bandwidth: 6749.419 AICc value: 42757.54 
Fixed bandwidth: 4173.553 AICc value: 42565.01 
Fixed bandwidth: 2581.58 AICc value: 42368.05 
Fixed bandwidth: 1597.687 AICc value: 42256.42 
Fixed bandwidth: 989.6077 AICc value: 42262.3 
Fixed bandwidth: 1973.501 AICc value: 42279.95 
Fixed bandwidth: 1365.421 AICc value: 42254.72 
Fixed bandwidth: 1221.873 AICc value: 42255.41 
Fixed bandwidth: 1454.139 AICc value: 42254.82 
Fixed bandwidth: 1310.591 AICc value: 42254.84 
Fixed bandwidth: 1399.309 AICc value: 42254.71 
Fixed bandwidth: 1420.252 AICc value: 42254.73 
Fixed bandwidth: 1386.365 AICc value: 42254.7 
Fixed bandwidth: 1378.365 AICc value: 42254.71 
Fixed bandwidth: 1391.309 AICc value: 42254.7 </code></pre>
</div>
</div>
<p>The result shows that the recommended bandwidth is 971.3405 metres.</p>
</section><section id="gwmodel-method---fixed-bandwith" class="level4" data-number="9.1.2"><h4 data-number="9.1.2" class="anchored" data-anchor-id="gwmodel-method---fixed-bandwith">
<span class="header-section-number">9.1.2</span> GWModel method - fixed bandwith</h4>
<p>Now we can use the code chunk below to calibrate the gwr model using fixed bandwidth and gaussian kernel.</p>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gwr.fixed</span> <span class="op">&lt;-</span> <span class="fu">gwr.basic</span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span>  <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_ELDERLYCARE</span>    <span class="op">+</span></span>
<span>    <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span> <span class="va">PROX_MRT</span> <span class="op">+</span> <span class="va">PROX_PARK</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> <span class="va">PROX_SHOPPING_MALL</span>   <span class="op">+</span> </span>
<span>    <span class="va">PROX_BUS_STOP</span>   <span class="op">+</span> <span class="va">NO_Of_UNITS</span> <span class="op">+</span> <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> </span>
<span>    <span class="va">FREEHOLD</span>, </span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>  bw<span class="op">=</span><span class="va">bw.fixed</span>, </span>
<span>  kernel <span class="op">=</span> <span class="st">'gaussian'</span>, </span>
<span>  longlat <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output is saved in a list of class “gwrm”. The code below can be used to display the model output.</p>
<div class="cell">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gwr.fixed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2025-10-18 15:45:03.990242 
   Call:
   gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + 
    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + 
    PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + 
    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
    data = condo_resale.sf, bw = bw.fixed, kernel = "gaussian", 
    longlat = FALSE)

   Dependent (y) variable:  SELLING_PRICE
   Independent variables:  AREA_SQM AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE PROX_URA_GROWTH_AREA PROX_MRT PROX_PARK PROX_PRIMARY_SCH PROX_SHOPPING_MALL PROX_BUS_STOP NO_Of_UNITS FAMILY_FRIENDLY FREEHOLD
   Number of data points: 1436
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
     Min       1Q   Median       3Q      Max 
-3470778  -298119   -23481   248917 12234210 

   Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
   (Intercept)           527633.22  108183.22   4.877 1.20e-06 ***
   AREA_SQM               12777.52     367.48  34.771  &lt; 2e-16 ***
   AGE                   -24687.74    2754.84  -8.962  &lt; 2e-16 ***
   PROX_CBD              -77131.32    5763.12 -13.384  &lt; 2e-16 ***
   PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** 
   PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***
   PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***
   PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***
   PROX_PARK             570504.81   65507.03   8.709  &lt; 2e-16 ***
   PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** 
   PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***
   PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***
   NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** 
   FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** 
   FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 756000 on 1421 degrees of freedom
   Multiple R-squared: 0.6507
   Adjusted R-squared: 0.6472 
   F-statistic: 189.1 on 14 and 1421 DF,  p-value: &lt; 2.2e-16 
   ***Extra Diagnostic information
   Residual sum of squares: 8.120609e+14
   Sigma(hat): 752522.9
   AIC:  42966.76
   AICc:  42967.14
   BIC:  41731.39
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: gaussian 
   Fixed bandwidth: 1386.365 
   Regression points: the same locations as observations are used.
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                               Min.     1st Qu.      Median     3rd Qu.
   Intercept            -5.0947e+06  7.5228e+04  9.6933e+05  1.6560e+06
   AREA_SQM              2.5558e+03  5.4041e+03  7.6995e+03  1.2569e+04
   AGE                  -8.4563e+04 -2.1045e+04 -1.1083e+04 -5.3192e+03
   PROX_CBD             -3.0121e+06 -2.2299e+05 -1.0207e+05 -5.3900e+04
   PROX_CHILDCARE       -3.6679e+06 -1.7018e+05 -1.6108e+04  2.4420e+05
   PROX_ELDERLYCARE     -4.9526e+05 -4.0047e+04  7.6715e+04  1.9650e+05
   PROX_URA_GROWTH_AREA -3.0350e+05 -3.0201e+04  5.1598e+04  1.5573e+05
   PROX_MRT             -2.6892e+06 -3.9441e+05 -2.3485e+05 -1.3171e+05
   PROX_PARK            -9.1626e+05 -1.2375e+05  4.7999e+04  4.0312e+05
   PROX_PRIMARY_SCH     -4.7607e+05 -1.2189e+05  2.9963e+04  3.0890e+05
   PROX_SHOPPING_MALL   -9.7562e+05 -1.2594e+05 -1.2552e+04  1.0019e+05
   PROX_BUS_STOP        -8.4504e+05  8.8484e+04  3.7699e+05  1.4980e+06
   NO_Of_UNITS          -1.2111e+03 -3.4940e+02 -5.8441e+01  1.0022e+02
   FAMILY_FRIENDLY      -1.3608e+06 -5.1541e+04  1.0951e+04  1.5911e+05
   FREEHOLD             -1.1559e+05  9.5013e+04  2.0430e+05  3.5295e+05
                             Max.
   Intercept            4639265.4
   AREA_SQM               19642.4
   AGE                    41275.9
   PROX_CBD              272116.0
   PROX_CHILDCARE       1776212.0
   PROX_ELDERLYCARE     2742988.5
   PROX_URA_GROWTH_AREA 3038754.5
   PROX_MRT             1349867.9
   PROX_PARK            1102849.3
   PROX_PRIMARY_SCH     2148894.9
   PROX_SHOPPING_MALL    668261.7
   PROX_BUS_STOP        4267600.2
   NO_Of_UNITS             2174.3
   FAMILY_FRIENDLY      1289044.9
   FREEHOLD             1001304.5
   ************************Diagnostic information*************************
   Number of data points: 1436 
   Effective number of parameters (2trace(S) - trace(S'S)): 302.5667 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1133.433 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 42254.7 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 41902.94 
   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 42011.36 
   Residual sum of squares: 3.334499e+14 
   R-square value:  0.8565589 
   Adjusted R-square value:  0.8182339 

   ***********************************************************************
   Program stops at: 2025-10-18 15:45:04.701269 </code></pre>
</div>
</div>
<p>The report shows that the AICc of the gwr is 42263.61 which is significantly smaller than the globel multiple linear regression model of 42967.1.</p>
</section></section></section><section id="building-adaptive-bandwidth-gwr-model" class="level2" data-number="10"><h2 data-number="10" class="anchored" data-anchor-id="building-adaptive-bandwidth-gwr-model">
<span class="header-section-number">10</span> Building Adaptive Bandwidth GWR Model</h2>
<section id="computing-the-adaptive-bandwidth-with-aic" class="level3" data-number="10.1"><h3 data-number="10.1" class="anchored" data-anchor-id="computing-the-adaptive-bandwidth-with-aic">
<span class="header-section-number">10.1</span> Computing the adaptive bandwidth witH AIC</h3>
<div class="cell">
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bw.adaptive</span> <span class="op">&lt;-</span> <span class="fu">bw.gwr</span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span>  <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_ELDERLYCARE</span>    <span class="op">+</span></span>
<span>    <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span> <span class="va">PROX_MRT</span> <span class="op">+</span> <span class="va">PROX_PARK</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> <span class="va">PROX_SHOPPING_MALL</span>   <span class="op">+</span> </span>
<span>    <span class="va">PROX_BUS_STOP</span>   <span class="op">+</span> <span class="va">NO_Of_UNITS</span> <span class="op">+</span> </span>
<span>    <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> <span class="va">FREEHOLD</span>, </span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>  approach<span class="op">=</span><span class="st">"AIC"</span>, </span>
<span>  kernel<span class="op">=</span><span class="st">"gaussian"</span>, </span>
<span>  adaptive<span class="op">=</span><span class="cn">TRUE</span>, </span>
<span>  longlat<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive bandwidth (number of nearest neighbours): 895 AICc value: 42879.45 
Adaptive bandwidth (number of nearest neighbours): 561 AICc value: 42823.52 
Adaptive bandwidth (number of nearest neighbours): 354 AICc value: 42677.14 
Adaptive bandwidth (number of nearest neighbours): 226 AICc value: 42484.37 
Adaptive bandwidth (number of nearest neighbours): 147 AICc value: 42353.27 
Adaptive bandwidth (number of nearest neighbours): 98 AICc value: 42280.68 
Adaptive bandwidth (number of nearest neighbours): 68 AICc value: 42201.18 
Adaptive bandwidth (number of nearest neighbours): 49 AICc value: 42100.66 
Adaptive bandwidth (number of nearest neighbours): 37 AICc value: 42055.68 
Adaptive bandwidth (number of nearest neighbours): 30 AICc value: 41982.22 
Adaptive bandwidth (number of nearest neighbours): 25 AICc value: 42003.33 
Adaptive bandwidth (number of nearest neighbours): 32 AICc value: 42035.41 
Adaptive bandwidth (number of nearest neighbours): 27 AICc value: 41978.63 
Adaptive bandwidth (number of nearest neighbours): 27 AICc value: 41978.63 </code></pre>
</div>
</div>
<p>Best bandwidth = 27 nearest neighbours This is because AICc = 41978.63 is the lowest among all computed values the model with this bandwidth achieves the best trade-off between fit and complexity.</p>
</section><section id="constructing-the-adaptive-bandwidth-gwr-model" class="level3" data-number="10.2"><h3 data-number="10.2" class="anchored" data-anchor-id="constructing-the-adaptive-bandwidth-gwr-model">
<span class="header-section-number">10.2</span> Constructing the adaptive bandwidth gwr model</h3>
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gwr.adaptive</span> <span class="op">&lt;-</span> <span class="fu">gwr.basic</span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">SELLING_PRICE</span> <span class="op">~</span> <span class="va">AREA_SQM</span> <span class="op">+</span> <span class="va">AGE</span> <span class="op">+</span> </span>
<span>    <span class="va">PROX_CBD</span> <span class="op">+</span> <span class="va">PROX_CHILDCARE</span> <span class="op">+</span> <span class="va">PROX_ELDERLYCARE</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_URA_GROWTH_AREA</span> <span class="op">+</span> <span class="va">PROX_MRT</span> <span class="op">+</span> <span class="va">PROX_PARK</span> <span class="op">+</span></span>
<span>    <span class="va">PROX_PRIMARY_SCH</span> <span class="op">+</span> <span class="va">PROX_SHOPPING_MALL</span> <span class="op">+</span> <span class="va">PROX_BUS_STOP</span> <span class="op">+</span></span>
<span>    <span class="va">NO_Of_UNITS</span> <span class="op">+</span> <span class="va">FAMILY_FRIENDLY</span> <span class="op">+</span> <span class="va">FREEHOLD</span>,</span>
<span>  data<span class="op">=</span><span class="va">condo_resale.sf</span>, </span>
<span>  bw<span class="op">=</span><span class="va">bw.adaptive</span>, </span>
<span>  kernel <span class="op">=</span> <span class="st">'gaussian'</span>, </span>
<span>  adaptive<span class="op">=</span><span class="cn">TRUE</span>, </span>
<span>  longlat <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gwr.adaptive</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2025-10-18 15:45:13.743804 
   Call:
   gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + 
    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + 
    PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + 
    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
    data = condo_resale.sf, bw = bw.adaptive, kernel = "gaussian", 
    adaptive = TRUE, longlat = FALSE)

   Dependent (y) variable:  SELLING_PRICE
   Independent variables:  AREA_SQM AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE PROX_URA_GROWTH_AREA PROX_MRT PROX_PARK PROX_PRIMARY_SCH PROX_SHOPPING_MALL PROX_BUS_STOP NO_Of_UNITS FAMILY_FRIENDLY FREEHOLD
   Number of data points: 1436
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
     Min       1Q   Median       3Q      Max 
-3470778  -298119   -23481   248917 12234210 

   Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
   (Intercept)           527633.22  108183.22   4.877 1.20e-06 ***
   AREA_SQM               12777.52     367.48  34.771  &lt; 2e-16 ***
   AGE                   -24687.74    2754.84  -8.962  &lt; 2e-16 ***
   PROX_CBD              -77131.32    5763.12 -13.384  &lt; 2e-16 ***
   PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** 
   PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***
   PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***
   PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***
   PROX_PARK             570504.81   65507.03   8.709  &lt; 2e-16 ***
   PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** 
   PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***
   PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***
   NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** 
   FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** 
   FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 756000 on 1421 degrees of freedom
   Multiple R-squared: 0.6507
   Adjusted R-squared: 0.6472 
   F-statistic: 189.1 on 14 and 1421 DF,  p-value: &lt; 2.2e-16 
   ***Extra Diagnostic information
   Residual sum of squares: 8.120609e+14
   Sigma(hat): 752522.9
   AIC:  42966.76
   AICc:  42967.14
   BIC:  41731.39
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: gaussian 
   Adaptive bandwidth: 27 (number of nearest neighbours)
   Regression points: the same locations as observations are used.
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                               Min.     1st Qu.      Median     3rd Qu.
   Intercept            -3.4055e+08 -4.9698e+05  7.6667e+05  1.6291e+06
   AREA_SQM              3.2900e+03  5.5381e+03  7.6847e+03  1.2674e+04
   AGE                  -1.0016e+05 -2.7556e+04 -1.3592e+04 -4.6598e+03
   PROX_CBD             -4.0881e+06 -1.9515e+05 -7.3518e+04  2.9526e+04
   PROX_CHILDCARE       -1.7059e+06 -2.6967e+05 -1.2514e+04  3.4777e+05
   PROX_ELDERLYCARE     -2.2412e+06 -9.4985e+04  7.9372e+04  3.2765e+05
   PROX_URA_GROWTH_AREA -1.8375e+07 -2.3765e+04  5.7504e+04  2.9631e+05
   PROX_MRT             -4.5351e+07 -6.2318e+05 -2.0888e+05 -3.8964e+04
   PROX_PARK            -1.0166e+08 -2.0084e+05  1.1152e+05  4.4450e+05
   PROX_PRIMARY_SCH     -4.6505e+06 -1.9579e+05 -9.1754e+03  4.3824e+05
   PROX_SHOPPING_MALL   -2.4269e+06 -1.4053e+05 -1.3684e+04  1.5823e+05
   PROX_BUS_STOP        -2.1436e+06 -8.7705e+04  4.1820e+05  1.2784e+06
   NO_Of_UNITS          -3.2993e+03 -2.2606e+02 -2.1790e+01  1.4231e+02
   FAMILY_FRIENDLY      -4.0477e+06 -6.5054e+04  2.2989e+04  1.9452e+05
   FREEHOLD             -1.0164e+08  2.4578e+04  1.8212e+05  3.8182e+05
                              Max.
   Intercept            55107367.9
   AREA_SQM                23242.4
   AGE                    265480.4
   PROX_CBD             26220365.8
   PROX_CHILDCARE        3565627.3
   PROX_ELDERLYCARE     93434431.6
   PROX_URA_GROWTH_AREA 25096284.3
   PROX_MRT              9223676.9
   PROX_PARK             2754387.0
   PROX_PRIMARY_SCH      4618809.5
   PROX_SHOPPING_MALL   39514834.8
   PROX_BUS_STOP        13319341.1
   NO_Of_UNITS              9878.1
   FAMILY_FRIENDLY       2315112.2
   FREEHOLD              1876281.2
   ************************Diagnostic information*************************
   Number of data points: 1436 
   Effective number of parameters (2trace(S) - trace(S'S)): 393.0807 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1042.919 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 41978.63 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 41453.88 
   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 42070.13 
   Residual sum of squares: 2.305296e+14 
   R-square value:  0.9008324 
   Adjusted R-square value:  0.8634199 

   ***********************************************************************
   Program stops at: 2025-10-18 15:45:14.578309 </code></pre>
</div>
</div>
</section></section><section id="converting-sdf-into-sf-data.frame" class="level2" data-number="11"><h2 data-number="11" class="anchored" data-anchor-id="converting-sdf-into-sf-data.frame">
<span class="header-section-number">11</span> Converting SDF into sf data.frame</h2>
<div class="cell">
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">condo_resale.sf.adaptive</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">st_as_sf</span><span class="op">(</span><span class="va">gwr.adaptive</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">st_transform</span><span class="op">(</span>crs<span class="op">=</span><span class="fl">3414</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">glimpse</span><span class="op">(</span><span class="va">condo_resale.sf.adaptive</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,436
Columns: 52
$ Intercept               &lt;dbl&gt; 2044700.26, 1773153.15, 3520072.36, 1539855.35…
$ AREA_SQM                &lt;dbl&gt; 9559.598, 15390.155, 13016.013, 21340.305, 678…
$ AGE                     &lt;dbl&gt; -9500.111, -48975.055, -25897.022, -97109.448,…
$ PROX_CBD                &lt;dbl&gt; -120265.31, -173034.60, -266084.74, 4535464.61…
$ PROX_CHILDCARE          &lt;dbl&gt; 318045.039, 348815.035, -194366.004, 286266.93…
$ PROX_ELDERLYCARE        &lt;dbl&gt; -394643.95, 238275.45, 558021.92, 402763.72, -…
$ PROX_URA_GROWTH_AREA    &lt;dbl&gt; -159575.59, -31187.00, -253591.14, -4781655.68…
$ PROX_MRT                &lt;dbl&gt; -299592.54, -2557296.15, -942766.83, -2495885.…
$ PROX_PARK               &lt;dbl&gt; -172380.89, 442318.02, 246972.65, -937538.48, …
$ PROX_PRIMARY_SCH        &lt;dbl&gt; 242732.037, 919399.390, 558785.123, 3340638.60…
$ PROX_SHOPPING_MALL      &lt;dbl&gt; 302051.162, -215149.309, -142022.712, 134573.9…
$ PROX_BUS_STOP           &lt;dbl&gt; 1209536.14, 1919405.53, 1450141.54, 8743551.68…
$ NO_Of_UNITS             &lt;dbl&gt; 106.372669, -211.071177, 19.339246, -150.59531…
$ FAMILY_FRIENDLY         &lt;dbl&gt; -9098.124, 152642.975, -29284.824, 1723147.674…
$ FREEHOLD                &lt;dbl&gt; 303927.63, 400568.89, 162972.29, 1318502.10, 3…
$ y                       &lt;dbl&gt; 3000000, 3880000, 3325000, 4250000, 1400000, 1…
$ yhat                    &lt;dbl&gt; 2885980.3, 3464956.3, 3621402.8, 5528248.5, 13…
$ residual                &lt;dbl&gt; 114019.686, 415043.736, -296402.814, -1278248.…
$ CV_Score                &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Stud_residual           &lt;dbl&gt; 0.39812858, 1.12993822, -0.89467945, -3.237264…
$ Intercept_SE            &lt;dbl&gt; 505352.2, 959583.4, 1088656.5, 644451.8, 21882…
$ AREA_SQM_SE             &lt;dbl&gt; 803.9810, 1041.2806, 1005.1322, 647.0447, 1408…
$ AGE_SE                  &lt;dbl&gt; 5754.545, 7873.214, 6772.090, 6339.353, 8401.1…
$ PROX_CBD_SE             &lt;dbl&gt; 36644.67, 46892.76, 64224.98, 723130.45, 42870…
$ PROX_CHILDCARE_SE       &lt;dbl&gt; 311604.5, 383548.3, 356362.3, 318029.0, 726053…
$ PROX_ELDERLYCARE_SE     &lt;dbl&gt; 117822.10, 121329.51, 145658.37, 153818.83, 36…
$ PROX_URA_GROWTH_AREA_SE &lt;dbl&gt; 54991.59, 138590.35, 104509.67, 714454.45, 501…
$ PROX_MRT_SE             &lt;dbl&gt; 181049.7, 426727.9, 290345.8, 310229.2, 399736…
$ PROX_PARK_SE            &lt;dbl&gt; 200556.4, 337273.4, 328846.1, 250084.3, 406910…
$ PROX_PRIMARY_SCH_SE     &lt;dbl&gt; 149035.4, 213215.4, 206844.1, 276593.8, 253671…
$ PROX_SHOPPING_MALL_SE   &lt;dbl&gt; 106789.05, 168563.26, 124684.33, 237237.76, 33…
$ PROX_BUS_STOP_SE        &lt;dbl&gt; 587417.1, 527904.1, 468907.1, 625949.7, 748596…
$ NO_Of_UNITS_SE          &lt;dbl&gt; 213.2704, 232.9495, 211.9892, 452.1575, 315.82…
$ FAMILY_FRIENDLY_SE      &lt;dbl&gt; 128381.97, 139756.71, 152249.80, 115274.06, 16…
$ FREEHOLD_SE             &lt;dbl&gt; 113234.6, 170426.6, 146100.1, 149874.1, 215886…
$ Intercept_TV            &lt;dbl&gt; 4.04608981, 1.84783643, 3.23340951, 2.38940359…
$ AREA_SQM_TV             &lt;dbl&gt; 11.890328, 14.780026, 12.949553, 32.981191, 4.…
$ AGE_TV                  &lt;dbl&gt; -1.6508882, -6.2204656, -3.8240810, -15.318510…
$ PROX_CBD_TV             &lt;dbl&gt; -3.28193222, -3.69000648, -4.14301022, 6.27198…
$ PROX_CHILDCARE_TV       &lt;dbl&gt; 1.020669014, 0.909442298, -0.545416851, 0.9001…
$ PROX_ELDERLYCARE_TV     &lt;dbl&gt; -3.34948996, 1.96387060, 3.83103226, 2.6184291…
$ PROX_URA_GROWTH_AREA_TV &lt;dbl&gt; -2.90181817, -0.22503007, -2.42648497, -6.6927…
$ PROX_MRT_TV             &lt;dbl&gt; -1.65475280, -5.99280279, -3.24704810, -8.0452…
$ PROX_PARK_TV            &lt;dbl&gt; -0.8595132, 1.3114524, 0.7510281, -3.7488897, …
$ PROX_PRIMARY_SCH_TV     &lt;dbl&gt; 1.62868734, 4.31206879, 2.70147945, 12.0777779…
$ PROX_SHOPPING_MALL_TV   &lt;dbl&gt; 2.82848439, -1.27637129, -1.13905821, 0.567253…
$ PROX_BUS_STOP_TV        &lt;dbl&gt; 2.0590756, 3.6358978, 3.0925989, 13.9684567, 0…
$ NO_Of_UNITS_TV          &lt;dbl&gt; 0.49876913, -0.90608143, 0.09122749, -0.333059…
$ FAMILY_FRIENDLY_TV      &lt;dbl&gt; -0.07086762, 1.09220500, -0.19234721, 14.94826…
$ FREEHOLD_TV             &lt;dbl&gt; 2.68405282, 2.35038940, 1.11548393, 8.79739845…
$ Local_R2                &lt;dbl&gt; 0.9172836, 0.9154542, 0.9132622, 0.9192190, 0.…
$ geometry                &lt;POINT [m]&gt; POINT (22085.12 29951.54), POINT (25656.…</code></pre>
</div>
</div>
</section><section id="visualising-and-plotting-of-r2-in-tampinies" class="level2" data-number="12"><h2 data-number="12" class="anchored" data-anchor-id="visualising-and-plotting-of-r2-in-tampinies">
<span class="header-section-number">12</span> Visualising and PLotting of R2 in Tampinies</h2>
<div class="cell">
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pa_col</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grepl</a></span><span class="op">(</span><span class="st">"PLN|PLAN.*AREA"</span>, <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">mpsz_svy21</span><span class="op">)</span>, ignore.case <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">]</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">mpsz_tamp</span> <span class="op">&lt;-</span> <span class="va">mpsz_svy21</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="op">!</span><span class="fu">rlang</span><span class="fu">::</span><span class="fu"><a href="https://rlang.r-lib.org/reference/sym.html">sym</a></span><span class="op">(</span><span class="va">pa_col</span><span class="op">)</span> <span class="op">==</span> <span class="st">"TAMPINES"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 3) Keep only points that fall inside Tampines</span></span>
<span><span class="va">pts_tamp</span> <span class="op">&lt;-</span> <span class="fu">st_join</span><span class="op">(</span><span class="va">condo_resale.sf.adaptive</span>, <span class="va">mpsz_tamp</span><span class="op">[</span><span class="st">"SUBZONE_N"</span><span class="op">]</span>, join <span class="op">=</span> <span class="va">st_within</span>, left <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co"># (left = FALSE drops points outside; use left=TRUE if you want to keep NAs)</span></span>
<span></span>
<span><span class="co"># 4) Plot Local R² for Tampines only</span></span>
<span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">mpsz_tamp</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_polygons</span><span class="op">(</span>col <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span> <span class="op">+</span>               <span class="co"># was fill_alpha=0.1; make polygon transparent</span></span>
<span>  <span class="fu">tm_borders</span><span class="op">(</span>col <span class="op">=</span> <span class="st">"gray60"</span>, lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span> <span class="co"># add clear border</span></span>
<span><span class="fu">tm_shape</span><span class="op">(</span><span class="va">pts_tamp</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">tm_dots</span><span class="op">(</span>col <span class="op">=</span> <span class="st">"Local_R2"</span>,</span>
<span>          palette <span class="op">=</span> <span class="st">"-RdYlBu"</span>,          <span class="co"># was "Blues" → strong diverging palette</span></span>
<span>          style <span class="op">=</span> <span class="st">"fixed"</span>,              <span class="co"># fix the breaks for consistent reading</span></span>
<span>          breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.88</span>, <span class="fl">0.98</span>, <span class="fl">0.02</span><span class="op">)</span>,  <span class="co"># 0.88–0.98 in 0.02 steps</span></span>
<span>          size <span class="op">=</span> <span class="fl">0.35</span>,</span>
<span>          border.col <span class="op">=</span> <span class="st">"gray20"</span>,</span>
<span>          border.lwd <span class="op">=</span> <span class="fl">0.4</span>,</span>
<span>          title <span class="op">=</span> <span class="st">"Local R² (Tampines)"</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu">tm_layout</span><span class="op">(</span>legend.outside <span class="op">=</span> <span class="cn">TRUE</span>, legend.title.size <span class="op">=</span> <span class="fl">1</span>, legend.text.size <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The Local R² map for Tampines shows how well the Geographically Weighted Regression (GWR) model explains variations in condominium resale prices across the subzones of Tampines. Local R² values range between 0.88 and 0.98, indicating generally strong model performance throughout the area.</p>
<p>High Local R² values (0.94–0.98, shown in red) are concentrated in the central and eastern parts of Tampines. This suggests that the chosen explanatory variables—such as floor area, building age, and proximity to MRT stations, parks, and schools—effectively capture the spatial variability of property prices in these subzones. These areas are typically well-developed, with stable housing markets and strong accessibility features that align with the predictors used in the model.</p>
<p>In contrast, the western and peripheral subzones show slightly lower R² values (0.88–0.92, shown in blue). This indicates that the model explains less of the price variation in these locations. The weaker performance may be attributed to local heterogeneity in property characteristics, differences in condominium types, or unobserved neighbourhood amenities—such as building-specific facilities or newer developments—that were not captured in the dataset.</p>
<p>Overall, the high Local R² values across most of Tampines highlight</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>