{
  "hash": "c67e8356087e75b15a30c190841a94e4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 5A: Global Measures of Spatial Autocorrelation\"\nauthor: \"Shubham Sinha\"\ndate: \"2025-09-21\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  message: false\n  freeze: true\nformat: \n  html:\n    code-fold: false\n    code-summary: \"code chunk\"\n    number-sections: true\n    number-depth: 4\n---\n\n\n\n## Overview\n\nIn this hands-on exercise, you will learn how to compute Global Measures of Spatial Autocorrelation (GMSA) by using **spdep** package. By the end to this hands-on exercise, you will be able to:\n\n-   Import geospatial data using appropriate function(s) of **sf** package,\n-   Import csv file using appropriate function of **readr** package,\n-   Perform relational join using appropriate join function of **dplyr** package,\n-   Compute Global Spatial Autocorrelation (GSA) statistics by using appropriate functions of **spdep** package,\n    -   plot Moran scatterplot,\n    -   compute and plot spatial correlogram using appropriate function of **spdep** package.\n-   provide statistically correct interpretation of GSA statistics.\n\n## The Analytical Question\n\nIn spatial policy planning, one of the main development objective of the local government and planners is to ensure equal distribution of development in the province. In this study, we will apply spatial statistical methods to examine the distribution of development in Hunan Province, China, using a selected indicator (e.g., GDP per capita).\n\n> Our key questions are:\n>\n> 1.  Is development evenly distributed geographically?\n> 2.  If not, is there evidence of spatial clustering?\n> 3.  If clustering exists, where are these clusters located?\n\n## The Data\n\nThe following 2 datasets will be used in this exercise.\n\n| **Data Set** | **Description** | **Format** |\n|-----------------|-------------------------------------|-----------------|\n| Hunan county boundary layer | Geospatial data set representing the county boundaries of Hunan | ESRI Shapefile |\n| Hunan_2012.csv | Contains selected local development indicators for Hunan in 2012 | CSV |\n\n## Installing and Launching the R Packages\n\nThe following R packages will be used in this exercise:\n\n| **Package** | **Purpose** | **Use Case in Exercise** |\n|-----------------|----------------------------|----------------------------|\n| **sf** | Imports, manages, and processes vector-based geospatial data. | Handling vector geospatial data such as the Hunan county boundary layer in shapefile format. |\n| **spdep** | Provides functions for spatial dependence analysis, including spatial weights and spatial autocorrelation. | Computing spatial weights and creating spatially lagged variables. |\n| **tmap** | Creates static and interactive thematic maps using cartographic quality elements. | Visualizing regional development indicators and plotting maps showing spatial relationships and patterns. |\n| **tidyverse** | A collection of packages for data science tasks such as data manipulation, visualization, and modeling. | Importing CSV files, wrangling data, and performing relational joins. |\n\nTo install and load these packages, use the following code:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse)\n```\n:::\n\n\n\n\n## Import Data and Preparation\n\nIn this section, we will perform 3 necessary steps to prepare the data for analysis.\n\n\n### Import Geospatial Shapefile\n\nIn the code chunk below we will use [`st_read()`](https://r-spatial.github.io/sf/reference/st_read.html) of **sf** package to import Hunan shapefile into R. The imported shapefile will be **simple features** Object of **sf**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\",\n                 layer = \"Hunan\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `D:\\ssinha8752\\ISSS608-VAA\\Hands-on_Ex\\Hands-on_Ex05\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n### Import Aspatial csv File\n\nNext, we will import *Hunan_2012.csv* into R by using `read_csv()` of **readr** package. The output is R dataframe class.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 88 Columns: 29\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (2): County, City\ndbl (27): avg_wage, deposite, FAI, Gov_Rev, Gov_Exp, GDP, GDPPC, GIO, Loan, ...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n### Perform Relational Join\n\nhe code chunk below will be used to update the attribute table of hunan’s SpatialPolygonsDataFrame with the attribute fields of hunan2012 dataframe. This is performed by using left_join() of dplyr package.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan,hunan2012) %>%\n  select(1:4, 7, 15)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(County)`\n```\n\n\n:::\n:::\n\n\n\n### Visualizing Regional Development Indicator\n\nTo visualize the regional development indicator, we are going to prepare a basemap and a choropleth map showing the distribution of GDPPC 2012 by using qtm() of tmap package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\")) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Equal interval classification\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[tm_borders()] Argument `fiil_alpha` unknown.\n[v3->v4] `tm_layout()`: use `tm_title()` instead of `tm_layout(main.title = )`\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5)) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Quantile classification\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[tm_borders()] Argument `fiil_alpha` unknown.\n[v3->v4] `tm_layout()`: use `tm_title()` instead of `tm_layout(main.title = )`\n```\n\n\n:::\n\n```{.r .cell-code}\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05a_files/figure-html/unnamed-chunk-5-1.png){width=1536}\n:::\n:::\n\n\n\n::: callout-note\n**Observations**\n\n\nThe left plot uses equal interval classification to divide GDP per capita (GDPPC) into five evenly spaced ranges, ensuring each class spans the same value range. This method is ideal for continuous datasets like temperature or precipitation and is appreciated for its simplicity and ease of interpretation, especially for nontechnical audiences. However, it can be misleading for skewed datasets, as many data points may cluster in just one or two classes, leaving others sparsely populated or empty.\n\n------------------------------------------------------------------------\n\nIn contrast, the right plot applies equal quantile classification, which divides the 88 counties of Hunan into five groups with roughly 17.6 counties each. This approach is useful for highlighting relative rankings, such as identifying the top 20% of counties by GDPPC. While it ensures balanced representation across classes, it can distort the data’s true distribution—counties with vastly different values may end up in the same class, or similar values may be split across different classes, exaggerating differences that aren’t statistically significant.\n\n:::\n\n\n## Global Measures of Spatial Autocorrelation\n\nIn this section, we will compute global spatial autocorrelation statistics and to perform spatial complete randomness test for global spatial autocorrelation.\n\n### Computing Contiguity Spatial Weights\n\nBefore we can compute the global spatial autocorrelation statistics, we need to construct a spatial weights of the study area. The spatial weights is used to define the neighbourhood relationships between the geographical units (i.e. county) in the study area.\n\nIn the code block below, the `poly2nb()` function from the **spdep** package calculates contiguity weight matrices for the study area by identifying regions that share boundaries.\n\nBy default, `poly2nb()` uses the \"Queen\" criteria, which considers any shared boundary or corner as a neighbor (equivalent to setting `queen = TRUE`). If we want to restrict the criteria to shared boundaries only (excluding corners), set `queen = FALSE`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan,\n                queen=TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n\nThe summary report above shows that there are 88 area units in Hunan. The most connected area unit has 11 neighbours. There are two area units with only one neighbours.\n\n### Row-standardised Weights Matrix\n\nTo assign weights to neighboring polygons, we use the equal weight method (style=\"W\"), where each neighbor receives a weight of 1 divided by the total number of neighbors. These weights are then used to calculate the lagged income values by summing the weighted contributions from adjacent counties.\n\nThis approach is intuitive and simple, making it a common choice for spatial analysis. However, it has a drawback: polygons at the edges of the study area have fewer neighbors, which can distort their lagged values and misrepresent spatial autocorrelation.\n\nFor this example, we’ll stick with style=\"W\" for clarity and ease of use. Still, it's worth noting that more robust alternatives like style=\"B\" exist, which can better handle edge effects and provide more accurate spatial insights.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, style=\"W\", zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n\n\n::: callout-tip\n- The input of [`nb2listw()`](https://r-spatial.github.io/spdep/reference/nb2listw.html) must be an object of class **nb**. The syntax of the function has two major arguments, namely style and zero.poly.\n\n-   *style* can take values \"W\", \"B\", \"C\", \"U\", \"minmax\" and \"S\". B is the basic binary coding, W is row standardised (sums over all links to n), C is globally standardised (sums over all links to n), U is equal to C divided by the number of neighbours (sums over all links to unity), while S is the variance-stabilizing coding scheme proposed by Tiefelsdorf et al. 1999, p. 167-168 (sums over all links to n).\n\n-   The zero.policy=TRUE option allows for lists of non-neighbors. This should be used with caution since the user may not be aware of missing neighbors in their dataset however, a zero.policy of FALSE would return an error.\n:::\n\n## Global Measures of Spatial Autocorrelation: Moran's I\n\nIn this section, you will learn how to perform Moran's I statistics testing by using [`moran.test()`](https://r-spatial.github.io/spdep/reference/moran.test.html) of **spdep**.\n\n::: callout-note\nSpatial autocorrelation is a key concept in geographic data analysis, helping researchers understand whether similar values are clustered together or spread out across space. One widely used measure for this is **Global Moran’s I**, which evaluates the overall spatial pattern of a dataset by considering both the location of features and the values they carry. It helps determine whether the observed distribution is random, clustered, or dispersed—offering insights into underlying spatial processes such as economic inequality, disease spread, or environmental patterns.\n\nHere’s how to interpret Global Moran’s I:\n\n- **Range of Values**: Moran’s I ranges from -1 to +1.\n  - Close to +1 → strong clustering of similar values.\n  - Close to -1 → strong dispersion of similar values.\n  - Near 0 → random spatial distribution.\n\n- **Positive Spatial Autocorrelation**: High values are near other high values, and low values are near other low values.\n\n- **Negative Spatial Autocorrelation**: High values are near low values, indicating contrast between neighboring areas.\n\n- **Zero Spatial Autocorrelation**: No meaningful spatial pattern—values are randomly distributed.\n\n- **Statistical Significance**: Moran’s I is accompanied by a z-score and p-value to test whether the observed pattern is statistically significant or could have occurred by chance.\n\n\n:::\n\n### Moran's I test\n\nTo evaluate whether GDP per capita (GDPPC) values are spatially clustered across regions, we apply **Moran’s I test**, a statistical method designed to detect spatial autocorrelation. This test is implemented using the `moran.test()` function from the **spdep** package in R, which analyzes both the spatial arrangement of regions and their associated GDPPC values. The goal is to determine whether similar economic values tend to group together geographically or are randomly distributed.\n\nKey components of the test include:\n\n- **Null Hypothesis (H₀)**: No spatial autocorrelation exists—GDPPC values are randomly distributed (Moran’s I = 0).\n- **Alternative Hypothesis (H₁)**: Positive spatial autocorrelation is present—regions with similar GDPPC values are geographically clustered (Moran’s I > 0).\n- **Significance Level (α = 0.05)**: We use a 95% confidence threshold to assess whether the observed spatial pattern is statistically significant or could have occurred by chance.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran.test(hunan$GDPPC,\n           listw=rswm_q,\n           zero.policy = TRUE,\n           na.action=na.omit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: rswm_q    \n\nMoran I statistic standard deviate = 4.7351, p-value = 1.095e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.300749970      -0.011494253       0.004348351 \n```\n\n\n:::\n:::\n\n\n\n::: callout-note\n**Question: What statistical conclusion can you draw from the output above?**\n\n-   The value of Moran's I is 0.3007, a positive number, indicating positive spatial autocorrelation. This means that regions with similar GDP per capita (GDPPC) values tend to be geographically close to each other.\n\n-   The p-value is 1.095e-06, which is much smaller than our alpha value of 0.05. This provides strong evidence against the null hypothesis of no spatial autocorrelation.\n\nTherefore, We will **reject the null hypothesis at 95% confidence interval** because the p-value is smaller than our chosen alpha value.\n:::\n\n### Computing Monte Carlo Moran's I\n\nNow we analyze the spatial distribution of GDP per capita (GDPPC) across Hunan’s counties using a Monte Carlo simulation. A total of 1000 iterations will be run to assess spatial patterns. The same hypothesis testing framework—based on Moran’s I—will be applied to evaluate statistical significance.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nbperm= moran.mc(hunan$GDPPC,\n                listw=rswm_q,\n                nsim=999,\n                zero.policy = TRUE,\n                na.action=na.omit)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30075, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\n**Question: What statistical conclusion can you draw from the output above?**\n\n-   The value of Moran's I is 0.30075, which is a positive number, indicating positive spatial autocorrelation. This suggests that regions with similar GDP per capita (GDPPC) values are geographically close to each other.\n\n- The p-value obtained from the Monte Carlo simulation is 0.001, which is much smaller than our alpha value of 0.05. This provides strong evidence against the null hypothesis of no spatial autocorrelation.\n\nTherefore, we will **reject the null hypothesis at 95% confidence interval** because the p-value is smaller than our chosen alpha value.\n:::\n\n### Visualising Monte Carlo Moran's I\n\nIt is always a good practice for us the examine the simulated Moran's I test statistics in greater detail. This can be achieved by plotting the distribution of the statistical values as a histogram by using the code block below.\n\nWe will first observe the summary report of the Monte Carlo Moran's I output before visualizing the plots using `ggplot2` and base R.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the mean of the first 999 simulated Moran's I values\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01504572\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the variance of the first 999 simulated Moran's I values\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004371574\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.18339 -0.06168 -0.02125 -0.01505  0.02611  0.27593 \n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n\n#### ggplot2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(x = bperm$res), aes(x = x)) +\n  geom_histogram(binwidth = diff(range(bperm$res)) / 20,\n                 fill = \"grey\",\n                 color = \"black\") +\n  geom_vline(xintercept = 0,\n             color = \"red\",\n             linetype = \"solid\") +\n  labs(x = \"Simulated Moran's I\",\n       y = \"Frequency\",\n       title = \"Histogram of Simulated Moran's I Values\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05a_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n#### base R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res,\n     freq = TRUE,         # Show the frequency (count) on y-axis\n     breaks = 20,         # Set the number of bins\n     xlab = \"Simulated Moran's I\")\n\n# Add vertical red line at 0 to indicate the mean under the null hypothesis of no autocorrelation\nabline(v = 0,\n       col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05a_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n::: callout-note\n**Question: What statistical conclusion can you draw from the output above?**\n\nThe observed Moran's I value (0.30075) lies outside the range of most simulated values, indicating that it is an outlier compared to the expected distribution under the null hypothesis, which are centered around the expected value of 0.0 under the null hypothesis of no spatial autocorrelation. The histogram shows that most of the simulated values of Moran's I are clustered around the mean of -0.01504572, with a variance of 0.004371574.\n\nSince the observed Moran's I value is significantly greater than the bulk of the simulated values and given the p-value from the test is very small (p < 0.05), there is strong evidence against the null hypothesis.\n\nThere is significant positive spatial autocorrelation in the GDP per capita (GDPPC) across regions, as indicated by the Moran's I test. This suggests that regions with similar GDPPC values are more likely to be geographically clustered.\n\n:::\n\n## Global Measures of Spatial Autocorrelation: Geary's C\n\nIn this section, we will perform Geary's C statistics testing by using appropriate functions of **spdep** package.\n\n### Geary's C test\n\nAnother popular index of global spatial autocorrelation is Geary’s C which is a cousin to the Moran’s I.\n\n::: callout-note\n\nGeary’s C, also referred to as Geary’s contiguity ratio, is a statistical measure used to evaluate spatial autocorrelation within a dataset. Unlike Moran’s I, it is more sensitive to local differences, making it especially useful for detecting subtle spatial patterns in smaller geographic areas.\n\n**Understanding Geary’s C Values:**\n\n- **Range and Expectation**: Geary’s C ranges from 0 to 2, with an expected value of 1 under the null hypothesis of no spatial autocorrelation.\n\n- **Values Less Than 1**: Indicate positive spatial autocorrelation—neighboring areas tend to have similar attribute values.\n\n- **Value Equal to 1**: Suggests no spatial autocorrelation, implying a random spatial distribution of values.\n\n- **Values Greater Than 1**: Reflect negative spatial autocorrelation—neighboring areas are more likely to have contrasting values.\n\n\n:::\n\n>Moran’s I and Geary’s C are both global measures of spatial autocorrelation, but they differ in how they capture spatial relationships. Moran’s I relies on standardized spatial covariance to detect overall clustering patterns\n>\n>while Geary’s C uses the sum of squared differences between neighboring values, making it more sensitive to local variations. This distinction allows Geary’s C to uncover finer spatial nuances that Moran’s I might overlook.\n\nTo test for spatial autocorrelation in GDP per capita (GDPPC) across regions, we can apply Geary’s C using the `geary.test()` function from the **spdep** package in R.  \n- **Null Hypothesis (H₀)**: No spatial autocorrelation exists—Geary’s C equals 1.  \n- **Alternative Hypothesis (H₁)**: Positive spatial autocorrelation is present—Geary’s C is less than 1.  \n\nWe use a **significance level of α = 0.05**, meaning results are considered statistically significant if the p-value is below 0.05.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary.test(hunan$GDPPC, listw=rswm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  hunan$GDPPC \nweights: rswm_q   \n\nGeary C statistic standard deviate = 3.6108, p-value = 0.0001526\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        0.6907223         1.0000000         0.0073364 \n```\n\n\n:::\n:::\n\n\n::: callout-note\n**Question: What statistical conclusion can you draw from the output above?**\n\n- The value of Geary's C statistic is 0.6907, which is less than the expected value of 1.0. This indicates positive spatial autocorrelation, meaning regions with similar GDP per capita (GDPPC) values tend to be geographically close to each other.\n\n- The p-value is 0.0001526, which is much smaller than our alpha value of 0.05. This provides strong evidence against the null hypothesis of no spatial autocorrelation.\n\nTherefore, we will reject the null hypothesis at 95% confidence interval because the p-value is smaller than our chosen alpha value.\n:::\n\n### Computing Monte Carlo Geary's C\n\nSimilar to Moran’s I, it is best to test the statistical significance of Geary’s C using a Monte Carlo simulation.\n\nTo perform permutation test for Geary's C statistic by using geary.mc() of **spdep**:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm=geary.mc(hunan$GDPPC,\n               listw=rswm_q,\n               nsim=999)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.69072, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\n\n**Question: What statistical conclusion can you draw from the output above?**\n\n- The value of Geary's C statistic is 0.6907, which is less than the expected value of 1.0. This indicates positive spatial autocorrelation, meaning regions with similar GDP per capita (GDPPC) values tend to be geographically close to each other.\n\n- The p-value from the Monte Carlo simulation is 0.001, which is much smaller than our alpha value of 0.05. This provides strong evidence against the null hypothesis of no spatial autocorrelation.\n\nTherefore, we will **reject the null hypothesis at 95% confidence** because the p-value is smaller than our chosen alpha value.\n\n:::\n\n### Visualising the Monte Carlo Geary's C\n\nNext, we will plot a histogram to reveal the distribution of the simulated values by using the code block below.\n\nWe will first observe the summary report of the Geary's C output before visualizing the plots using `ggplot2` and base R.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the mean of the first 999 simulated geary's c values\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.004402\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the variance of the first 999 simulated geary's c values\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.007436493\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.7142  0.9502  1.0052  1.0044  1.0595  1.2722 \n```\n\n\n:::\n:::\n\n\n::: panel-tabset\n\n#### ggplot2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(x = bperm$res), aes(x = x)) +\n  geom_histogram(binwidth = diff(range(bperm$res)) / 20,\n                 color = \"black\",\n                 fill = \"grey\") +\n  geom_vline(xintercept = 1,\n             color = \"red\") +\n  labs(x = \"Simulated Geary's C\",\n       y = \"Frequency\",\n       title = \"Histogram of Simulated Geary's C Values\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05a_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n#### base R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, freq=TRUE, breaks=20, xlab=\"Simulated Geary's C\")\nabline(v=1, col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05a_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n::: callout-note\n**Question: What statistical conclusion can you draw from the output above?**\n\nThe observed Geary's C value (0.69072) lies outside the range of most simulated values, which are centered around the expected value of 1.0 under the null hypothesis of no spatial autocorrelation. The histogram shows that most of the simulated values of Geary's C are clustered around the mean of 1.0044, with a variance of 0.0074.\n\nSince the observed Geary's C value is significantly lower than the bulk of the simulated values and the p-value from the test is very small (p < 0.05), there is strong evidence against the null hypothesis.\n\nThere is significant positive spatial autocorrelation in the GDP per capita (GDPPC) across regions, as indicated by the Geary's C test. This suggests that regions with similar GDPPC values are more likely to be geographically clustered.\n:::\n\n",
    "supporting": [
      "Hands-on_Ex05a_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}