{
  "hash": "6b86cb49860603bf7aee563ae928bd89",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Geospatial Analytics for Public Good\"\nauthor: \"Shubham Sinha\"\ndate: \"September 12, 2025\"\ndate-modified: \"September 24, 2025\"\nexecute: \n  eval: true\n  echo: true\n  message: false\n  freeze: true\nformat: \n  html:\n    code-fold: false\n    code-summary: \"code chunk\"\n    number-sections: true\n    number-depth: 4\n---\n\n\n\n## Overview\n\nUrban development is profoundly shaped by the geography of commercial activity. The placement of businesses not only dictates economic growth and job creation but also defines the functional character of urban areas, creating specialized zones and influencing daily flows of people and goods. Consequently, investigating the evolution of these patterns over space and time is indispensable for scientific urban planning. Such analysis uncovers the dynamics of economic change, enabling evidence-based decisions that enhance sustainability, rectify inefficiencies, and improve the overall quality of life by aligning urban infrastructure with actual economic trends.\n\n## Objective\n\nThis exercise investigates the spatial and spatio-temporal distribution of new business entities established in Singapore during the first half of 2025. The analysis aims to:\n\nMap the 'Where' and 'When': Identify geographic clusters, temporal trends, and density patterns of new business formations to provide a foundational understanding for urban planning, resource allocation, and economic development strategies.\n\nUncover Complex Interactions: Reveal deeper structural patterns beyond simple density, such as attraction/repulsion between business types, the influence of historical trends on new locations, and the emergent development of commercial areas. These insights are vital for evidence-based policy-making.\n\nUltimately, by deciphering these patterns, urban planners and managers can leverage spatial intelligence to optimize infrastructure, guide sustainable growth, and craft targeted strategies for investment attraction.\n\n## The Data\n\nThe following datasets will be used in this exercise:\n\n| **Dataset Name** | **Description** | **Format** | **Source** |\n|---------------|------------------------------|--------------|--------------|\n| ACRA Information on Corporate Entities | Information on corporate entities registered in Singapore, including address, registration date, and business type. | CSV | [data.gov.sg](https://data.gov.sg/dataset/acra-information-on-corporate-entities) |\n| Singapore Planning Areas Boundary (2019) | Geospatial data detailing the planning area boundaries of Singapore. | ESRI Shapefile | [data.gov.sg](https://data.gov.sg/dataset/singapore-planning-areas-boundary-2019) |\n\nFor this exercise, we will select three business types from the Singapore Standard Industrial Classification (SSIC) 2020. For demonstration purposes, we will choose:\n\n**56111 (Food & Beverage Services)**: Represents restaurants, cafés, and eateries, which are strong indicators of neighborhood vibrancy and consumer activity, making them ideal for studying spatial concentration and short-term growth trends.\n\n**62011 (Information Technology)**: Captures IT consultancy and development firms that cluster in innovation hubs, reflecting Singapore’s digital economy growth and helping identify where high-value knowledge-based activity is emerging.\n\n**471 (Retail Trade)**: Covers supermarkets and general retail outlets, providing insight into consumption patterns and commercial accessibility across neighborhoods, complementing F&B data for a holistic view of urban vibrancy.\n\n## Installing & Launching the packages\n\nThis analysis uses the following libraries:\n\n| Library | Desc |\n|------------------------------------|------------------------------------|\n| [**sf**](https://r-spatial.github.io/sf/) | handling geospatial data |\n| [**tmap**](https://cran.r-project.org/web/packages/tmap/index.html) | visualization for geospatial data |\n| **tidyverse** | handling data including packages **readr**, **tidyr and dplyr** |\n| [**sparr**](https://tilmandavies.github.io/sparr/index.html) | provides functions to estimate fixed and adaptive kernel-smoothed spatial relative risk surfaces via the density-ratio method and perform subsequent inference.  |\n| [**spatstat**](https://spatstat.org/) | for point pattern analysis |\n| [**terra**](https://rspatial.github.io/terra/index.html) | a modern spatial data analysis package to replace the raster package. terra provides functionalities for creating, reading, manipulating, and writing raster and vector data, and it’s built on top of GDAL and PROJ libraries for enhanced performance |\n| rvest | scraping (or harvesting) data from web pages |\n| knitr | generate elegant, flexible, and fast dynamic report |\n| httr | package in R provides a set of tools for interacting with web resources via HTTP. It simplifies the process of making HTTP requests (GET, POST, PUT, DELETE, etc.) and handling the responses |\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf,tmap,tidyverse,sparr,terra,spatstat,\n               rvest,httr,knitr, ggthemes, plotly,DT)\n```\n:::\n\n\n\nFor reproducible results of this exercise, we will use seed value, 1234.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n```\n:::\n\n\n\n## Import Data\n\n### Master Plan 2019\n\nThe Master Plan 2019 is Singapore’s statutory land use plan that outlines the country’s medium-term development strategy for the next 10 to 15 years. It is provided as a polygon feature layer in **KML** format and is maintained and published by the Urban Redevelopment Authority (URA).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- st_read(\"data/geospatial/MasterPlan2019PlanningAreaBoundaryNoSea.kml\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `URA_MP19_SUBZONE_NO_SEA_PL' from data source \n  `D:\\ssinha8752\\ISSS608-VAA\\Take-home_Ex\\Take-home_Ex01\\data\\geospatial\\MasterPlan2019PlanningAreaBoundaryNoSea.kml' \n  using driver `KML'\nSimple feature collection with 332 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\nThis message indicates that the KML file MasterPlan2019PlanningAreaBoundaryNoSea.kml was successfully read using the KML driver, containing a simple feature collection of 332 multipolygon features with two attribute fields. Each feature represents a URA Master Plan 2019 subzone (excluding sea areas), described using two-dimensional geographic coordinates (longitude and latitude) under the WGS 84 coordinate reference system. The dataset covers Singapore’s extent, with a bounding box ranging roughly from 103.61°E to 104.09°E longitude and 1.16°N to 1.47°N latitude.\n\nNow we will extract the information from the HTML\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_kml_field <- function(html_text, field_name) {\n  if (is.na(html_text) || html_text == \"\") return(NA_character_) # check if text is na\n  \n  page <- read_html(html_text)\n  rows <- page %>% html_elements(\"tr\") # find table row element \n  \n  value <- rows %>%\n    # looks through each row to find table header == field_name and\n    keep(~ html_text2(html_element(.x, \"th\")) == field_name) %>% \n    html_element(\"td\") %>% # extract table data\n    html_text2() # and then extract clean text context\n  \n  if (length(value) == 0) NA_character_ else value # return value if is not NA\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- mppa %>%\n  mutate(REGION_N = map_chr(Description,extract_kml_field,\"REGION_N\"),\n         PLN_AREA_N = map_chr(Description,extract_kml_field,\"PLN_AREA_N\"))%>%\n  select(-Name, -Description) %>% # unselect columns \"Name\" and \"Description\"\n  relocate(geometry, .after = last_col()) # move the \"geometry\" to the end\n```\n:::\n\n\n\nTransforming its CRS (Coordinates Reference System) from WGS84 (EPSG: 4326) to SVY21 (EPSG:3414) for accuracy and further spatial analysis requirements, converting all feature coordinates from (latitude, longitude) degrees into (x, y) meter coordinates in Singapore’s SVY21 system :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- mppa %>%\n    #Removes Z (elevation) and M (measure) dimensions from the geometry if they exist\n  st_zm(drop = TRUE, what = \"ZM\") %>% \n  st_transform(crs = 3414)\nst_geometry(mppa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 332 features \nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nMULTIPOLYGON (((25910.34 29425.34, 26265.82 292...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nMULTIPOLYGON (((26750.09 29216.1, 26751.91 2917...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nMULTIPOLYGON (((29161.2 29723.07, 29189.03 2970...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nMULTIPOLYGON (((29814.11 29616.89, 29806.68 295...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nMULTIPOLYGON (((30137.77 29843.19, 30138.42 298...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(mppa,\"data/rds/mppa.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- read_rds(\"data/rds/mppa.rds\")\n```\n:::\n\n\n\nPlotting planning area in SG:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa) +\n  tm_polygons(col =\"REGION_N\",\n      palette = \"set2\",\n              lwd = 0.5)+\n   tm_text(\"PLN_AREA_N\", size=0.4,\n           auto.placement = TRUE,\n           remove.overlap = TRUE)+\n  tm_title(\"SG PLanning Area\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_legend(frame = FALSE,\n            position = c(\"right\", \"bottom\"))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── tmap v3 code detected ───────────────────────────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[v3->v4] `tm_tm_polygons()`: migrate the argument(s) related to the scale of\nthe visual variable `fill` namely 'palette' (rename to 'values') to fill.scale\n= tm_scale(<HERE>).\n[v3->v4] `tm_polygons()`: use 'fill' for the fill color of polygons/symbols\n(instead of 'col'), and 'col' for the outlines (instead of 'border.col').\n[v3->v4] `tm_text()`: migrate the layer options 'auto.placement' (rename to\n'point.label') to 'options = opt_tm_text(<HERE>)'\n[v3->v4] `tm_legend()`: use 'tm_legend()' inside a layer function, e.g.\n'tm_polygons(..., fill.legend = tm_legend())'\nMultiple palettes called \"set2\" found: \"brewer.set2\", \"hcl.set2\". The first one, \"brewer.set2\", is returned.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-1.png){width=1152}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa_sf <- mppa %>%\n  filter (PLN_AREA_N != \"CENTRAL WATER CATCHMENT\",\n          PLN_AREA_N != \"WESTERN WATER CATCHMENT\",\n         PLN_AREA_N != \"WESTERN ISLANDS\",\n         PLN_AREA_N != \"SOUTHERN ISLANDS\",\n         PLN_AREA_N != \"NORTH-EASTERN ISLANDS\",\n         )\n```\n:::\n\n\n\nSince our analysis is centered on business activities taking place on Singapore’s main island, we will exclude areas that are not relevant to commercial operations — such as the North-Eastern Islands, Western Islands, Southern Islands, as well as the Central and Western Water Catchments — to ensure that the results accurately reflect business-related spatial patterns. Plotting the Area again -\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa_sf) +\n  tm_polygons(col =\"REGION_N\",\n      palette = \"set2\",\n              lwd = 0.5)+\n   tm_text(\"PLN_AREA_N\", size=0.4,\n           auto.placement = TRUE,\n           remove.overlap = TRUE)+\n  tm_title(\"SG Planning Area - Business Activites\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_legend(frame = FALSE,\n            position = c(\"right\", \"bottom\"))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── tmap v3 code detected ───────────────────────────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[v3->v4] `tm_tm_polygons()`: migrate the argument(s) related to the scale of\nthe visual variable `fill` namely 'palette' (rename to 'values') to fill.scale\n= tm_scale(<HERE>).\n[v3->v4] `tm_text()`: migrate the layer options 'auto.placement' (rename to\n'point.label') to 'options = opt_tm_text(<HERE>)'\nMultiple palettes called \"set2\" found: \"brewer.set2\", \"hcl.set2\". The first one, \"brewer.set2\", is returned.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-11-1.png){width=1152}\n:::\n:::\n\n\n\n### ACRA Data\n\nWe will utilize data from the Accounting and Corporate Regulatory Authority (ACRA) for our spatial analysis. This dataset consists of 27 files, categorized by the first letter of the company name (A–Z and “Others”), and contains comprehensive details on all businesses registered in Singapore, including company profiles, industry classifications, and registration information. As the files share a consistent naming convention and are stored in a single directory, we will employ map_dfr() to efficiently import and merge them into a unified dataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfolder_path <- \"data/ACRA\"\nfile_list <- list.files(path = folder_path,\n                        pattern = \"^ACRA*.*\\\\.csv$\",\n                        full.names = TRUE)\nacra <- file_list %>%\n  map_dfr(read_csv)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nacra <- read_rds(\"data/rds/acra_data.rds\")\n```\n:::\n\n\n\n### Filtering SSIC Data\n\nExtract selected data  for three industries: Food and Beverages (SSIC 56111), Retail (SSIC 471), and Information Technology (SSIC 62011) from January to June 2025\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFNB_56111 <- acra %>%\n  select(1,3,4,8:9,11,17,22) %>%\n  filter(grepl(\"56111\", primary_ssic_code)) %>% \n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         Year = year(date),\n         Month_num = month(date,\n                           label =TRUE,\n                           abbr =TRUE)) %>%\n  # make sure the post_code are 6 digits\n  mutate(postal_code = str_pad(postal_code,\n                               width =6,\n                               side = \"left\",pad =\"0\"))  %>% \n  filter(Year == 2025,\n         Month_num %in% c(\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\"))\n\nretail_47111 <- acra %>%\n  select(1,3,4,8:9,11,17,22) %>%\n  filter(grepl(\"^471\", primary_ssic_code)) %>% \n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         Year = year(date),\n         Month_num = month(date,\n                           label =TRUE,\n                           abbr =TRUE)) %>%\n  # make sure the post_code are 6 digits\n  mutate(postal_code = str_pad(postal_code,\n                               width =6,\n                               side = \"left\",pad =\"0\"))  %>% \n  filter(Year == 2025,\n         Month_num %in% c(\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\"))\n\nIT_62011 <- acra %>%\n  select(1,3,4,8:9,11,17,22) %>%\n  filter(grepl(\"62011\", primary_ssic_code)) %>% \n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         Year = year(date),\n         Month_num = month(date,\n                           label =TRUE,\n                           abbr =TRUE)) %>%\n  # make sure the post_code are 6 digits\n  mutate(postal_code = str_pad(postal_code,\n                               width =6,\n                               side = \"left\",pad =\"0\"))  %>% \n  filter(Year == 2025,\n         Month_num %in% c(\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\"))\n```\n:::\n\n\n\n## Geocoding for Coodinates\n\nUnlike geospatial datasets that directly include latitude and longitude, the ACRA dataset only provides business locations in the form of postal codes and addresses. To convert these into usable spatial data, we need to perform geocoding, which is the process of translating text-based location information (like postal codes) into precise geographic coordinates (latitude and longitude).\n\nFor this project, we will use the OneMap API, Singapore’s official geospatial platform, to geocode each postal code. The API will return the corresponding coordinates, allowing us to plot business locations accurately on a map and perform spatial analyses such as clustering, density estimation, and proximity measurements. This step is essential because spatial operations require coordinate data, not just textual addresses.\n\n**Combining the data by row**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_data <- rbind(FNB_56111,retail_47111,IT_62011)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create folder if not exists\nif (!dir.exists(\"data/rds\")) dir.create(\"data/rds\", recursive = TRUE)\n\n# Create and save combined data if not already saved\nif (file.exists(\"data/rds/combined_data.rds\")) {\n  combined_data <- read_rds(\"data/rds/combined_data.rds\")\n} else {\n  combined_data <- rbind(FNB_56111, retail_47111, IT_62011)\n  write_rds(combined_data, \"data/rds/combined_data.rds\")\n}\n```\n:::\n\n\n\n**Extract Unique postal codes from the above extracted data**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npostcodes <- unique(combined_data$postal_code)\nlength(postcodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1280\n```\n\n\n:::\n:::\n\n\n\nOur dataset contains 1,280 unique business locations. To map them accurately, we use the `httr` package to send GET requests to the OneMap API, which returns the latitude and longitude for each postal code. This enables us to convert text-based addresses into spatial data for further analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurl <- \"https://onemap.gov.sg/api/common/elastic/search\"\n\nfound <- data.frame()\nnot_found <- data.frame(postcode =character())\n\nfor(pc in postcodes) {\n  query <- list(\n    searchVal = pc,\n    returnGeom = \"Y\",\n    getAddrDetails = \"Y\",\n    pageNum =\"1\"\n  )\n  \n  res <- GET(url, query=query)\n  json <- content(res)\n  \n  if(json$found !=0) {\n    df <- as.data.frame(json$results, stringFactors =FALSE)\n    df$input_postcode <- pc\n    found <- bind_rows(found,df)\n  } else{\n    not_found <- bind_rows(not_found, data.frame(postcode=pc))\n  }\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(found,\"data/rds/found.rds\")\nwrite_rds(not_found,\"data/rds/not_found.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfound <- read_rds(\"data/rds/found.rds\")\nnot_found <- read_rds(\"data/rds/not_found.rds\")\n```\n:::\n\n\n\n**Examining the mapping result**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(found)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1280\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(not_found)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\nThe results above indicate we successfully retrieve all the coordinates.\n\n## Combine and Convert Data into sf Format\n\nwe merge the original ACRA dataset with the geocoded results containing the spatial coordinates using left_join(). This ensures that each business record now includes its corresponding longitude (X) and latitude (Y) obtained from the OneMap API. By joining the datasets in this way, we maintain all original records while appending the newly retrieved coordinate information.\n\nOnce the datasets are combined, we use the st_as_sf() function to convert the merged dataset into an sf (simple feature) object, which is the standard format for spatial data in R. By specifying the X and Y columns as coordinates, this conversion allows us to perform spatial operations, visualizations, and analyses, such as mapping business locations, calculating distances, and identifying spatial patterns, in a structured and efficient manner.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Keep only the relevant columns from geocoded data\nfound_sel <- found %>%\n  select(POSTAL, LATITUDE, LONGITUDE)\n\n# F&B\n#FNB_sf <- FNB_56111 %>%\n#  left_join(found_sel %>% rename(X = LONGITUDE, Y = LATITUDE),\n#            by = c(\"postal_code\" = \"POSTAL\")) %>%\n#  filter(!is.na(X) & !is.na(Y)) %>%\n#  st_as_sf(coords = c(\"X\", \"Y\"), crs = 3414)\nFNB_sf <- FNB_56111 %>%\n  left_join(found_sel, by = c(\"postal_code\" = \"POSTAL\")) %>%\n  filter(!is.na(LATITUDE) & !is.na(LONGITUDE)) %>%\n  # First create with correct WGS84 CRS (4326)\n  st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), crs = 4326) %>%\n  # Then transform to match your boundary\n  st_transform(st_crs(mppa_sf))\n\n# Retail\n#retail_sf <- retail_47111 %>%\n#  left_join(found_sel %>% rename(X = LONGITUDE, Y = LATITUDE),\n#            by = c(\"postal_code\" = \"POSTAL\")) %>%\n#  filter(!is.na(X) & !is.na(Y)) %>%\n#  st_as_sf(coords = c(\"X\", \"Y\"), crs = 3414)\nretail_sf <- retail_47111 %>%\n  left_join(found_sel, by = c(\"postal_code\" = \"POSTAL\")) %>%\n  filter(!is.na(LATITUDE) & !is.na(LONGITUDE)) %>%\n  # First create with correct WGS84 CRS (4326)\n  st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), crs = 4326) %>%\n  # Then transform to match your boundary\n  st_transform(st_crs(mppa_sf))\n\n# IT\n#IT_sf <- IT_62011 %>%\n#  left_join(found_sel %>% rename(X = LONGITUDE, Y = LATITUDE),\n#            by = c(\"postal_code\" = \"POSTAL\")) %>%\n#  filter(!is.na(X) & !is.na(Y)) %>%\n#  st_as_sf(coords = c(\"X\", \"Y\"), crs = 3414)\nIT_sf <- IT_62011 %>%\n  left_join(found_sel, by = c(\"postal_code\" = \"POSTAL\")) %>%\n  filter(!is.na(LATITUDE) & !is.na(LONGITUDE)) %>%\n  # First create with correct WGS84 CRS (4326)\n  st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), crs = 4326) %>%\n  # Then transform to match your boundary\n  st_transform(st_crs(mppa_sf))\n```\n:::\n\n\n\nThe code saves the spatial datasets for F&B, retail, and IT businesses as RDS files for future use, then resolves a coordinate projection issue by transforming all three datasets to match the CRS of the study area (mppa_sf). After the transformation, a quick verification confirms the number of points in each dataset and ensures that the retail points correctly fall within the study area boundary using st_intersection(). This process ensures all spatial data are accurately aligned for subsequent analysis\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(FNB_sf,\"data/rds/FNB_sf.rds\")\nwrite_rds(retail_sf,\"data/rds/retail_sf.rds\")\nwrite_rds(IT_sf,\"data/rds/IT_sf.rds\")\n\n# Fix coordinate projection issue\nFNB_sf <- st_transform(FNB_sf, st_crs(mppa_sf))\nretail_sf <- st_transform(retail_sf, st_crs(mppa_sf))\nIT_sf <- st_transform(IT_sf, st_crs(mppa_sf))\n\n# Quick verification\ncat(\"=== Coordinate Verification ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Coordinate Verification ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"FNB points in study area:\", nrow(FNB_sf), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFNB points in study area: 596 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Retail points in study area:\", nrow(retail_sf), \"\\n\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRetail points in study area: 457 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"IT points in study area:\", nrow(IT_sf), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIT points in study area: 1597 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Check if points are now properly projected\ntest_intersection <- st_intersection(retail_sf, mppa_sf)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: attribute variables are assumed to be spatially constant throughout\nall geometries\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Retail points inside boundary after fix:\", nrow(test_intersection), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRetail points inside boundary after fix: 457 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nFNB_sf <- read_rds(\"data/rds/FNB_sf.rds\")\nretail_sf <- read_rds(\"data/rds/retail_sf.rds\")\nIT_sf <- read_rds(\"data/rds/IT_sf.rds\")\n```\n:::\n\n\n\n## Mapping Geospatial Data\n\nPlotting the map and examining the distribution of the three industries:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(FNB_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 596\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(retail_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 457\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(IT_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1597\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry(FNB_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 596 features \nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 7514.986 ymin: 26622.47 xmax: 46829.34 ymax: 49432.98\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (34007.42 41217.84)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (30569.32 31216.93)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (30900.42 33108.58)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (37390.83 34553.95)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (27549.59 46589.95)\n```\n\n\n:::\n\n```{.r .cell-code}\nst_geometry(retail_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 457 features \nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 4670.11 ymin: 27393.65 xmax: 45154.27 ymax: 49401.78\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (32829.61 36781.03)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (27808.56 45289.08)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (28071.64 31871.17)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (36343.66 41287.07)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (22308.9 35972.96)\n```\n\n\n:::\n\n```{.r .cell-code}\nst_geometry(IT_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 1597 features \nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 11775.35 ymin: 24744.89 xmax: 43955.12 ymax: 49327.11\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (29975.87 29642.37)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (29391.73 29747.36)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (29924.68 30512.73)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (29617.75 28954.42)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPOINT (29724.79 29082.07)\n```\n\n\n:::\n:::\n\n\n\n### Combined Plot of the Three Industries’ Distribution\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa_sf) +\n    tm_polygons(col =\"REGION_N\",\n                border.col = \"white\",\n      palette = \"set2\",\n              lwd = 0.5)+\ntm_shape(retail_sf) +\n  tm_dots(fill = \"red\", size = 0.5, shape = 17)+    \ntm_shape(FNB_sf) +\n  tm_dots(fill = \"blue\", size = 0.5, shape = 16)+\ntm_shape(IT_sf) +\n  tm_dots(fill = \"black\", size = 0.5, shape = 18)+\n\n  tm_title(\"Activity Distribution: H1 2025\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_legend(frame = FALSE,\n            position = c(\"right\", \"bottom\"))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── tmap v3 code detected ───────────────────────────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[v3->v4] `tm_tm_polygons()`: migrate the argument(s) related to the scale of\nthe visual variable `fill` namely 'palette' (rename to 'values') to fill.scale\n= tm_scale(<HERE>).\nMultiple palettes called \"set2\" found: \"brewer.set2\", \"hcl.set2\". The first one, \"brewer.set2\", is returned.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-27-1.png){width=1152}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(mppa_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(FNB_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(retail_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(IT_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\n\n## Geospatial Data wrangling\n\nThe spatstat package requires specialized data structures—ppp for planar point patterns and owin for observation windows—we must convert our sf (Simple Features) objects into corresponding ppp and owin formats.\n\n### Converting sf dfs to ppp class\n\nThe following code leverages as.ppp() from the spatstat package to transform data from sf format into the ppp (planar point pattern) format. To handle cases where multiple points have identical coordinates—such as businesses sharing the same postal code—rjitter() is applied to slightly offset the points and eliminate duplicates.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFNB_ppp <- as.ppp(FNB_sf)%>%\n          rjitter(retry = TRUE,\n          nsim = 1,\n          drop = TRUE)\nIT_ppp <- as.ppp(IT_sf)%>%\n          rjitter(retry = TRUE,\n          nsim = 1,\n          drop = TRUE)\nretail_ppp <- as.ppp(retail_sf)%>%\n          rjitter(retry = TRUE,\n          nsim = 1,\n          drop = TRUE)\n```\n:::\n\n\n\n### Creating owin object\n\nIn **spatstat**, an **owin** object is used to represent a polygonal study region. It defines the spatial boundaries within which point pattern analysis is performed. By converting the study area into an owin object, we ensure that all spatial computations are restricted to the correct geographic extent.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsg_owin <- as.owin(mppa_sf)\n```\n:::\n\n\n\nThe study area look like this\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(sg_owin)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-31-1.png){width=1152}\n:::\n:::\n\n\n\n### Combining point events object and owin object\n\nThe code below combine ppp and owin objects\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFNBSG_ppp <- FNB_ppp[sg_owin]\nretailSG_ppp <- retail_ppp[sg_owin]\nITSG_ppp <- IT_ppp[sg_owin]\n```\n:::\n\n\n\nExamine the output for three ppp objects:\n\n::: panel-tabset\n#### Food n Bev\n\nA point is dropped outside the study area\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n FNBSG_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 594 points\nMark variables: \n   uen entity_name entity_type_description entity_status_description date \naddress_type postal_code primary_ssic_code Year Month_num\nwindow: polygonal boundary\nenclosing rectangle: [2667.54, 55941.94] x [21448.47, 50256.33] units\n```\n\n\n:::\n:::\n\n\n\n#### Retail Stores\n\nAll points are within the study area\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nretailSG_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 457 points\nMark variables: \n   uen entity_name entity_type_description entity_status_description date \naddress_type postal_code primary_ssic_code Year Month_num\nwindow: polygonal boundary\nenclosing rectangle: [2667.54, 55941.94] x [21448.47, 50256.33] units\n```\n\n\n:::\n:::\n\n\n\n#### IT\n\nA point is dropped outside the study area\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nITSG_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 1594 points\nMark variables: \n   uen entity_name entity_type_description entity_status_description date \naddress_type postal_code primary_ssic_code Year Month_num\nwindow: polygonal boundary\nenclosing rectangle: [2667.54, 55941.94] x [21448.47, 50256.33] units\n```\n\n\n:::\n:::\n\n\n:::\n\n## Spatial Point Pattern Analysis\n\n### Food and Beverages\n\nTo analyze the spatial distribution of F&B outlets, we start with the Clark-Evans test and Kernel Density Estimation (KDE) to identify overall clustering tendencies. These first-order analyses provide a general view of how outlets are distributed across the study area. We then apply second-order spatial point pattern analysis to examine clustering at both local and global scales, revealing more detailed patterns in F&B location strategies.\n\n#### First-Order SPPA\n\n##### Clark-Evan Test\n\nSince we have 594 points, we will use the Monte Carlo method for robustness.\n\nThe hypothesis and alpha value are as follows:\n\n**Null and Alternative Hypotheses:**\n\n-   H0 = The distribution of FNB businesses are randomly distributed (R=1)\n-   H1 = The distribution of FNB businesses are clustered (R\\<1)\n\n**Significance Level:** A 95% confidence level will be used (α = 0.05)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nclarkevans.test(FNBSG_ppp,\n                correction = \"none\",\n                clipregion = \"sg_owin\",\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim=99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  FNBSG_ppp\nR = 0.54567, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\nThe Clark-Evans test evaluates whether the spatial distribution of points—in this case, F&B outlets—is random, clustered, or regularly spaced. Here, the test was run using the Monte Carlo method with 99 simulations, no edge correction, and a 95% confidence level (α = 0.05).\n\nR = 0.5457: The Clark-Evans R value is less than 1, which indicates that the points are more clustered than would be expected under complete spatial randomness.\n\np-value = 0.01: Since the p-value is below 0.05, we reject the null hypothesis (H0) of random distribution in favor of the alternative hypothesis (H1) that the F&B businesses are clustered.\n\nConclusion: The analysis shows that F&B outlets in Singapore are not randomly distributed but tend to cluster in certain areas. This suggests that businesses strategically choose locations near existing F&B clusters, likely to capitalize on high customer traffic, accessibility, and complementary services.FNB establishments may tend to locate near one another, possibly due to shared preferences for high-footfall areas and commercial zones. :::\n\n##### Kernel Density Estimation\n\nAfter confirming the clustered pattern, let us apply the KDE method to visualize hotspots with high intensity.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFNBSG_ppp_km <- rescale.ppp(FNBSG_ppp, 1000, \"km\")\n\nkde_FNBSG_km_ppl <- density(FNBSG_ppp_km,\n        sigma = bw.ppl,\n        edge = TRUE,\n        kernel = \"gaussian\")\n\nkde_FNBSG_km_dg <- density(FNBSG_ppp_km,\n        sigma = bw.diggle,\n        edge = TRUE,\n        kernel = \"gaussian\")\n\nkde_FNBSG_km_ad <- adaptive.density(FNBSG_ppp_km, \n  method=\"kernel\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg=\"#f6f6f6\", mfrow = c(2,2))\nplot(kde_FNBSG_km_dg, main = \"bw.diggle\")\nplot(kde_FNBSG_km_ppl, main = \"bw.ppl\")\nplot(kde_FNBSG_km_ad, main = \"bw.adaptive\")\n# Convert ppp to data frame and plot\nFNBSG_points <- as.data.frame(FNBSG_ppp_km)\nplot(FNBSG_points$x, FNBSG_points$y, main = \"Original Points\", \n     cex = 0.5, pch = 16, xlab = \"x\", ylab = \"y\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-38-1.png){width=1152}\n:::\n:::\n\n\n::: callout-note\nThe KDE plots show high-density points in central regions like Downtown Core, Orchard, and Marina Bay. There are also secondary clusters in regional centers like Tampines and Jurong East.\n:::\n\n#### First Order SPPA at Planning Area\n\n##### Geospartial Data Wrangling\n\nWe first extract the study areas with high FNB concentration where The code first identifies the top three planning areas with the highest density of F&B businesses using st_join() and count(). It then extracts the corresponding spatial polygons for Downtown Core, Outram, and Geylang, and converts them into owin objects to define the study windows. F&B points within each planning area are subsetted from the main ppp object, and the points are rescaled from meters to kilometers for spatial analysis. Finally, the Clark-Evans test is applied separately to each area using Monte Carlo simulations to test whether F&B outlets are randomly distributed or clustered within the planning areas.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identify planning areas with highest FNB density\nfnb_by_area <- FNB_sf %>%\n  st_join(mppa_sf) %>%\n  st_drop_geometry() %>%\n  count(PLN_AREA_N, sort = TRUE) %>%\n  head(3)\n\ntop_areas <- fnb_by_area$PLN_AREA_N\ncat(\"Top 3 planning areas for FNB businesses:\", paste(top_areas, collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 3 planning areas for FNB businesses: GEYLANG, DOWNTOWN CORE, OUTRAM \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract these areas\nDC <- mppa_sf %>% filter(PLN_AREA_N == \"DOWNTOWN CORE\")\nOR <- mppa_sf %>% filter(PLN_AREA_N == \"OUTRAM\")\nTP <- mppa_sf %>% filter(PLN_AREA_N == \"GEYLANG\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nDC_owin = as.owin(DC)\nOR_owin = as.owin(OR)\nTP_owin = as.owin(TP)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nFNB_DC_ppp = FNB_ppp[DC_owin]\nFNB_OR_ppp = FNB_ppp[OR_owin]\nFNB_TP_ppp = FNB_ppp[TP_owin]\n```\n:::\n\n\n\nRescale ppp objects:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFNB_DC_ppp_km = rescale.ppp(FNB_DC_ppp, 1000, \"km\")\nFNB_OR_ppp_km = rescale.ppp(FNB_OR_ppp, 1000, \"km\")\nFNB_TP_ppp_km = rescale.ppp(FNB_TP_ppp, 1000, \"km\")\n```\n:::\n\n\n\n##### Clark-Evan Test by Planning Area\n\nNull and Alternative Hypotheses:\n\nH0 = The distribution of FNB businesses are randomly distributed (R=1)\n\nH1 = The distribution of FNB businesses are clustered (R\\<1)\n\nSignificance Level: A 95% confidence level will be used (α = 0.05)\n\n::: panel-tabset\nDowntown Core\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nclarkevans.test(FNB_DC_ppp,\n                correction = \"none\",\n                clipregion = \"DC_owin\",\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim=99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  FNB_DC_ppp\nR = 0.45684, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\nOutram\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nclarkevans.test(FNB_OR_ppp,\n                correction = \"none\",\n                clipregion = \"OR_owin\",\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim=99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  FNB_OR_ppp\nR = 0.75435, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\nGeylang\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nclarkevans.test(FNB_TP_ppp,\n                correction = \"none\",\n                clipregion = \"TP_owin\",\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim=99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  FNB_TP_ppp\nR = 0.80382, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n:::\n\n::: callout-note\nFor all three areas, the Clark-Evans R values are less than 1 (Downtown Core: 0.457, Outram: 0.754, Geylang: 0.804) with p-values of 0.01, indicating statistically significant clustering. This means F&B outlets in each of these top planning areas are not randomly distributed but tend to cluster together. The strongest clustering is observed in the Downtown Core, suggesting a high concentration of outlets, likely due to commercial activity and foot traffic, while clustering in Outram and Geylang is present but less pronounced.\n:::\n\n##### Kernel Density Estimation by Planning Area\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg=\"#f6f6f6\", mfrow=c(2,2))\n\nplot(density(FNB_DC_ppp_km,\n             title=\"A\",\n             sigma=bw.diggle, \n             edge=TRUE, \n             kernel=\"gaussian\"),\n     main=\"Downtown Core\")\n\nplot(density(FNB_OR_ppp_km, \n             sigma=bw.diggle, \n             edge=TRUE, \n             kernel=\"gaussian\"),\n     main=\"Outram\")\n\nplot(density(FNB_TP_ppp_km, \n             sigma=bw.diggle, \n             edge=TRUE, \n             kernel=\"gaussian\"),\n     main=\"Geylang\")\n\n# Combine all point patterns and plot using spatstat method\nFNB_all_ppp_km <- superimpose(FNB_DC_ppp_km, FNB_OR_ppp_km, FNB_TP_ppp_km)\nspatstat.geom::plot.ppp(FNB_all_ppp_km, main=\"All FNB Points\", cex=0.3, size=0.1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in default.charmap(ntypes, chars): Too many types to display every type\nas a different character\nWarning in default.charmap(ntypes, chars): Too many types to display every type\nas a different character\nWarning in default.charmap(ntypes, chars): Too many types to display every type\nas a different character\nWarning in default.charmap(ntypes, chars): Too many types to display every type\nas a different character\nWarning in default.charmap(ntypes, chars): Too many types to display every type\nas a different character\nWarning in default.charmap(ntypes, chars): Too many types to display every type\nas a different character\nWarning in default.charmap(ntypes, chars): Too many types to display every type\nas a different character\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Only 10 out of 169 symbols are shown in the symbol map\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in default.charmap(ntypes, chars): Too many types to display every type\nas a different character\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Only 10 out of 169 symbols are shown in the symbol map\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in default.charmap(ntypes, chars): Too many types to display every type\nas a different character\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Only 10 out of 101 symbols are shown in the symbol map\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Only 10 out of 12 symbols are shown in the symbol map\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-47-1.png){width=1152}\n:::\n:::\n\n\n\nThe KDE plots reveal distinct clustering patterns: Downtown Core shows multiple intense hotspots followed by Geylang and then Outram displays a more distributed.\n\n#### Second-Order SPPA at the Planning Area Level\n\n##### Downtown Core Planning Area\n\nCompute G-function estimation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_DC = Gest(FNB_DC_ppp, correction = \"border\")\npar(bg = \"#f6f6f6\")\nplot(G_DC, xlim=c(0,500), main=\"G-function: Downtown Core FNB\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n\n\nPerform CSR Test with G-function\n\nNull and Alternative Hypotheses:\n\n- H0 = The nearest neighbor distances of FNB businesses in Downtown Core are randomly distributed.\n- H1 = The nearest neighbor distances of FNB businesses in Downtown Core are not randomly distributed\n\nSignificance Level: A 95% confidence level will be used\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nG_DC.csr <- envelope(FNB_DC_ppp, Gest, rank=1, nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(G_DC.csr, main=\"G-function CSR Test: Downtown Core\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\n\n::: callout-note\nStatistical Conclusion\n\nThe spatial distribution of food and beverage outlets in Singapore’s Downtown Core significantly deviates from what would be expected under Complete Spatial Randomness (CSR). This is evident as the observed G-function consistently lies above both the theoretical CSR curve and the simulation envelope, which represents the expected range of variation under random placement. This upward deviation indicates statistically significant clustering, meaning outlets are located closer to one another than a random distribution would suggest. Such clustering is likely influenced by strategic urban planning, concentrated commercial demand, and high pedestrian traffic—factors typical of dense city centers that encourage co-location and competitive proximity.\n:::\n\n**Compute L-function estimation**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_DC = Lest(FNB_DC_ppp, correction = \"Ripley\")\npar(bg = \"#f6f6f6\")\nplot(L_DC, . -r ~ r, ylab= \"L(d)-r\", xlab = \"d(m)\", main=\"L-function: Downtown Core\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\n\nPerform CSR Test with L-function Null and Alternative Hypotheses:\n\n- H0 = The distribution of FNB businesses in Downtown Core are randomly distributed.\n- H1 = The distribution of FNB businesses in Downtown Core are not randomly distributed\n\nSignificance Level: A 95% confidence level will be used\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nL_DC.csr <- envelope(FNB_DC_ppp, Lest, nsim = 99, rank = 1, glocal=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(L_DC.csr, . - r ~ r, xlab=\"d\", ylab=\"L(d)-r\", main=\"L-function CSR Test: Downtown Core\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\nThe spatial pattern of outlets shows significant clustering, as the observed distribution consistently exceeds the bounds of what would be expected under complete spatial randomness. This suggests that businesses are strategically concentrated, likely influenced by commercial zoning, pedestrian traffic, and competitive proximity in the urban core.\n\n\n##### Geylang Planning Area\n\nCompute G-function estimation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_TP = Gest(FNB_TP_ppp, correction = \"border\")\npar(bg = \"#f6f6f6\")\nplot(G_TP, xlim=c(0,500), main=\"G-function: Geylang FNB\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\n\nPerform CSR Test with G-function\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nG_TP.csr <- envelope(FNB_TP_ppp, Gest, rank=1, nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(G_TP.csr, main=\"G-function CSR Test: Geylang\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\n\n\n**Compute L-function estimation**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_TP = Lest(FNB_TP_ppp, correction = \"Ripley\")\npar(bg = \"#f6f6f6\")\nplot(L_TP, . -r ~ r, ylab= \"L(d)-r\", xlab = \"d(m)\", main=\"L-function: Geylang\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\n\nPerform CSR Test with L-function\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nL_TP.csr <- envelope(FNB_TP_ppp, Lest, nsim = 99, rank = 1, glocal=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(L_TP.csr, . - r ~ r, xlab=\"d\", ylab=\"L(d)-r\", main=\"L-function CSR Test: Geylang\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n\n::: callout-note\nThe spatial pattern of outlets in Geylang exhibits significant clustering, as the observed distribution consistently exceeds the expected range under complete spatial randomness. This suggests that businesses are intentionally concentrated, likely influenced by local planning policies, consumer behavior, and shared infrastructure—factors that promote proximity and commercial synergy in suburban retail environments\n:::\n\n#### Findings\n\nThe spatial analysis reveals that Food and Beverage (FNB) businesses in Singapore exhibit strong clustering patterns at multiple scales:\n\nGlobal Level:\nThere is clear evidence of significant clustering across Singapore, indicating that FNB outlets are not randomly distributed but tend to concentrate in commercially active zones.\n\nRegional Level:\nAll three major planning areas show distinct clustering characteristics:\n\n- Downtown Core:\nDisplays intensive micro-clustering, especially in the Central Business District, where outlets are tightly packed within short distances—likely driven by high pedestrian volumes and dense commercial zoning.\n\n- Outram:\nShows distributed clustering along major shopping belts, suggesting a linear agglomeration pattern aligned with retail corridors and tourist footfall.\n\n- Geylang:\nExhibits a single dominant cluster centered around the regional hub, reflecting suburban planning that concentrates amenities in one core location.\n\nSpatial Scales:\nClustering is most pronounced at distances of 50–200 meters, highlighting that FNB businesses tend to agglomerate within walking distance. This proximity likely enhances visibility, shared customer traffic, and access to complementary services such as transport, retail, and entertainment.\n\nStrategic Implications:\nThe consistent clustering across diverse urban typologies suggests that agglomeration economies—benefits gained from being near other businesses—play a pivotal role in location decisions. Rather than dispersing evenly, FNB outlets prefer to anchor themselves in established commercial nodes, reinforcing the importance of spatial strategy in retail planning and urban development.\n\n\n### Retail\n\nOur interest in Retail Trade entities (supermarkets, general retail outlets) is to examine whether these stores maintain clustered distributions in Singapore's urban landscape over time. To achieve this, we will implement STKDE and Clark-Evans test for 1st-order SPPA, followed by G-function and L-function analysis for second-order insights.\n\n#### Distribution by Month\n\nThe code below plots the distribution of newly registered retail entities by month:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa_union <- mppa_sf %>%\n  st_union() \n  \ntm_shape(mppa_union) +\n  tm_polygons() +\n  tm_shape(retail_sf) +\n  tm_dots(size = 0.2, shape = 16) +\n  tm_title(\"Retail Trade Entity Monthly Distribution\",\n           position = tm_pos_out(cell.h = \"center\",\n                                 cell.v = \"top\",\n                                 pos.h = \"center\")) + \n  tm_facets(nrow = 2, ncol = 3,\n            by = \"Month_num\",\n            free.coords = FALSE) + \n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\",\n            panel.label.bg.color = \"#AFCD6F\",\n            inner.margins = c(0, 0.05, 0.2, 0.05)) # bottom, left, top, right\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\n\n#### First-Order SPPA\n\nGeospatial Data Wrangling Extract points by month We first need to extract the \"month\" value from the registration dates:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nretail_sf <- retail_sf %>%\n  mutate(Month_no = month(date))\n\nretail_m <- retail_sf %>%\n  select(Month_no) \n\nkable(head(retail_m))\n```\n\n::: {.cell-output-display}\n\n\n| Month_no|geometry                  |\n|--------:|:-------------------------|\n|        1|POINT (32829.61 36781.03) |\n|        1|POINT (27808.56 45289.08) |\n|        1|POINT (28071.64 31871.17) |\n|        1|POINT (36343.66 41287.07) |\n|        4|POINT (22308.9 35972.96)  |\n|        1|POINT (31204.28 32179.87) |\n\n\n:::\n:::\n\n\n\nCreate ppp Object Next, convert the sf object to ppp format and apply rjitter() to slightly jitter points that share the same coordinates:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nretail_m_ppp <- as.ppp(retail_m) %>%\n  rjitter(retry = TRUE, nsim = 1, drop = TRUE)\n\nretail_m_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 457 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [4670.11, 45154.27] x [27393.65, 49401.78] units\n```\n\n\n:::\n:::\n\n\n\nCheck if there are any duplicates:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(duplicated(retail_m_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\nCreate owin Object\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nretail_m_ppp <- retail_m_ppp[sg_owin]\nsummary(retail_m_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  457 points\nAverage intensity 8.194519e-07 points per square unit\n\nCoordinates are given to 12 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   2.000   4.000   3.615   5.000   6.000 \n\nWindow: polygonal boundary\n28 separate polygons (22 holes)\n                  vertices         area relative.area\npolygon 1              285  1.61128e+06      2.89e-03\npolygon 2 (hole)        41 -4.01660e+04     -7.20e-05\npolygon 3 (hole)       317 -5.11280e+04     -9.17e-05\npolygon 4 (hole)         3 -4.14100e-04     -7.43e-13\npolygon 5 (hole)         4 -2.86396e-01     -5.14e-10\npolygon 6 (hole)         3 -1.81439e-04     -3.25e-13\npolygon 7 (hole)         3 -8.68789e-04     -1.56e-12\npolygon 8 (hole)         3 -5.99531e-04     -1.08e-12\npolygon 9 (hole)         3 -3.04560e-04     -5.46e-13\npolygon 10 (hole)        5 -2.44408e-04     -4.38e-13\npolygon 11 (hole)        5 -3.64686e-02     -6.54e-11\npolygon 12              71  8.18750e+03      1.47e-05\npolygon 13 (hole)       38 -7.79904e+03     -1.40e-05\npolygon 14              91  1.49663e+04      2.68e-05\npolygon 15              71  5.63061e+03      1.01e-05\npolygon 16              10  1.99717e+02      3.58e-07\npolygon 17 (hole)        3 -4.46108e-04     -8.00e-13\npolygon 18 (hole)        3 -3.39815e-04     -6.09e-13\npolygon 19 (hole)        3 -4.52041e-05     -8.11e-14\npolygon 20 (hole)        3 -3.90173e-05     -7.00e-14\npolygon 21 (hole)        3 -9.59845e-05     -1.72e-13\npolygon 22 (hole)        8 -4.28707e-01     -7.69e-10\npolygon 23 (hole)        4 -2.18619e-04     -3.92e-13\npolygon 24 (hole)      779 -3.71587e+07     -6.66e-02\npolygon 25 (hole)        6 -8.37554e-01     -1.50e-09\npolygon 26 (hole)        5 -2.92235e-04     -5.24e-13\npolygon 27           11981  5.93307e+08      1.06e+00\npolygon 28 (hole)        3 -7.43616e-06     -1.33e-14\nenclosing rectangle: [2667.54, 55941.94] x [21448.47, 50256.33] units\n                     (53270 x 28810 units)\nWindow area = 557690000 square units\nFraction of frame area: 0.363\n```\n\n\n:::\n:::\n\n\n\nAll data points remain within the study area.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(retail_m_ppp, main = \"Retail Business Entities Registered by Month\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n:::\n\n\n\n#### Compute Spatial-temporal KDE\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nretail_m_ppp_km <- rescale.ppp(retail_m_ppp, 1000, \"km\")\nst_kde <- spattemp.density(retail_m_ppp_km)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCalculating trivariate smooth...Done.\nEdge-correcting...Done.\nConditioning on time...Done.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\", mfcol = c(2,3))\nfor(i in 1:6) { \n  plot(st_kde, i, \n       override.par = FALSE, \n       fix.range = TRUE, \n       main = paste(\"Retail KDE at month\", i))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-67-1.png){width=1152}\n:::\n:::\n\n\n\nFrom January to May, the density intensity in the Central region is noticeably higher than in other regions. However, in June, the density appears to be more evenly distributed across the entire study area, suggesting potential seasonal variations in retail establishment patterns.\n\n**Clark-Evans Test** The hypothesis and alpha value are as follows:\n\nNull and Alternative Hypotheses:\n\nH0 = The distribution of retail businesses are randomly distributed (R=1)\n\nH1 = The distribution of retail businesses are clustered (R\\<1)\n\nSignificance Level: A 95% confidence level will be used (α = 0.05)\n\nThe code below performs Clark-Evans Test for SPPA from January to June:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (m in 1:6) {\n  cat(\"Running Clark-Evans test for month\", m, \"\\n\")\n  \n  # Subset by mark directly\n  month_ppp <- retail_m_ppp[marks(retail_m_ppp) == m]\n  \n  result <- clarkevans.test(month_ppp,\n                            correction = \"none\",\n                            alternative = \"clustered\",\n                            method = \"MonteCarlo\",\n                            nsim = 99)\n  \n  print(result)\n  cat(\"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning Clark-Evans test for month 1 \n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  month_ppp\nR = 0.77074, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n\n\nRunning Clark-Evans test for month 2 \n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  month_ppp\nR = 0.61375, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n\n\nRunning Clark-Evans test for month 3 \n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  month_ppp\nR = 0.75845, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n\n\nRunning Clark-Evans test for month 4 \n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  month_ppp\nR = 0.66984, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n\n\nRunning Clark-Evans test for month 5 \n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  month_ppp\nR = 0.67301, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n\n\nRunning Clark-Evans test for month 6 \n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  month_ppp\nR = 0.71312, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\nResult Interpretation The tests consistently show R values less than 1 with p-values below 0.05 for each month, suggesting significant spatial clustering of retail trade entities within Singapore throughout the first half of 2025. This indicates that retail establishments consistently prefer clustered locations rather than random distribution patterns.\n:::\n\n#### Second-Order SPPA\n\nPerform CSR Tests with G-function Null and Alternative Hypotheses:\n\nH0 = The nearest neighbor distances of retail trade entities in Singapore are randomly distributed.\n\nH1 = The nearest neighbor distances of retail trade entities in Singapore are not randomly distributed\n\nSignificance Level: A 95% confidence level will be used (α = 0.05)\n\nMonte Carlo test with G-function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\npar(bg = \"#f6f6f6\", mfcol = c(2,3))\nfor (m in 1:6) {\n  cat(\"Month:\", m, \"\\n\")\n  \n  month_ppp <- retail_m_ppp[marks(retail_m_ppp) == m]\n  \n  # G-function envelope\n  G.csr <- envelope(month_ppp, Gest, rank = 1, nsim = 99)\n  plot(G.csr, main = paste(\"G-function - Month\", m))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 1 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 2 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 3 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 4 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 5 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 6 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-69-1.png){width=1152}\n:::\n:::\n\n\n\n::: callout-note\nThe six-month G-function analysis shows stable and significant clustering of food and beverage outlets, especially at short distances. This persistent pattern suggests strategic co-location near high-traffic areas like transport hubs and retail centers, rather than seasonal variation. The consistency over time highlights the influence of agglomeration economies in guiding FNB location choices across Singapore.\n\n:::\n\nPerform CSR Tests with L-function Null and Alternative Hypotheses:\n\nH0 = The distribution of retail trade entities in Singapore are randomly distributed.\n\nH1 = The distribution of retail trade entities in Singapore are not randomly distributed\n\nSignificance Level: A 95% confidence level will be used (α = 0.05)\n\nMonte Carlo test with L-function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\npar(bg = \"#f6f6f6\", mfcol = c(2,3))\nfor (m in 1:6) {\n  cat(\"Month:\", m, \"\\n\")\n  \n  month_ppp <- retail_m_ppp[marks(retail_m_ppp) == m]\n  \n  # L-function envelope\n  L.csr <- envelope(month_ppp, Lest, nsim = 99, rank = 1, glocal = TRUE)\n  plot(L.csr, . - r ~ r, xlab = \"d\", ylab = \"L(d)-r\", main = paste(\"L-function - Month\", m))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 1 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 2 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 3 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5,  [3:09 remaining] 6,\n [3:10 remaining] 7,  [3:17 remaining] 8,  [3:06 remaining] 9,\n [2:58 remaining] 10,  [2:52 remaining] 11,  [2:50 remaining] 12,\n [2:45 remaining] 13,  [2:46 remaining] 14,  [2:40 remaining] 15,\n [2:38 remaining] 16,  [2:33 remaining] 17,  [2:32 remaining] 18,\n [2:30 remaining] 19,  [2:26 remaining] 20,  [2:23 remaining] 21,\n [2:21 remaining] 22,  [2:23 remaining] 23,  [2:23 remaining] 24,\n [2:21 remaining] 25,  [2:18 remaining] 26,  [2:15 remaining] 27,\n [2:12 remaining] 28,  [2:15 remaining] 29,  [2:13 remaining] 30,\n [2:10 remaining] 31,  [2:06 remaining] 32,  [2:03 remaining] 33,\n [2:00 remaining] 34,  [1:57 remaining] 35,  [1:54 remaining] 36,\n [1:52 remaining] 37,  [1:49 remaining] 38,  [1:47 remaining] 39,\n [1:48 remaining] 40,  [1:47 remaining] 41,  [1:44 remaining] 42,\n [1:41 remaining] 43,  [1:41 remaining] 44,  [1:38 remaining] 45,\n [1:36 remaining] 46,  [1:34 remaining] 47,  [1:31 remaining] 48,\n [1:29 remaining] 49,  [1:26 remaining] 50,  [1:24 remaining] 51,\n [1:22 remaining] 52,  [1:20 remaining] 53,  [1:18 remaining] 54,\n [1:16 remaining] 55,  [1:13 remaining] 56,  [1:11 remaining] 57,\n [1:09 remaining] 58,  [1:08 remaining] 59,  [1:06 remaining] 60,\n [1:04 remaining] 61,  [1:02 remaining] 62,  [1:00 remaining] 63,\n [58 sec remaining] 64,  [57 sec remaining] 65,  [55 sec remaining] 66,\n [53 sec remaining] 67,  [51 sec remaining] 68,  [50 sec remaining] 69,\n [48 sec remaining] 70,  [46 sec remaining] 71,  [44 sec remaining] 72,\n [42 sec remaining] 73,  [41 sec remaining] 74,  [39 sec remaining] 75,\n [37 sec remaining] 76,  [36 sec remaining] 77,  [34 sec remaining] 78,\n [32 sec remaining] 79,  [31 sec remaining] 80,  [29 sec remaining] 81,\n [27 sec remaining] 82,  [26 sec remaining] 83,  [24 sec remaining] 84,\n [23 sec remaining] 85,  [21 sec remaining] 86,  [20 sec remaining] 87,\n [18 sec remaining] 88,  [17 sec remaining] 89,  [15 sec remaining] 90,\n [13 sec remaining] 91,  [12 sec remaining] 92,  [10 sec remaining] 93,\n [9 sec remaining] 94,  [7 sec remaining] 95,  [6 sec remaining] 96,\n [4 sec remaining] 97,  [3 sec remaining] 98,  [1 sec remaining] \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 4 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 5 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonth: 6 \nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-70-1.png){width=1152}\n:::\n:::\n\n\n\n::: callout-note\nThese six monthly L-function plots show how spatial relationships among entities evolve over time. Each plot includes multiple curves and shaded regions, indicating variability and confidence intervals across different simulations or subgroups. The logarithmic scale suggests a focus on capturing wide-ranging spatial effects, especially at larger distances. Some months show rising trends, hinting at increasing clustering or interaction strength, while others remain stable. Overall, the plots suggest dynamic but consistently structured spatial behavior across months, possibly reflecting persistent locational strategies or external influences like urban planning.\n:::\n\n\n#### Findings \n\nThe retail trade sector in Singapore demonstrates remarkable spatial stability and strategic clustering throughout the first half of 2025. Analysis reveals that retail establishments maintain consistent clustering patterns across all six months, with Clark-Evans R values consistently ranging between 0.61-0.78, all statistically significant (p < 0.05). This temporal consistency indicates that retail location decisions are driven by long-term strategic factors rather than short-term market fluctuations. The sector exhibits a clear hierarchical spatial organization, with primary clusters concentrated in the Central Region's established shopping districts and secondary clusters emerging in regional centers like Tampines and Jurong East, supporting Singapore's polycentric development model. Retail businesses show strong preference for locations near transportation nodes and in mixed-use developments, optimizing for pedestrian accessibility and shared customer traffic.\n\nRetail businesses maintain stable, statistically significant clustering patterns (R = 0.61-0.78) across all six months, demonstrating strategic co-location behavior focused on transportation nodes and established commercial corridors, with a clear hierarchical distribution from central business districts to regional centers.\n\n\n\n### Information Technology\n\n#### Geospatial Data Wrangling\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter IT data points within Downtown Core\nIT_DC_ppp = IT_ppp[DC_owin]\nIT_DC_ppp_km = rescale.ppp(IT_DC_ppp, 1000, \"km\")\n\n# Filter IT data points outside Downtown Core\nnon_dc <- mppa_sf %>% \n  filter(PLN_AREA_N != \"DOWNTOWN CORE\")\n\nnon_dc_owin = as.owin(non_dc)\nIT_non_DC_ppp = IT_ppp[non_dc_owin]\nIT_non_DC_ppp_km = rescale.ppp(IT_non_DC_ppp, 1000, \"km\")\n```\n:::\n\n\n\n#### First-Order SPPA Clark–Evans Test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\n# Downtown Core\nclarkevans.test(IT_DC_ppp,\n                correction = \"none\",\n                clipregion = \"DC_owin\",\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  IT_DC_ppp\nR = 0.31837, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n\n```{.r .cell-code}\n# Outside Downtown Core\nclarkevans.test(IT_non_DC_ppp,\n                correction = \"none\",\n                clipregion = \"non_dc_owin\",\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  IT_non_DC_ppp\nR = 0.39649, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\n**Downtown Core:**\nThe test statistic R = 0.31837 is well below 1, and the p-value of 0.01 confirms that the observed pattern is significantly more clustered than expected under complete spatial randomness (CSR). This suggests that IT businesses in the CBD are tightly packed—likely due to proximity to financial institutions, talent pools, and infrastructure.\n\n**Outside Downtown Core:**\nThe test statistic R = 0.39636 also falls below 1 with a p-value of 0.01, indicating statistically significant clustering in suburban or peripheral areas. While less intense than in the CBD, this still reflects a tendency for IT firms to co-locate near regional hubs or innovation corridors.\n\n#### Kernel Density Estimation (KDE)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg=\"#f6f6f6\", mfrow=c(2,2))\nplot(density(IT_DC_ppp_km, \n             sigma=bw.diggle, \n             edge=TRUE, \n             kernel=\"gaussian\"),\n     main=\"IT Entities - Downtown Core (Diggle)\")\nplot(density(IT_non_DC_ppp_km, \n             sigma=bw.diggle, \n             edge=TRUE, \n             kernel=\"gaussian\"),\n     main=\"IT Entities - Outside Downtown Core (Diggle)\")\nplot(density(IT_DC_ppp_km, \n             sigma=bw.ppl, \n             edge=TRUE, \n             kernel=\"gaussian\"),\n     main=\"IT Entities - Downtown Core (PPL)\")\nplot(density(IT_non_DC_ppp_km, \n             sigma=bw.ppl, \n             edge=TRUE, \n             kernel=\"gaussian\"),\n     main=\"IT Entities - Outside Downtown Core (PPL)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-73-1.png){width=1152}\n:::\n:::\n\n\n::: callout-note\nInterpretation: Look for hotspots in the CBD vs outside. High intensity in CBD would indicate tech hubs like Raffles Place, Marina Bay, One-North.\n:::\n\n#### Second-Order SPPA G-function\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Downtown Core\nG_DC_IT = Gest(IT_DC_ppp, correction = \"border\")\npar(bg=\"#f6f6f6\")\nplot(G_DC_IT, xlim=c(0,500))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-74-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Outside Downtown Core\nG_n_DC_IT = Gest(IT_non_DC_ppp, correction = \"border\")\npar(bg=\"#f6f6f6\")\nplot(G_n_DC_IT, xlim=c(0,500))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-74-2.png){width=672}\n:::\n:::\n\n\n\n::: callout-note\nThis plot compares the observed spatial distribution of IT businesses in the Downtown Core to a theoretical random pattern. The black curve rises more steeply than the red dashed line, especially at shorter distances, indicating that businesses are located closer together than expected under complete spatial randomness. This suggests significant clustering, likely driven by proximity to infrastructure, talent, and commercial demand. The pattern reflects strategic co-location behavior typical of high-density urban tech ecosystems.\n:::\n\n**CSR Test with G-function**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\nG_DC_IT.csr <- envelope(IT_DC_ppp, Gest, rank = 1, nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(G_DC_IT.csr)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-75-1.png){width=672}\n:::\n\n```{.r .cell-code}\nG_n_DC_IT.csr <- envelope(IT_non_DC_ppp, Gest, rank = 1, nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(G_n_DC_IT.csr)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-75-2.png){width=672}\n:::\n:::\n\n\n\n::: callout-note\nThis plot visually tests whether the spatial distribution of IT businesses in the Downtown Core deviates from complete spatial randomness. The solid black curve represents the actual observed pattern, while the dashed red line shows the theoretical expectation under randomness. The shaded gray region and accompanying curves define a simulation envelope—essentially a confidence band based on randomized scenarios. Since the observed curve lies above both the theoretical line and the envelope at shorter distances, it indicates statistically significant clustering. This suggests that IT firms tend to locate close to one another, likely to leverage shared infrastructure, talent pools, and business synergies typical of high-density urban tech zones.\n:::\n\n\n**L-function**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple L-function calculation (fast)\nL_DC_IT = Lest(IT_DC_ppp, correction = \"border\")  # Use 'border' for faster computation\nL_n_DC_IT = Lest(IT_non_DC_ppp, correction = \"border\")\n\n# Plot both side by side\npar(mfrow = c(1,2), bg = \"#f6f6f6\")\nplot(L_DC_IT, . - r ~ r, ylab = \"L(d)-r\", xlab = \"d(m)\", main = \"IT - Downtown Core\")\nplot(L_n_DC_IT, . - r ~ r, ylab = \"L(d)-r\", xlab = \"d(m)\", main = \"IT - Outside Downtown Core\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-76-1.png){width=672}\n:::\n:::\n\n\nThese side-by-side plots compare spatial clustering of IT businesses inside and outside Singapore’s Downtown Core. In both areas, the observed curves rise above the baseline at short distances, indicating strong clustering. However, the Downtown Core shows a more moderate peak around 200 meters, while areas outside the core exhibit sharper clustering followed by noticeable dispersion at longer distances. This suggests that IT firms in suburban zones concentrate tightly near regional hubs but spread out beyond them, whereas those in the CBD maintain more uniform proximity. The contrast reflects differing urban layouts and planning strategies across regions.\n\n\n\n**CSR Test with L-function + Interactive Plot**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\n#| label: it-csr-interactive-optimized\n#| warning: false\n#| message: false\n\nset.seed(1234)\n\n# Use Monte Carlo envelopes with nsim > 1 (minimum 2, typically 39 or 99)\nL_DC_IT.mc <- envelope(IT_DC_ppp, Lest, nsim = 39, correction = \"border\")  # Changed nsim to 39\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nL_n_DC_IT.mc <- envelope(IT_non_DC_ppp, Lest, nsim = 39, correction = \"border\")  # Changed nsim to 39\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 39 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot Monte Carlo envelopes\npar(mfrow = c(1,2), bg = \"#f6f6f6\")\nplot(L_DC_IT.mc, . - r ~ r, main = \"IT - Downtown Core (Monte Carlo CSR)\")\nplot(L_n_DC_IT.mc, . - r ~ r, main = \"IT - Outside Downtown Core (Monte Carlo CSR)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-77-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Create interactive plot using Monte Carlo results\nlibrary(plotly)\n\n# Use the Monte Carlo envelope object\nL_df <- as.data.frame(L_n_DC_IT.mc)  # Make sure this matches the object name above\n\n# Create interactive plot with confidence envelopes\ninteractive_plot <- plot_ly(L_df, x = ~r) %>%\n  add_lines(y = ~(obs - r), name = \"Observed\", \n            line = list(color = \"#4D4D4D\", width = 2)) %>%\n  add_lines(y = ~(theo - r), name = \"Theoretical (CSR)\", \n            line = list(color = \"red\", width = 2, dash = \"dash\")) %>%\n  add_ribbons(ymin = ~(lo - r), ymax = ~(hi - r), name = \"95% CI\",\n              line = list(color = \"lightblue\"), \n              fillcolor = \"rgba(173,216,230,0.3)\") %>%\n  layout(title = \"IT Businesses: L-function Analysis (Outside Downtown Core)\",\n         xaxis = list(title = \"Distance r (meters)\"),\n         yaxis = list(title = \"L(r) - r\"),\n         legend = list(x = 0.1, y = 0.9))\n\ninteractive_plot\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-58d3298300c8b5754b05\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-58d3298300c8b5754b05\">{\"x\":{\"visdat\":{\"1da4608d7b8e\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"1da4608d7b8e\",\"attrs\":{\"1da4608d7b8e\":{\"x\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"y\":{},\"type\":\"scatter\",\"mode\":\"lines\",\"name\":\"Observed\",\"line\":{\"color\":\"#4D4D4D\",\"width\":2},\"inherit\":true},\"1da4608d7b8e.1\":{\"x\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"y\":{},\"type\":\"scatter\",\"mode\":\"lines\",\"name\":\"Theoretical (CSR)\",\"line\":{\"color\":\"red\",\"width\":2,\"dash\":\"dash\"},\"inherit\":true},\"1da4608d7b8e.2\":{\"x\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"ymin\":{},\"ymax\":{},\"type\":\"scatter\",\"mode\":\"lines\",\"hoveron\":\"points\",\"fill\":\"toself\",\"name\":\"95% CI\",\"line\":{\"color\":\"lightblue\"},\"fillcolor\":\"rgba(173,216,230,0.3)\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"IT Businesses: L-function Analysis (Outside Downtown Core)\",\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Distance r (meters)\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"L(r) - r\"},\"legend\":{\"x\":0.10000000000000001,\"y\":0.90000000000000002},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0,14.066338281447399,28.132676562894797,42.199014844342194,56.265353125789595,70.331691407236988,84.398029688684389,98.464367970131789,112.53070625157919,126.59704453302659,140.66338281447398,154.72972109592138,168.79605937736878,182.86239765881618,196.92873594026358,210.99507422171098,225.06141250315838,239.12775078460578,253.19408906605318,267.26042734750058,281.32676562894795,295.39310391039538,309.45944219184275,323.52578047329018,337.59211875473756,351.65845703618498,365.72479531763236,379.79113359907979,393.85747188052716,407.92381016197459,421.99014844342196,436.05648672486939,450.12282500631676,464.18916328776413,478.25550156921156,492.32183985065893,506.38817813210636,520.45451641355373,534.52085469500116,548.58719297644859,562.65353125789591,576.71986953934334,590.78620782079076,604.85254610223819,618.91888438368551,632.98522266513294,647.05156094658037,661.1178992280278,675.18423750947511,689.25057579092254,703.31691407236997,717.38325235381728,731.44959063526471,745.51592891671214,759.58226719815957,773.64860547960689,787.71494376105431,801.78128204250174,815.84762032394917,829.91395860539649,843.98029688684392,858.04663516829135,872.11297344973877,886.17931173118609,900.24565001263352,914.31198829408095,928.37832657552826,942.44466485697569,956.51100313842312,970.57734141987055,984.64367970131786,998.71001798276529,1012.7763562642127,1026.8426945456602,1040.9090328271075,1054.975371108555,1069.0417093900023,1083.1080476714496,1097.1743859528972,1111.2407242343445,1125.3070625157918,1139.3734007972394,1153.4397390786867,1167.506077360134,1181.5724156415815,1195.6387539230288,1209.7050922044764,1223.7714304859237,1237.837768767371,1251.9041070488186,1265.9704453302659,1280.0367836117132,1294.1031218931607,1308.169460174608,1322.2357984560556,1336.3021367375029,1350.3684750189502,1364.4348133003978,1378.5011515818451,1392.5674898632924,1406.6338281447399,1420.7001664261873,1434.7665047076346,1448.8328429890821,1462.8991812705294,1476.965519551977,1491.0318578334243,1505.0981961148716,1519.1645343963191,1533.2308726777665,1547.2972109592138,1561.3635492406613,1575.4298875221086,1589.4962258035559,1603.5625640850035,1617.6289023664508,1631.6952406478983,1645.7615789293457,1659.827917210793,1673.8942554922405,1687.9605937736878,1702.0269320551351,1716.0932703365827,1730.15960861803,1744.2259468994775,1758.2922851809249,1772.3586234623722,1786.4249617438197,1800.491300025267,1814.5576383067144,1828.6239765881619,1842.6903148696092,1856.7566531510565,1870.8229914325041,1884.8893297139514,1898.9556679953989,1913.0220062768462,1927.0883445582936,1941.1546828397411,1955.2210211211884,1969.2873594026357,1983.3536976840833,1997.4200359655306,2011.4863742469781,2025.5527125284254,2039.6190508098728,2053.6853890913203,2067.7517273727676,2081.8180656542149,2095.8844039356622,2109.95074221711,2124.0170804985573,2138.0834187800046,2152.149757061452,2166.2160953428993,2180.2824336243466,2194.3487719057944,2208.4151101872417,2222.481448468689,2236.5477867501363,2250.6141250315836,2264.6804633130314,2278.7468015944787,2292.813139875926,2306.8794781573733,2320.9458164388207,2335.012154720268,2349.0784930017157,2363.1448312831631,2377.2111695646104,2391.2775078460577,2405.343846127505,2419.4101844089528,2433.4765226904001,2447.5428609718474,2461.6091992532947,2475.675537534742,2489.7418758161893,2503.8082140976371,2517.8745523790844,2531.9408906605317,2546.0072289419791,2560.0735672234264,2574.1399055048742,2588.2062437863215,2602.2725820677688,2616.3389203492161,2630.4052586306634,2644.4715969121112,2658.5379351935585,2672.6042734750058,2686.6706117564531,2700.7369500379004,2714.8032883193478,2728.8696266007955,2742.9359648822428,2757.0023031636902,2771.0686414451375,2785.1349797265848,2799.2013180080326,2813.2676562894799,2827.3339945709272,2841.4003328523745,2855.4666711338218,2869.5330094152691,2883.5993476967169,2897.6656859781642,2911.7320242596115,2925.7983625410589,2939.8647008225062,2953.9310391039539,2967.9973773854013,2982.0637156668486,2996.1300539482959,3010.1963922297432,3024.2627305111905,3038.3290687926383,3052.3954070740856,3066.4617453555329,3080.5280836369802,3094.5944219184275,3108.6607601998753,3122.7270984813226,3136.7934367627699,3150.8597750442173,3164.9261133256646,3178.9924516071119,3193.0587898885597,3207.125128170007,3221.1914664514543,3235.2578047329016,3249.3241430143489,3263.3904812957967,3277.456819577244,3291.5231578586913,3305.5894961401386,3319.655834421586,3333.7221727030337,3347.788510984481,3361.8548492659284,3375.9211875473757,3389.987525828823,3404.0538641102703,3418.1202023917181,3432.1865406731654,3446.2528789546127,3460.31921723606,3474.3855555175073,3488.4518937989551,3502.5182320804024,3516.5845703618497,3530.650908643297,3544.7172469247444,3558.7835852061917,3572.8499234876394,3586.9162617690868,3600.9826000505341,3615.0489383319814,3629.1152766134287,3643.1816148948765,3657.2479531763238,3671.3142914577711,3685.3806297392184,3699.4469680206657,3713.5133063021131,3727.5796445835608,3741.6459828650081,3755.7123211464555,3769.7786594279028,3783.8449977093501,3797.9113359907979,3811.9776742722452,3826.0440125536925,3840.1103508351398,3854.1766891165871,3868.2430273980344,3882.3093656794822,3896.3757039609295],\"y\":[0,604.59918304334292,1090.6126110245634,1461.1591697235951,1729.7789475148584,1883.2390229841931,1934.5323275415794,1914.3160810373647,1908.011184081427,1903.4449296668604,1902.7560209346989,1902.5081574399383,1904.879615114598,1903.7881871687748,1906.0750415656669,1906.666090390816,1904.2456472866338,1896.4621671257237,1888.9089587746892,1879.6237195010719,1872.4411041583187,1865.7532907002806,1857.5094268372159,1852.129917789217,1846.0781157126733,1839.447881772084,1830.4036862703128,1826.0988798105086,1824.23463579606,1825.576798319041,1830.5761281780212,1843.3047850900002,1857.8634957301533,1869.596042764611,1880.9185177308559,1886.4931876100788,1891.571399178936,1892.6432473375362,1889.2179167637282,1881.2382011795694,1872.471490731225,1869.4703904162354,1864.6813983586912,1859.5090491465771,1854.5526191581152,1851.5180152651078,1851.3242467451653,1846.0881271127328,1844.1962835585341,1844.3173052119182,1846.8348859918874,1847.4783714089272,1847.4146379319561,1853.2819485816412,1858.127756009048,1864.5412179228038,1868.2793502859631,1874.5913718816939,1880.3881206469487,1880.0262579944351,1879.8551467728607,1880.7889608540695,1880.3346776999722,1886.6646205918807,1893.2355718398312,1901.883877494397,1905.5135175651826,1910.5923011296031,1918.1117522576571,1922.010627748256,1931.0931423221905,1929.4847188399626,1934.4873056456872,1935.1644512029204,1932.2988560983156,1932.8199853052665,1933.6012492957939,1936.7541151883443,1939.7960035268145,1939.1447091557623,1942.4946633661305,1950.6707398876802,1963.3329950809753,1978.6853385967088,1995.9542135163081,2009.5196885391335,2022.0098341124381,2036.481208162555,2046.3537411379943,2062.026493944978,2067.8683208260827,2075.5980968045378,2084.4694967227997,2096.9651639953768,2103.4013950457656,2105.505403690915,2106.5861268188883,2107.5133496941539,2108.7729078643092,2110.6984512346835,2108.0664536922704,2110.6011295318858,2114.9484338459752,2124.0161883524079,2130.7360202753903,2142.8608696430047,2152.9838593787945,2168.7298919221303,2184.6031458813013,2203.7503799633168,2244.0835020895056,2272.6335691802587,2300.111444816419,2331.2838817043012,2342.407749664952,2359.1202993512206,2370.8508482814441,2377.6043314114177,2386.1399250984268,2383.9163634441038,2392.9417913164434,2397.4791736786747,2407.327524699509,2413.6576414375713,2422.0584835190334,2434.4535863144642,2440.2092739583763,2442.3559195675634,2440.4715423162124,2464.3580898893042,2457.8963982251635,2442.0588965275956,2415.1218860449626,2412.6692019732627,2418.8253391401813,2417.205672715389,2422.8596261854877,2420.525358996048,2423.8607371303042,2429.2971000266398,2441.3893055614953,2443.0380101723276,2459.5344618699273,2477.4036789908005,2456.4914248199884,2455.8788606752487,2466.097372125168,2480.3795071285044,2506.9848726816131,2514.3775406422196,2535.8963933229925,2563.9756532342453,2581.1135665584043,2604.6442584316073,2606.7201787446602,2617.7939628853883,2628.0783083568308,2630.8618231986015,2640.2549694017212,2634.9343591350412,2630.3048593251892,2633.1299620559284,2632.0626407302861,2633.7730476314891,2622.2606842792829,2616.6161114566439,2619.7319788383156,2624.3789921260955,2634.9346014168409,2627.5830318300882,2628.6636951707701,2645.6500872289057,2653.2333891541748,2666.1708192762562,2652.0673661118281,2668.3556943667563,2666.7560091720652,2644.3396678631498,2633.339884826089,2623.297539819187,2600.5875935936415,2593.4698086669291,2608.2388697303909,2608.5092839122599,2610.8939662965831,2612.019937672263,2613.2612956540897,2622.7743708257613,2505.8563449519129,2298.7409307886833,1981.1453695946025,1600.1207419942771,1015.8722673088669,239.72049179100986,180.13747577772483,182.94926767078141,187.67145708520638,192.69317976902721,206.43761280009676,177.83710189788962,165.28161873505223,155.23438120920264,148.81869334255498,150.33545349060478,148.79623391424775,135.76255434504583,119.69090675786811,129.95074613101633,102.8437996038615,100.62768996106297,100.15122014947428,61.518470743448233,55.70798186510774,52.173024986835117,49.657694102224013,43.22954565381724,36.782424961940706,36.239260124807515,32.144945968904267,24.199318227542335,31.070507072289274,37.841119812620946,29.750908808289296,22.665902091814587,22.005592682565293,28.908393705110484,34.609543290804595,53.947415912814449,-7.6408463507764282,-26.200965260689372,-37.170729492334431,-74.24694834224556,-76.989797090935099,-84.166612336157868,-91.358259760089823,-100.84966375704198,-89.972794458519729,-102.85371040606515,-114.55050787592654,-124.84045489732398,-136.42916985823331,-145.54593761739034,-143.31904820136151,-161.54289782028809,-233.82072859716754,-295.59118057260548,-374.95162554582566,-493.16627348815473,-493.13693373469141,-500.18024957320858,-503.74274941667363,-514.31593658755128,-528.38227486899859,-542.44861315044591,-501.16473886809172,-487.9266718715071,-492.94484610979134,-493.48811362229981,-507.55445190374712,-517.12609984465371,-477.75172060415753,-475.96012394049785,-484.75794394095738,-434.9749190044372,-442.59609395497091,-384.4855502060027,-139.7758330760912,-153.84217135753852,-144.59519085382544,-158.66152913527276,-172.72786741672053,-163.62985838282248,-177.69619666426979,-191.76253494571711,-205.82887322716442,-219.89521150861174,-233.96154979005951,-225.00969243504687],\"type\":\"scatter\",\"mode\":\"lines\",\"name\":\"Observed\",\"line\":{\"color\":\"#4D4D4D\",\"width\":2},\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[0,14.066338281447399,28.132676562894797,42.199014844342194,56.265353125789595,70.331691407236988,84.398029688684389,98.464367970131789,112.53070625157919,126.59704453302659,140.66338281447398,154.72972109592138,168.79605937736878,182.86239765881618,196.92873594026358,210.99507422171098,225.06141250315838,239.12775078460578,253.19408906605318,267.26042734750058,281.32676562894795,295.39310391039538,309.45944219184275,323.52578047329018,337.59211875473756,351.65845703618498,365.72479531763236,379.79113359907979,393.85747188052716,407.92381016197459,421.99014844342196,436.05648672486939,450.12282500631676,464.18916328776413,478.25550156921156,492.32183985065893,506.38817813210636,520.45451641355373,534.52085469500116,548.58719297644859,562.65353125789591,576.71986953934334,590.78620782079076,604.85254610223819,618.91888438368551,632.98522266513294,647.05156094658037,661.1178992280278,675.18423750947511,689.25057579092254,703.31691407236997,717.38325235381728,731.44959063526471,745.51592891671214,759.58226719815957,773.64860547960689,787.71494376105431,801.78128204250174,815.84762032394917,829.91395860539649,843.98029688684392,858.04663516829135,872.11297344973877,886.17931173118609,900.24565001263352,914.31198829408095,928.37832657552826,942.44466485697569,956.51100313842312,970.57734141987055,984.64367970131786,998.71001798276529,1012.7763562642127,1026.8426945456602,1040.9090328271075,1054.975371108555,1069.0417093900023,1083.1080476714496,1097.1743859528972,1111.2407242343445,1125.3070625157918,1139.3734007972394,1153.4397390786867,1167.506077360134,1181.5724156415815,1195.6387539230288,1209.7050922044764,1223.7714304859237,1237.837768767371,1251.9041070488186,1265.9704453302659,1280.0367836117132,1294.1031218931607,1308.169460174608,1322.2357984560556,1336.3021367375029,1350.3684750189502,1364.4348133003978,1378.5011515818451,1392.5674898632924,1406.6338281447399,1420.7001664261873,1434.7665047076346,1448.8328429890821,1462.8991812705294,1476.965519551977,1491.0318578334243,1505.0981961148716,1519.1645343963191,1533.2308726777665,1547.2972109592138,1561.3635492406613,1575.4298875221086,1589.4962258035559,1603.5625640850035,1617.6289023664508,1631.6952406478983,1645.7615789293457,1659.827917210793,1673.8942554922405,1687.9605937736878,1702.0269320551351,1716.0932703365827,1730.15960861803,1744.2259468994775,1758.2922851809249,1772.3586234623722,1786.4249617438197,1800.491300025267,1814.5576383067144,1828.6239765881619,1842.6903148696092,1856.7566531510565,1870.8229914325041,1884.8893297139514,1898.9556679953989,1913.0220062768462,1927.0883445582936,1941.1546828397411,1955.2210211211884,1969.2873594026357,1983.3536976840833,1997.4200359655306,2011.4863742469781,2025.5527125284254,2039.6190508098728,2053.6853890913203,2067.7517273727676,2081.8180656542149,2095.8844039356622,2109.95074221711,2124.0170804985573,2138.0834187800046,2152.149757061452,2166.2160953428993,2180.2824336243466,2194.3487719057944,2208.4151101872417,2222.481448468689,2236.5477867501363,2250.6141250315836,2264.6804633130314,2278.7468015944787,2292.813139875926,2306.8794781573733,2320.9458164388207,2335.012154720268,2349.0784930017157,2363.1448312831631,2377.2111695646104,2391.2775078460577,2405.343846127505,2419.4101844089528,2433.4765226904001,2447.5428609718474,2461.6091992532947,2475.675537534742,2489.7418758161893,2503.8082140976371,2517.8745523790844,2531.9408906605317,2546.0072289419791,2560.0735672234264,2574.1399055048742,2588.2062437863215,2602.2725820677688,2616.3389203492161,2630.4052586306634,2644.4715969121112,2658.5379351935585,2672.6042734750058,2686.6706117564531,2700.7369500379004,2714.8032883193478,2728.8696266007955,2742.9359648822428,2757.0023031636902,2771.0686414451375,2785.1349797265848,2799.2013180080326,2813.2676562894799,2827.3339945709272,2841.4003328523745,2855.4666711338218,2869.5330094152691,2883.5993476967169,2897.6656859781642,2911.7320242596115,2925.7983625410589,2939.8647008225062,2953.9310391039539,2967.9973773854013,2982.0637156668486,2996.1300539482959,3010.1963922297432,3024.2627305111905,3038.3290687926383,3052.3954070740856,3066.4617453555329,3080.5280836369802,3094.5944219184275,3108.6607601998753,3122.7270984813226,3136.7934367627699,3150.8597750442173,3164.9261133256646,3178.9924516071119,3193.0587898885597,3207.125128170007,3221.1914664514543,3235.2578047329016,3249.3241430143489,3263.3904812957967,3277.456819577244,3291.5231578586913,3305.5894961401386,3319.655834421586,3333.7221727030337,3347.788510984481,3361.8548492659284,3375.9211875473757,3389.987525828823,3404.0538641102703,3418.1202023917181,3432.1865406731654,3446.2528789546127,3460.31921723606,3474.3855555175073,3488.4518937989551,3502.5182320804024,3516.5845703618497,3530.650908643297,3544.7172469247444,3558.7835852061917,3572.8499234876394,3586.9162617690868,3600.9826000505341,3615.0489383319814,3629.1152766134287,3643.1816148948765,3657.2479531763238,3671.3142914577711,3685.3806297392184,3699.4469680206657,3713.5133063021131,3727.5796445835608,3741.6459828650081,3755.7123211464555,3769.7786594279028,3783.8449977093501,3797.9113359907979,3811.9776742722452,3826.0440125536925,3840.1103508351398,3854.1766891165871,3868.2430273980344,3882.3093656794822,3896.3757039609295,3910.4420422423768,3924.5083805238241,3938.5747188052715,3952.6410570867192,3966.7073953681665,3980.7737336496139,3994.8400719310612,4008.9064102125085,4022.9727484939563,4037.0390867754036,4051.1054250568509,4065.1717633382982,4079.2381016197455,4093.3044399011928,4107.3707781826406,4121.4371164640879,4135.5034547455352,4149.5697930269826,4163.6361313084299,4177.7024695898772,4191.7688078713245,4205.8351461527718,4219.90148443422,4233.9678227156674,4248.0341609971147,4262.100499278562,4276.1668375600093,4290.2331758414566,4304.2995141229039,4318.3658524043512,4332.4321906857986,4346.4985289672459,4360.5648672486932,4374.6312055301414,4388.6975438115887,4402.763882093036,4416.8302203744834,4430.8965586559307,4444.962896937378,4459.0292352188253,4473.0955735002726,4487.1619117817199,4501.2282500631673,4515.2945883446146,4529.3609266260628,4543.4272649075101,4557.4936031889574,4571.5599414704047,4585.6262797518521,4599.6926180332994,4613.7589563147467,4627.825294596194,4641.8916328776413,4655.9579711590886,4670.0243094405359,4684.0906477219842,4698.1569860034315,4712.2233242848788,4726.2896625663261,4740.3560008477734,4754.4223391292207,4768.4886774106681,4782.5550156921154,4796.6213539735627,4810.68769225501,4824.7540305364573,4838.8203688179055,4852.8867070993529,4866.9530453808002,4881.0193836622475,4895.0857219436948,4909.1520602251421,4923.2183985065894,4937.2847367880368,4951.3510750694841,4965.4174133509314,4979.4837516323787,4993.5500899138269,5007.6164281952742,5021.6827664767216,5035.7491047581689,5049.8154430396162,5063.8817813210635,5077.9481196025108,5092.0144578839581,5106.0807961654054,5120.1471344468528,5134.213472728301,5148.2798110097483,5162.3461492911956,5176.4124875726429,5190.4788258540902,5204.5451641355376,5218.6115024169849,5232.6778406984322,5246.7441789798795,5260.8105172613268,5274.8768555427741,5288.9431938242224,5303.0095321056697,5317.075870387117,5331.1422086685643,5345.2085469500116,5359.2748852314589,5373.3412235129063,5387.4075617943536,5401.4739000758009,5415.5402383572482,5429.6065766386955,5443.6729149201437,5457.7392532015911,5471.8055914830384,5485.8719297644857,5499.938268045933,5514.0046063273803,5528.0709446088276,5542.1372828902749,5556.2036211717223,5570.2699594531696,5584.3362977346169,5598.4026360160651,5612.4689742975124,5626.5353125789597,5640.6016508604071,5654.6679891418544,5668.7343274233017,5682.800665704749,5696.8670039861963,5710.9333422676436,5724.999680549091,5739.0660188305383,5753.1323571119865,5767.1986953934338,5781.2650336748811,5795.3313719563284,5809.3977102377758,5823.4640485192231,5837.5303868006704,5851.5967250821177,5865.663063363565,5879.7294016450123,5893.7957399264596,5907.8620782079079,5921.9284164893552,5935.9947547708025,5950.0610930522498,5964.1274313336971,5978.1937696151444,5992.2601078965918,6006.3264461780391,6020.3927844594864,6034.4591227409337,6048.525461022381,6062.5917993038292,6076.6581375852766,6090.7244758667239,6104.7908141481712,6118.8571524296185,6132.9234907110658,6146.9898289925131,6161.0561672739605,6175.1225055554078,6189.1888438368551,6203.2551821183024,6217.3215203997506,6231.3878586811979,6245.4541969626453,6259.5205352440926,6273.5868735255399,6287.6532118069872,6301.7195500884345,6315.7858883698818,6329.8522266513291,6343.9185649327765,6357.9849032142238,6372.051241495672,6386.1175797771193,6400.1839180585666,6414.2502563400139,6428.3165946214613,6442.3829329029086,6456.4492711843559,6470.5156094658032,6484.5819477472505,6498.6482860286978,6512.7146243101461,6526.7809625915934,6540.8473008730407,6554.913639154488,6568.9799774359353,6583.0463157173826,6597.11265399883,6611.1789922802773,6625.2453305617246,6639.3116688431719,6653.3780071246192,6667.4443454060674,6681.5106836875148,6695.5770219689621,6709.6433602504094,6723.7096985318567,6737.776036813304,6751.8423750947513,6765.9087133761986,6779.975051657646,6794.0413899390933,6808.1077282205406,6822.1740665019888,6836.2404047834361,6850.3067430648834,6864.3730813463308,6878.4394196277781,6892.5057579092254,6906.5720961906727,6920.63843447212,6934.7047727535673,6948.7711110350147,6962.837449316462,6976.9037875979102,6990.9701258793575,7005.0364641608048,7019.1028024422521,7033.1691407236995,7047.2354790051468,7061.3018172865941,7075.3681555680414,7089.4344938494887,7103.500832130936,7117.5671704123833,7131.6335086938316,7145.6998469752789,7159.7661852567262,7173.8325235381735,7187.8988618196208,7201.9652001010681],\"y\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2.8421709430404007e-14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-5.6843418860808015e-14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1.1368683772161603e-13,0,0,0,0,0,0,1.1368683772161603e-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2.2737367544323206e-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2.2737367544323206e-13,0,0,0,0,2.2737367544323206e-13,0,0,0,0,0,0,0,0,2.2737367544323206e-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.5474735088646412e-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-4.5474735088646412e-13,0,0,0,0,0,0,0,0,0,4.5474735088646412e-13,0,0,0,0,0,0,0,0,0,0,0,0,-4.5474735088646412e-13,0,0,0,0,4.5474735088646412e-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.0949470177292824e-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-9.0949470177292824e-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-9.0949470177292824e-13,0,-9.0949470177292824e-13,-9.0949470177292824e-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-9.0949470177292824e-13,0,-9.0949470177292824e-13,0,0,9.0949470177292824e-13,0,0,-9.0949470177292824e-13,0,0,0,0,0,0,0,0,0],\"type\":\"scatter\",\"mode\":\"lines\",\"name\":\"Theoretical (CSR)\",\"line\":{\"color\":\"red\",\"width\":2,\"dash\":\"dash\"},\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"fillcolor\":\"rgba(173,216,230,0.3)\",\"x\":[0,14.066338281447399,28.132676562894797,42.199014844342194,56.265353125789595,70.331691407236988,84.398029688684389,98.464367970131789,112.53070625157919,126.59704453302659,140.66338281447398,154.72972109592138,168.79605937736878,182.86239765881618,196.92873594026358,210.99507422171098,225.06141250315838,239.12775078460578,253.19408906605318,267.26042734750058,281.32676562894795,295.39310391039538,309.45944219184275,323.52578047329018,337.59211875473756,351.65845703618498,365.72479531763236,379.79113359907979,393.85747188052716,407.92381016197459,421.99014844342196,436.05648672486939,450.12282500631676,464.18916328776413,478.25550156921156,492.32183985065893,506.38817813210636,520.45451641355373,534.52085469500116,548.58719297644859,562.65353125789591,576.71986953934334,590.78620782079076,604.85254610223819,618.91888438368551,632.98522266513294,647.05156094658037,661.1178992280278,675.18423750947511,689.25057579092254,703.31691407236997,717.38325235381728,731.44959063526471,745.51592891671214,759.58226719815957,773.64860547960689,787.71494376105431,801.78128204250174,815.84762032394917,829.91395860539649,843.98029688684392,858.04663516829135,872.11297344973877,886.17931173118609,900.24565001263352,914.31198829408095,928.37832657552826,942.44466485697569,956.51100313842312,970.57734141987055,984.64367970131786,998.71001798276529,1012.7763562642127,1026.8426945456602,1040.9090328271075,1054.975371108555,1069.0417093900023,1083.1080476714496,1097.1743859528972,1111.2407242343445,1125.3070625157918,1139.3734007972394,1153.4397390786867,1167.506077360134,1181.5724156415815,1195.6387539230288,1209.7050922044764,1223.7714304859237,1237.837768767371,1251.9041070488186,1265.9704453302659,1280.0367836117132,1294.1031218931607,1308.169460174608,1322.2357984560556,1336.3021367375029,1350.3684750189502,1364.4348133003978,1378.5011515818451,1392.5674898632924,1406.6338281447399,1420.7001664261873,1434.7665047076346,1448.8328429890821,1462.8991812705294,1476.965519551977,1491.0318578334243,1505.0981961148716,1519.1645343963191,1533.2308726777665,1547.2972109592138,1561.3635492406613,1575.4298875221086,1589.4962258035559,1603.5625640850035,1617.6289023664508,1631.6952406478983,1645.7615789293457,1659.827917210793,1673.8942554922405,1687.9605937736878,1702.0269320551351,1716.0932703365827,1730.15960861803,1744.2259468994775,1758.2922851809249,1772.3586234623722,1786.4249617438197,1800.491300025267,1814.5576383067144,1828.6239765881619,1842.6903148696092,1856.7566531510565,1870.8229914325041,1884.8893297139514,1898.9556679953989,1913.0220062768462,1927.0883445582936,1941.1546828397411,1955.2210211211884,1969.2873594026357,1983.3536976840833,1997.4200359655306,2011.4863742469781,2025.5527125284254,2039.6190508098728,2053.6853890913203,2067.7517273727676,2081.8180656542149,2095.8844039356622,2109.95074221711,2124.0170804985573,2138.0834187800046,2152.149757061452,2166.2160953428993,2180.2824336243466,2194.3487719057944,2208.4151101872417,2222.481448468689,2236.5477867501363,2250.6141250315836,2264.6804633130314,2278.7468015944787,2292.813139875926,2306.8794781573733,2320.9458164388207,2335.012154720268,2349.0784930017157,2363.1448312831631,2377.2111695646104,2391.2775078460577,2405.343846127505,2419.4101844089528,2433.4765226904001,2447.5428609718474,2461.6091992532947,2475.675537534742,2489.7418758161893,2503.8082140976371,2517.8745523790844,2531.9408906605317,2546.0072289419791,2560.0735672234264,2574.1399055048742,2588.2062437863215,2602.2725820677688,2616.3389203492161,2630.4052586306634,2644.4715969121112,2658.5379351935585,2672.6042734750058,2686.6706117564531,2700.7369500379004,2714.8032883193478,2728.8696266007955,2742.9359648822428,2757.0023031636902,2771.0686414451375,2785.1349797265848,2799.2013180080326,2813.2676562894799,2827.3339945709272,2841.4003328523745,2855.4666711338218,2869.5330094152691,2883.5993476967169,2897.6656859781642,2911.7320242596115,2925.7983625410589,2939.8647008225062,2953.9310391039539,2967.9973773854013,2982.0637156668486,2996.1300539482959,3010.1963922297432,3024.2627305111905,3038.3290687926383,3052.3954070740856,3066.4617453555329,3080.5280836369802,3094.5944219184275,3108.6607601998753,3122.7270984813226,3136.7934367627699,3150.8597750442173,3164.9261133256646,3178.9924516071119,3193.0587898885597,3207.125128170007,3221.1914664514543,3235.2578047329016,3249.3241430143489,3263.3904812957967,3277.456819577244,3291.5231578586913,3305.5894961401386,3319.655834421586,3333.7221727030337,3347.788510984481,3361.8548492659284,3375.9211875473757,3389.987525828823,3404.0538641102703,3418.1202023917181,3432.1865406731654,3446.2528789546127,3460.31921723606,3474.3855555175073,3488.4518937989551,3502.5182320804024,3516.5845703618497,3530.650908643297,3544.7172469247444,3558.7835852061917,3572.8499234876394,3586.9162617690868,3600.9826000505341,3615.0489383319814,3629.1152766134287,3643.1816148948765,3657.2479531763238,3671.3142914577711,3685.3806297392184,3699.4469680206657,3713.5133063021131,3727.5796445835608,3741.6459828650081,3755.7123211464555,3769.7786594279028,3783.8449977093501,3797.9113359907979,3811.9776742722452,3826.0440125536925,3840.1103508351398,3854.1766891165871,3868.2430273980344,3882.3093656794822,3896.3757039609295,3910.4420422423768,3924.5083805238241,3938.5747188052715,3952.6410570867192,3966.7073953681665,3980.7737336496139,3994.8400719310612,4008.9064102125085,4022.9727484939563,4037.0390867754036,4051.1054250568509,4065.1717633382982,4079.2381016197455,4093.3044399011928,4107.3707781826406,4121.4371164640879,4135.5034547455352,4149.5697930269826,4163.6361313084299,4177.7024695898772,4191.7688078713245,4205.8351461527718,4219.90148443422,4233.9678227156674,4248.0341609971147,4262.100499278562,4276.1668375600093,4290.2331758414566,4304.2995141229039,4318.3658524043512,4332.4321906857986,4346.4985289672459,4360.5648672486932,4374.6312055301414,4388.6975438115887,4402.763882093036,4416.8302203744834,4430.8965586559307,4444.962896937378,4459.0292352188253,4473.0955735002726,4487.1619117817199,4501.2282500631673,4515.2945883446146,4529.3609266260628,4543.4272649075101,4557.4936031889574,4571.5599414704047,4585.6262797518521,4599.6926180332994,4613.7589563147467,4627.825294596194,4641.8916328776413,4655.9579711590886,4670.0243094405359,4684.0906477219842,4698.1569860034315,4712.2233242848788,4726.2896625663261,4740.3560008477734,4754.4223391292207,4768.4886774106681,4782.5550156921154,4796.6213539735627,4810.68769225501,4824.7540305364573,4838.8203688179055,4852.8867070993529,4866.9530453808002,4881.0193836622475,4895.0857219436948,4909.1520602251421,4923.2183985065894,4937.2847367880368,4951.3510750694841,4965.4174133509314,4979.4837516323787,4993.5500899138269,5007.6164281952742,5021.6827664767216,5035.7491047581689,5049.8154430396162,5063.8817813210635,5077.9481196025108,5092.0144578839581,5106.0807961654054,5120.1471344468528,5134.213472728301,5148.2798110097483,5162.3461492911956,5176.4124875726429,5190.4788258540902,5204.5451641355376,5218.6115024169849,5232.6778406984322,5246.7441789798795,5260.8105172613268,5274.8768555427741,5288.9431938242224,5303.0095321056697,5317.075870387117,5331.1422086685643,5345.2085469500116,5359.2748852314589,5373.3412235129063,5387.4075617943536,5401.4739000758009,5415.5402383572482,5429.6065766386955,5443.6729149201437,5457.7392532015911,5471.8055914830384,5485.8719297644857,5499.938268045933,5514.0046063273803,5528.0709446088276,5542.1372828902749,5556.2036211717223,5570.2699594531696,5584.3362977346169,5598.4026360160651,5612.4689742975124,5626.5353125789597,5640.6016508604071,5654.6679891418544,5668.7343274233017,5682.800665704749,5696.8670039861963,5710.9333422676436,5724.999680549091,5739.0660188305383,5753.1323571119865,5767.1986953934338,5781.2650336748811,5795.3313719563284,5809.3977102377758,5823.4640485192231,5837.5303868006704,5851.5967250821177,5865.663063363565,5879.7294016450123,5893.7957399264596,5907.8620782079079,5921.9284164893552,5935.9947547708025,5950.0610930522498,5964.1274313336971,5978.1937696151444,5992.2601078965918,6006.3264461780391,6020.3927844594864,6034.4591227409337,6048.525461022381,6062.5917993038292,6076.6581375852766,6090.7244758667239,6104.7908141481712,6118.8571524296185,6132.9234907110658,6146.9898289925131,6161.0561672739605,6175.1225055554078,6189.1888438368551,6203.2551821183024,6217.3215203997506,6231.3878586811979,6245.4541969626453,6259.5205352440926,6273.5868735255399,6287.6532118069872,6301.7195500884345,6315.7858883698818,6329.8522266513291,6343.9185649327765,6357.9849032142238,6372.051241495672,6386.1175797771193,6400.1839180585666,6414.2502563400139,6428.3165946214613,6442.3829329029086,6456.4492711843559,6470.5156094658032,6484.5819477472505,6498.6482860286978,6512.7146243101461,6526.7809625915934,6540.8473008730407,6554.913639154488,6568.9799774359353,6583.0463157173826,6597.11265399883,6611.1789922802773,6625.2453305617246,6639.3116688431719,6653.3780071246192,6667.4443454060674,6681.5106836875148,6695.5770219689621,6709.6433602504094,6723.7096985318567,6737.776036813304,6751.8423750947513,6765.9087133761986,6779.975051657646,6794.0413899390933,6808.1077282205406,6822.1740665019888,6836.2404047834361,6850.3067430648834,6864.3730813463308,6878.4394196277781,6892.5057579092254,6906.5720961906727,6920.63843447212,6934.7047727535673,6948.7711110350147,6962.837449316462,6976.9037875979102,6990.9701258793575,7005.0364641608048,7019.1028024422521,7033.1691407236995,7047.2354790051468,7061.3018172865941,7075.3681555680414,7089.4344938494887,7103.500832130936,7117.5671704123833,7131.6335086938316,7145.6998469752789,7159.7661852567262,7173.8325235381735,7187.8988618196208,7201.9652001010681,7201.9652001010681,7201.9652001010681,7187.8988618196208,7173.8325235381735,7159.7661852567262,7145.6998469752789,7131.6335086938316,7117.5671704123833,7103.500832130936,7089.4344938494887,7075.3681555680414,7061.3018172865941,7047.2354790051468,7033.1691407236995,7019.1028024422521,7005.0364641608048,6990.9701258793575,6976.9037875979102,6962.837449316462,6948.7711110350147,6934.7047727535673,6920.63843447212,6906.5720961906727,6892.5057579092254,6878.4394196277781,6864.3730813463308,6850.3067430648834,6836.2404047834361,6822.1740665019888,6808.1077282205406,6794.0413899390933,6779.975051657646,6765.9087133761986,6751.8423750947513,6737.776036813304,6723.7096985318567,6709.6433602504094,6695.5770219689621,6681.5106836875148,6667.4443454060674,6653.3780071246192,6639.3116688431719,6625.2453305617246,6611.1789922802773,6597.11265399883,6583.0463157173826,6568.9799774359353,6554.913639154488,6540.8473008730407,6526.7809625915934,6512.7146243101461,6498.6482860286978,6484.5819477472505,6470.5156094658032,6456.4492711843559,6442.3829329029086,6428.3165946214613,6414.2502563400139,6400.1839180585666,6386.1175797771193,6372.051241495672,6357.9849032142238,6343.9185649327765,6329.8522266513291,6315.7858883698818,6301.7195500884345,6287.6532118069872,6273.5868735255399,6259.5205352440926,6245.4541969626453,6231.3878586811979,6217.3215203997506,6203.2551821183024,6189.1888438368551,6175.1225055554078,6161.0561672739605,6146.9898289925131,6132.9234907110658,6118.8571524296185,6104.7908141481712,6090.7244758667239,6076.6581375852766,6062.5917993038292,6048.525461022381,6034.4591227409337,6020.3927844594864,6006.3264461780391,5992.2601078965918,5978.1937696151444,5964.1274313336971,5950.0610930522498,5935.9947547708025,5921.9284164893552,5907.8620782079079,5893.7957399264596,5879.7294016450123,5865.663063363565,5851.5967250821177,5837.5303868006704,5823.4640485192231,5809.3977102377758,5795.3313719563284,5781.2650336748811,5767.1986953934338,5753.1323571119865,5739.0660188305383,5724.999680549091,5710.9333422676436,5696.8670039861963,5682.800665704749,5668.7343274233017,5654.6679891418544,5640.6016508604071,5626.5353125789597,5612.4689742975124,5598.4026360160651,5584.3362977346169,5570.2699594531696,5556.2036211717223,5542.1372828902749,5528.0709446088276,5514.0046063273803,5499.938268045933,5485.8719297644857,5471.8055914830384,5457.7392532015911,5443.6729149201437,5429.6065766386955,5415.5402383572482,5401.4739000758009,5387.4075617943536,5373.3412235129063,5359.2748852314589,5345.2085469500116,5331.1422086685643,5317.075870387117,5303.0095321056697,5288.9431938242224,5274.8768555427741,5260.8105172613268,5246.7441789798795,5232.6778406984322,5218.6115024169849,5204.5451641355376,5190.4788258540902,5176.4124875726429,5162.3461492911956,5148.2798110097483,5134.213472728301,5120.1471344468528,5106.0807961654054,5092.0144578839581,5077.9481196025108,5063.8817813210635,5049.8154430396162,5035.7491047581689,5021.6827664767216,5007.6164281952742,4993.5500899138269,4979.4837516323787,4965.4174133509314,4951.3510750694841,4937.2847367880368,4923.2183985065894,4909.1520602251421,4895.0857219436948,4881.0193836622475,4866.9530453808002,4852.8867070993529,4838.8203688179055,4824.7540305364573,4810.68769225501,4796.6213539735627,4782.5550156921154,4768.4886774106681,4754.4223391292207,4740.3560008477734,4726.2896625663261,4712.2233242848788,4698.1569860034315,4684.0906477219842,4670.0243094405359,4655.9579711590886,4641.8916328776413,4627.825294596194,4613.7589563147467,4599.6926180332994,4585.6262797518521,4571.5599414704047,4557.4936031889574,4543.4272649075101,4529.3609266260628,4515.2945883446146,4501.2282500631673,4487.1619117817199,4473.0955735002726,4459.0292352188253,4444.962896937378,4430.8965586559307,4416.8302203744834,4402.763882093036,4388.6975438115887,4374.6312055301414,4360.5648672486932,4346.4985289672459,4332.4321906857986,4318.3658524043512,4304.2995141229039,4290.2331758414566,4276.1668375600093,4262.100499278562,4248.0341609971147,4233.9678227156674,4219.90148443422,4205.8351461527718,4191.7688078713245,4177.7024695898772,4163.6361313084299,4149.5697930269826,4135.5034547455352,4121.4371164640879,4107.3707781826406,4093.3044399011928,4079.2381016197455,4065.1717633382982,4051.1054250568509,4037.0390867754036,4022.9727484939563,4008.9064102125085,3994.8400719310612,3980.7737336496139,3966.7073953681665,3952.6410570867192,3938.5747188052715,3924.5083805238241,3910.4420422423768,3896.3757039609295,3882.3093656794822,3868.2430273980344,3854.1766891165871,3840.1103508351398,3826.0440125536925,3811.9776742722452,3797.9113359907979,3783.8449977093501,3769.7786594279028,3755.7123211464555,3741.6459828650081,3727.5796445835608,3713.5133063021131,3699.4469680206657,3685.3806297392184,3671.3142914577711,3657.2479531763238,3643.1816148948765,3629.1152766134287,3615.0489383319814,3600.9826000505341,3586.9162617690868,3572.8499234876394,3558.7835852061917,3544.7172469247444,3530.650908643297,3516.5845703618497,3502.5182320804024,3488.4518937989551,3474.3855555175073,3460.31921723606,3446.2528789546127,3432.1865406731654,3418.1202023917181,3404.0538641102703,3389.987525828823,3375.9211875473757,3361.8548492659284,3347.788510984481,3333.7221727030337,3319.655834421586,3305.5894961401386,3291.5231578586913,3277.456819577244,3263.3904812957967,3249.3241430143489,3235.2578047329016,3221.1914664514543,3207.125128170007,3193.0587898885597,3178.9924516071119,3164.9261133256646,3150.8597750442173,3136.7934367627699,3122.7270984813226,3108.6607601998753,3094.5944219184275,3080.5280836369802,3066.4617453555329,3052.3954070740856,3038.3290687926383,3024.2627305111905,3010.1963922297432,2996.1300539482959,2982.0637156668486,2967.9973773854013,2953.9310391039539,2939.8647008225062,2925.7983625410589,2911.7320242596115,2897.6656859781642,2883.5993476967169,2869.5330094152691,2855.4666711338218,2841.4003328523745,2827.3339945709272,2813.2676562894799,2799.2013180080326,2785.1349797265848,2771.0686414451375,2757.0023031636902,2742.9359648822428,2728.8696266007955,2714.8032883193478,2700.7369500379004,2686.6706117564531,2672.6042734750058,2658.5379351935585,2644.4715969121112,2630.4052586306634,2616.3389203492161,2602.2725820677688,2588.2062437863215,2574.1399055048742,2560.0735672234264,2546.0072289419791,2531.9408906605317,2517.8745523790844,2503.8082140976371,2489.7418758161893,2475.675537534742,2461.6091992532947,2447.5428609718474,2433.4765226904001,2419.4101844089528,2405.343846127505,2391.2775078460577,2377.2111695646104,2363.1448312831631,2349.0784930017157,2335.012154720268,2320.9458164388207,2306.8794781573733,2292.813139875926,2278.7468015944787,2264.6804633130314,2250.6141250315836,2236.5477867501363,2222.481448468689,2208.4151101872417,2194.3487719057944,2180.2824336243466,2166.2160953428993,2152.149757061452,2138.0834187800046,2124.0170804985573,2109.95074221711,2095.8844039356622,2081.8180656542149,2067.7517273727676,2053.6853890913203,2039.6190508098728,2025.5527125284254,2011.4863742469781,1997.4200359655306,1983.3536976840833,1969.2873594026357,1955.2210211211884,1941.1546828397411,1927.0883445582936,1913.0220062768462,1898.9556679953989,1884.8893297139514,1870.8229914325041,1856.7566531510565,1842.6903148696092,1828.6239765881619,1814.5576383067144,1800.491300025267,1786.4249617438197,1772.3586234623722,1758.2922851809249,1744.2259468994775,1730.15960861803,1716.0932703365827,1702.0269320551351,1687.9605937736878,1673.8942554922405,1659.827917210793,1645.7615789293457,1631.6952406478983,1617.6289023664508,1603.5625640850035,1589.4962258035559,1575.4298875221086,1561.3635492406613,1547.2972109592138,1533.2308726777665,1519.1645343963191,1505.0981961148716,1491.0318578334243,1476.965519551977,1462.8991812705294,1448.8328429890821,1434.7665047076346,1420.7001664261873,1406.6338281447399,1392.5674898632924,1378.5011515818451,1364.4348133003978,1350.3684750189502,1336.3021367375029,1322.2357984560556,1308.169460174608,1294.1031218931607,1280.0367836117132,1265.9704453302659,1251.9041070488186,1237.837768767371,1223.7714304859237,1209.7050922044764,1195.6387539230288,1181.5724156415815,1167.506077360134,1153.4397390786867,1139.3734007972394,1125.3070625157918,1111.2407242343445,1097.1743859528972,1083.1080476714496,1069.0417093900023,1054.975371108555,1040.9090328271075,1026.8426945456602,1012.7763562642127,998.71001798276529,984.64367970131786,970.57734141987055,956.51100313842312,942.44466485697569,928.37832657552826,914.31198829408095,900.24565001263352,886.17931173118609,872.11297344973877,858.04663516829135,843.98029688684392,829.91395860539649,815.84762032394917,801.78128204250174,787.71494376105431,773.64860547960689,759.58226719815957,745.51592891671214,731.44959063526471,717.38325235381728,703.31691407236997,689.25057579092254,675.18423750947511,661.1178992280278,647.05156094658037,632.98522266513294,618.91888438368551,604.85254610223819,590.78620782079076,576.71986953934334,562.65353125789591,548.58719297644859,534.52085469500116,520.45451641355373,506.38817813210636,492.32183985065893,478.25550156921156,464.18916328776413,450.12282500631676,436.05648672486939,421.99014844342196,407.92381016197459,393.85747188052716,379.79113359907979,365.72479531763236,351.65845703618498,337.59211875473756,323.52578047329018,309.45944219184275,295.39310391039538,281.32676562894795,267.26042734750058,253.19408906605318,239.12775078460578,225.06141250315838,210.99507422171098,196.92873594026358,182.86239765881618,168.79605937736878,154.72972109592138,140.66338281447398,126.59704453302659,112.53070625157919,98.464367970131789,84.398029688684389,70.331691407236988,56.265353125789595,42.199014844342194,28.132676562894797,14.066338281447399,0],\"type\":\"scatter\",\"mode\":\"lines\",\"hoveron\":\"points\",\"fill\":\"toself\",\"name\":\"95% CI\",\"line\":{\"color\":\"lightblue\"},\"y\":[0,-14.066338281447399,-28.132676562894797,-11.906121043671547,-18.986438467462996,-19.661313431269328,-25.328868162441609,-14.713377201287315,-11.933861674061831,-16.421811488999893,-14.31065548744003,-21.204434802812784,-21.285225189151191,-15.676309553835154,-18.097772273728225,-21.843896185629347,-14.821520065304355,-16.811097740318246,-22.857248198238267,-18.19698233599533,-21.917667517978714,-17.889156594508222,-22.410421806931481,-20.90131152813052,-20.60789744547094,-22.808777631839348,-22.286923746276614,-22.251885979944973,-23.915180983046298,-24.017297239818845,-26.648851451508222,-26.565442768358082,-27.78589659062186,-30.034362607386186,-31.339141061814416,-31.938015142690972,-31.231686318893026,-24.522821393756146,-27.089366519909106,-25.273583809843331,-25.050788536382242,-24.466627978250131,-28.016445500875307,-29.547082817044725,-30.194160916787609,-31.777956417033465,-30.547548370228924,-29.459344376975992,-29.866348571232038,-30.546519355446208,-29.594027590879364,-31.124911761461249,-31.953648556573626,-33.133704691089747,-33.191632864343433,-30.901251009998418,-30.552066972122134,-31.42107856113762,-32.322917475390341,-30.85187671360768,-32.676443187739096,-30.283872200381438,-27.122942438049904,-24.942363811330551,-24.2112933270746,-24.558087654378824,-26.446123536937876,-25.625290984663707,-28.247883905637877,-27.178404173241347,-28.757720618477379,-29.463923720492403,-26.956762387344384,-25.682842803988478,-26.164098766806887,-29.45118924697681,-28.792940359761815,-31.58963552663954,-29.939659914653475,-33.704643861113709,-34.640488997446937,-36.797654557180294,-35.23886605569578,-37.231389347254208,-36.470201261530747,-37.347843706737876,-37.808256946176925,-37.77925117982204,-38.749931981392137,-39.297432019525786,-42.04996317527366,-42.499177352031666,-41.681652137679066,-43.316218872885884,-44.926937690364639,-47.349716702230126,-48.291453729197883,-47.063158304026956,-47.042869296077242,-50.715265861728085,-54.362435618263817,-55.412117219188985,-55.236461549137857,-57.744596284105455,-57.189536986057874,-58.173645671274926,-58.590744202274436,-60.139450977251954,-58.020826116708804,-60.430816194312911,-61.35124990323402,-64.610870036100096,-60.38582833820692,-62.622563146129096,-64.965350727342411,-68.958800267589595,-68.045739592511381,-62.017777935507183,-64.397997070624342,-61.753035751520201,-60.729249737353939,-66.204609993564418,-69.396709304907063,-68.725305371773629,-67.506915689228435,-68.077750977592359,-66.132984259699015,-67.246774809329963,-71.640924116061569,-72.562833362690526,-71.429326662763742,-70.625501556439531,-69.14824536910578,-67.000493122943681,-68.806487389740141,-69.754498911550854,-71.566863498373323,-69.612058368506496,-71.215996017869429,-72.734178679315846,-73.287355992541279,-76.151445514276247,-81.361031680517272,-89.599217541939879,-91.003208138525679,-95.889147770289583,-92.99521116879464,-94.30931574245642,-97.343669520588492,-97.148795075477892,-96.451666070518968,-96.610908964102236,-102.42729067269715,-101.38706028675779,-105.01309429724915,-104.37917832310495,-111.53444712371311,-114.79184326507675,-119.65704969715898,-126.07053796114542,-131.14442674281599,-134.4774895010878,-131.73131413322017,-132.02780168160962,-137.13091972539905,-138.3076000122901,-139.70523095373346,-140.50191956968138,-141.04766138569948,-147.64460870451603,-151.01693210371695,-153.17748126875222,-147.65598229520492,-150.9820378480099,-148.26537187392705,-141.30289468202091,-142.35684029074901,-142.06378352165029,-141.59453766266233,-138.61943604735416,-139.1247262961997,-141.67802152851482,-144.89146238907961,-146.27474744011943,-148.66045179619186,-156.96802906109951,-156.73478550769187,-161.05285768473641,-161.65284635069429,-158.51143757886985,-163.175576629023,-162.78104625423248,-165.47469697755923,-166.16452681261626,-166.9241975339437,-169.2774652339117,-168.94987202144966,-174.41346328169629,-188.65790473411789,-201.1509779617204,-198.07151653763412,-217.91827824011534,-223.64594298306156,-227.33072843543687,-240.76892031814214,-242.30370112531955,-248.39479973883772,-249.42854825324321,-247.57361628099534,-243.17580684811992,-242.71333597432385,-247.61822839654133,-251.10802291627533,-246.03619545542824,-249.70407432092679,-249.39275119444483,-252.46946239203362,-255.80253465403075,-251.79568062384897,-250.85989525717287,-262.81079705286402,-260.59302395934355,-266.25143913085867,-273.72011772840278,-275.67250340588089,-269.35375883701454,-286.83133610503091,-286.42755738533378,-280.82611665828063,-265.66906976989139,-272.50741389516179,-275.08556299622796,-275.97604598551106,-276.1448722652317,-273.19442245595474,-278.52385826741647,-281.97642993081445,-325.21953026469373,-321.45733039246488,-317.94560498560713,-310.60765431575783,-327.43955095674937,-331.07128328295948,-308.46331267695359,-311.82512054162316,-303.04838153805122,-300.95417886219775,-367.73254399337611,-374.08047780370953,-372.19894303434012,-388.75177646257907,-436.47996436592121,-450.54630264736852,-438.50103078898701,-429.97609826150574,-436.77566655260307,-435.63608898047096,-444.64999545729324,-448.63554854472477,-436.39059577577109,-409.55490204751004,-423.62124032895736,-413.45072710546992,-427.51706538691724,-441.58340366836455,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,233.85218047084527,277.05076258561849,283.85408525047023,283.35437544770957,290.11753359663453,282.19280669261798,274.14418352247139,265.96954611606861,257.20293549570124,252.81777856355575,252.05883353154968,273.01547239433194,239.12248565674872,221.8462381094273,228.2151382406928,213.00690686848657,233.89165113411627,234.86902842980135,228.48244824369795,209.53068706933072,206.92923230620818,207.04720276734542,221.03133304594394,210.09299256030317,220.66829494689,210.93166170951054,205.84082969580322,201.85304945085954,202.6208870455639,206.98396523504607,201.25756870227224,211.73036802860224,208.05120188335559,186.55583942492103,174.3378906672915,174.38835239198488,186.50763107453713,186.355560904713,193.75243472062948,200.70449754887522,186.59224164654279,188.34902675349713,192.64987415670703,181.6282814892279,184.04026213734596,168.29542528019192,146.4777455389617,126.70902334430866,134.34174749640169,135.00024910817183,133.40996651985051,129.20508881098158,140.64202595966981,136.82057283770655,140.79114971869876,143.33449833576151,139.74337471257104,137.01694056866882,140.61532660220973,141.51245947802227,142.36973334288268,140.27874304778379,133.94100327965543,133.39019163819739,131.98134867787303,135.38644980763547,121.92810026521056,112.58876899336656,108.40364782523511,109.24054871128556,106.75925094503236,107.10074327168013,108.53958986305315,105.8859067534554,96.559491400005754,100.40427388830722,97.193905582150364,98.259886572089272,101.2510344820721,103.12041866337404,95.764997548371866,89.325877709374709,84.845964431655375,91.501161980249435,93.982884903831291,86.786519999894608,85.527021775327285,82.657410844284186,82.050860439870121,86.297510591051832,84.55694885916364,87.350784845946691,90.044211258854375,89.686159525576841,88.712450240187536,85.881788078977479,85.320852166906207,87.589529391344513,86.152045758311033,87.581968812183732,81.701821759845188,79.15325125080517,75.380962727123915,71.20009087996641,77.357739695704367,73.705261617827546,72.12536514821295,68.495479812630947,69.495280821487086,61.21615619507611,62.660344346832517,58.737302069226189,61.044972792645694,62.122375894544803,63.553986428300504,65.146655860676674,63.683666532910138,66.193926365043808,66.370475885724773,63.879659373488948,60.62910724773451,60.573406941272196,60.974627766598587,62.637474422863988,63.679181985266041,60.830221627807987,68.580609959307139,70.080399514174587,72.811642258430766,71.516121376482261,70.765935020267762,69.628368149802554,68.818927061706972,68.411147014107883,67.568455390950703,66.948657845206071,68.484201721206546,67.763058902740113,67.685880058654675,67.627628461937547,67.3867337304373,66.3130389872249,61.540315945365137,59.204939014949559,55.808066712573009,54.490236020376415,53.548204086408987,52.522976659028927,50.724051478689717,47.904218173320487,46.527359385186628,44.712544318512755,42.285757303935952,45.389810961035892,43.91182492475059,42.099664878138583,38.832800067307971,40.114062672626233,38.99769597563909,38.949497718821476,36.941864727676148,35.70684795370039,35.995636104129517,36.349810223003033,39.072345039290667,38.837878086216278,39.093676466850411,39.323906681173867,36.188270290535229,35.973571176062023,35.27396607366677,33.135868867202589,31.64709530929531,29.390008308607776,31.647120651015257,34.343639113470999,33.330205711378085,30.536002619772262,29.222305944176014,28.087934324018079,27.576076865560935,25.29631414005712,23.34293300309696,21.90769949706646,23.593323005530465,24.263624934059408,23.891994162524725,22.481781843967156,23.906433750562883,24.234222907415187,24.624267978747639,23.585094045187589,24.816651218279844,23.984068120817824,27.150985078678104,27.78095045752616,24.483323388557437,26.898784671735712,31.131831607687786,35.19729726467699,35.131221386940751,31.495156857017378,31.953403917921378,30.258451581318468,29.76066891186656,30.207580999151105,30.544574095572557,34.988237260138135,33.113556689519669,30.680078759870412,30.660881140203969,29.885038317856015,31.648630745277273,29.55346931648819,27.999334211311407,29.189777926846773,30.794150216964795,27.780968485708286,25.656465643036427,25.736623225420658,25.084405892223913,23.997718258715736,25.06355541660389,27.3235037496828,28.965744615080325,26.562926106197892,22.765209728128866,24.242993420982316,24.722411638638675,25.85729358757925,25.08349874125588,22.817079683386623,24.301031935051469,20.756290150816653,20.232202340521383,19.972206305803297,21.049643160059873,17.653475736392465,14.676262116435566,16.703693570489293,15.71891570948759,17.765170038688439,18.079185542522225,16.347700290721946,14.838483956276264,19.568564007864154,20.471289580565355,20.853876339716521,22.022079375798228,17.943697515056584,18.003727093877671,19.626228470250339,16.305141499750704,19.258490903502064,19.170519048116091,23.115877679963049,25.745542517969497,24.629602479704701,20.79539586614456,20.278935171924033,18.922560907981044,22.585932249956876,17.470381196783354,15.643156745976556,0],\"marker\":{\"color\":\"rgba(44,160,44,1)\",\"line\":{\"color\":\"rgba(44,160,44,1)\"}},\"error_y\":{\"color\":\"rgba(44,160,44,1)\"},\"error_x\":{\"color\":\"rgba(44,160,44,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: callout-note\nThis plot above shows the spatial distribution of IT businesses across a large area using the L-function. The observed curve rises well above the theoretical expectation between 0 and 3000 meters, indicating strong clustering at short to mid-range distances. Beyond 3500 meters, the curve dips below the confidence interval, suggesting dispersion or regular spacing at larger scales. This pattern implies that IT firms tend to concentrate in specific hubs but avoid overlapping across broader regions. The dual behavior reflects both localized agglomeration and strategic spacing across the urban landscape.\n:::\n\n#### Findings \n\nThe IT sector exhibits a sophisticated dual spatial strategy that reflects the diverse needs of different technology business models. The analysis reveals extreme clustering in the Downtown Core (Clark-Evans R = 0.32) alongside significant but different clustering patterns in peripheral areas (R = 0.40). This bifurcated spatial organization shows corporate IT and fintech firms hyper-concentrating in the CBD for proximity to clients and financial institutions, while R&D and innovation-focused companies form specialized clusters in areas like one-north. The sector operates at multiple spatial scales, with CBD clustering occurring at very fine scales (50-150 meters) for maximum interaction density, while peripheral clusters function at larger scales (200-500 meters) suitable for campus-style development. This pattern reflects global trends in tech industry location strategies and demonstrates how different IT business models require distinct spatial environments.\n\nIT businesses display a dual clustering pattern with extreme concentration in the CBD (R = 0.32) for client-facing operations and strategic clustering in peripheral innovation corridors (R = 0.40) for R&D activities, reflecting sector segmentation by business function and spatial needs at different scales.\n\n## Conclusion\nThis geospatial analysis of new business registrations in Singapore for the first half of 2025 reveals that commercial activity is far from randomly distributed, instead following distinct spatial patterns driven by agglomeration economies. Using rigorous spatial point pattern analysis, including Clark-Evans tests and KDE, the study moves beyond simple mapping to uncover why businesses locate where they do and the implications for urban planning. The findings demonstrate that business clustering is a consistent feature across sectors, reflecting strategic location decisions that maximize access to customers, infrastructure, and complementary services.\n\n**Food & Beverage (F\\&B):**\nF\\&B outlets show the strongest clustering among the sectors analyzed, with a Clark-Evans R value of 0.55. Clustering occurs at multiple scales: globally in the Central Region and locally in dense micro-clusters such as food streets in the Downtown Core, while Geylang and Outram exhibit smaller, consolidated clusters. The L-function analysis indicates that clustering is most pronounced at short distances (50–200 meters), reflecting strategic proximity to shared foot traffic. **Strategic Implication:** Urban planners should support these self-reinforcing clusters by enhancing pedestrian infrastructure, managing logistics, and creating vibrant, accessible precincts rather than dispersing outlets artificially.\n\n**Retail Trade:**\nRetail businesses exhibit stable clustering over time, with R values consistently below 1 (0.61–0.78) across the first half of 2025. Core clusters remain dominant in the Central Region, though some suburban areas show emerging activity, indicating potential shifts in demand. **Strategic Implication:** The temporal and spatial consistency of retail clusters supports targeted infrastructure investments, such as public transport and utilities, in established commercial zones, and guides the planning of regional centres as envisioned in Singapore’s master plan.\n\n**Information Technology (IT):**\nThe IT sector displays a dual spatial pattern, with extreme clustering in the Downtown Core (R = 0.32) to leverage proximity to clients, talent, and venture capital, and significant but different clustering outside the CBD in innovation hubs like one-north. **Strategic Implication:** Planners need a dual approach: facilitating high-density connectivity in the CBD for corporate IT and fintech firms, while also nurturing specialized peripheral hubs with tailored amenities for R\\&D and innovation-focused companies. Overall, the analysis emphasizes that supporting existing clusters through zoning, infrastructure, and monitoring can maximize economic efficiency and foster sustainable urban growth.\n\n## Future work\n\nWhile this analysis provides a robust foundation for understanding the spatial distribution of new businesses in Singapore, several avenues for future research remain open. These directions address limitations in the current study and explore more sophisticated analytical techniques that could yield deeper insights.\n\n1. Incorporating Covariates and Spatial Regression\nThis is a game-changer. Moving from descriptive clustering to explanatory modeling allows you to answer why businesses cluster where they do. By integrating demographic, infrastructure, zoning, and economic variables, you can quantify the drivers of spatial behavior. This opens doors to predictive modeling, policy evaluation, and targeted urban interventions—especially useful for planners, investors, and government agencies.\n\n2. Temporal Analysis at Finer Resolution & Forecasting\nUnderstanding when businesses emerge is just as powerful as knowing where. Weekly or daily trends can reveal responses to policy shifts, market cycles, or even social events. Coupling this with spatio-temporal forecasting lets you anticipate future hotspots—critical for infrastructure planning, retail strategy, and economic resilience.\n\n3. Multi-Type Point Pattern Analysis\nThis adds a layer of relational intelligence. By analyzing how different business types interact spatially (e.g., IT firms clustering near F&B outlets), you can uncover ecosystem dynamics—valuable for designing mixed-use developments, optimizing tenant mixes, or supporting innovation districts. It’s especially relevant in Singapore’s compact urban fabric where synergy matters.\n\n\n## Reference\n\n1. First-order Spatial Point Patterns Analysis Methods - https://r4gdsa.netlify.app/chap04.html\n\n2. 2nd Order Spatial Point Patterns Analysis Methods - \nhttps://r4gdsa.netlify.app/chap05.html\n\n3. Spatio-Temporal Point Patterns Analysis - https://r4gdsa.netlify.app/chap06.html\n\n\n\n\n\n",
    "supporting": [
      "Take-home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.11.0/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}